// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAiConfigs = `-- name: CountAiConfigs :one
SELECT COUNT(*) FROM ai_configs
`

func (q *Queries) CountAiConfigs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAiConfigs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAiConfigs = `-- name: CountUserAiConfigs :one
SELECT COUNT(*) FROM user_ai_provider_configs WHERE user_id = ?
`

func (q *Queries) CountUserAiConfigs(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAiConfigs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAiConfig = `-- name: CreateAiConfig :execresult
INSERT INTO ai_configs (id, provider, api_key_enc, model, base_url, is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAiConfigParams struct {
	ID        string         `json:"id"`
	Provider  string         `json:"provider"`
	ApiKeyEnc string         `json:"api_key_enc"`
	Model     string         `json:"model"`
	BaseUrl   sql.NullString `json:"base_url"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateAiConfig(ctx context.Context, arg CreateAiConfigParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAiConfig,
		arg.ID,
		arg.Provider,
		arg.ApiKeyEnc,
		arg.Model,
		arg.BaseUrl,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createUserAiConfig = `-- name: CreateUserAiConfig :execresult
INSERT INTO user_ai_provider_configs (id, user_id, provider, api_key_enc, model, base_url, is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserAiConfigParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Provider  string         `json:"provider"`
	ApiKeyEnc string         `json:"api_key_enc"`
	Model     string         `json:"model"`
	BaseUrl   sql.NullString `json:"base_url"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUserAiConfig(ctx context.Context, arg CreateUserAiConfigParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserAiConfig,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ApiKeyEnc,
		arg.Model,
		arg.BaseUrl,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteAiConfig = `-- name: DeleteAiConfig :execrows
DELETE FROM ai_configs WHERE provider = ?
`

func (q *Queries) DeleteAiConfig(ctx context.Context, provider string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAiConfig, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserAiConfig = `-- name: DeleteUserAiConfig :execrows
DELETE FROM user_ai_provider_configs WHERE user_id = ? AND provider = ?
`

type DeleteUserAiConfigParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteUserAiConfig(ctx context.Context, arg DeleteUserAiConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserAiConfig, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAiConfigByProvider = `-- name: GetAiConfigByProvider :one
SELECT id, provider, api_key_enc, model, base_url, is_active, created_at, updated_at
FROM ai_configs
WHERE provider = ?
`

func (q *Queries) GetAiConfigByProvider(ctx context.Context, provider string) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, getAiConfigByProvider, provider)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ApiKeyEnc,
		&i.Model,
		&i.BaseUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAiConfig = `-- name: GetUserAiConfig :one
SELECT id, user_id, provider, api_key_enc, model, base_url, is_active, created_at, updated_at
FROM user_ai_provider_configs
WHERE user_id = ? AND provider = ?
`

type GetUserAiConfigParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetUserAiConfig(ctx context.Context, arg GetUserAiConfigParams) (UserAiProviderConfig, error) {
	row := q.db.QueryRowContext(ctx, getUserAiConfig, arg.UserID, arg.Provider)
	var i UserAiProviderConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ApiKeyEnc,
		&i.Model,
		&i.BaseUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAiConfigs = `-- name: ListAiConfigs :many

SELECT id, provider, api_key_enc, model, base_url, is_active, created_at, updated_at
FROM ai_configs
ORDER BY provider ASC
`

// ============================================================================
// AI config queries (T21).
//
// Two distinct tables:
//
//	ai_configs                 — admin-global provider configs (no user_id)
//	user_ai_provider_configs   — per-user overrides
//
// Field notes:
//
//	api_key_enc: ciphertext (AES-256-GCM). The Go layer encrypts on write
//	             and decrypts on read for masking. List/upsert endpoints
//	             only ever return the masked form.
//	base_url: nullable for the official gemini/openai/claude providers
//	          that have a fixed endpoint. Required for openai-compatible
//	          and ollama.
//
// ============================================================================
func (q *Queries) ListAiConfigs(ctx context.Context) ([]AiConfig, error) {
	rows, err := q.db.QueryContext(ctx, listAiConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiConfig{}
	for rows.Next() {
		var i AiConfig
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ApiKeyEnc,
			&i.Model,
			&i.BaseUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAiConfigs = `-- name: ListUserAiConfigs :many

SELECT id, user_id, provider, api_key_enc, model, base_url, is_active, created_at, updated_at
FROM user_ai_provider_configs
WHERE user_id = ?
ORDER BY provider ASC
`

// ============================================================================
// user_ai_provider_configs
// ============================================================================
func (q *Queries) ListUserAiConfigs(ctx context.Context, userID string) ([]UserAiProviderConfig, error) {
	rows, err := q.db.QueryContext(ctx, listUserAiConfigs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAiProviderConfig{}
	for rows.Next() {
		var i UserAiProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ApiKeyEnc,
			&i.Model,
			&i.BaseUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAiConfig = `-- name: UpdateAiConfig :exec
UPDATE ai_configs
SET api_key_enc = ?,
    model       = ?,
    base_url    = ?,
    is_active   = ?,
    updated_at  = ?
WHERE provider = ?
`

type UpdateAiConfigParams struct {
	ApiKeyEnc string         `json:"api_key_enc"`
	Model     string         `json:"model"`
	BaseUrl   sql.NullString `json:"base_url"`
	IsActive  bool           `json:"is_active"`
	UpdatedAt time.Time      `json:"updated_at"`
	Provider  string         `json:"provider"`
}

func (q *Queries) UpdateAiConfig(ctx context.Context, arg UpdateAiConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateAiConfig,
		arg.ApiKeyEnc,
		arg.Model,
		arg.BaseUrl,
		arg.IsActive,
		arg.UpdatedAt,
		arg.Provider,
	)
	return err
}

const updateUserAiConfig = `-- name: UpdateUserAiConfig :exec
UPDATE user_ai_provider_configs
SET api_key_enc = ?,
    model       = ?,
    base_url    = ?,
    is_active   = ?,
    updated_at  = ?
WHERE user_id = ? AND provider = ?
`

type UpdateUserAiConfigParams struct {
	ApiKeyEnc string         `json:"api_key_enc"`
	Model     string         `json:"model"`
	BaseUrl   sql.NullString `json:"base_url"`
	IsActive  bool           `json:"is_active"`
	UpdatedAt time.Time      `json:"updated_at"`
	UserID    string         `json:"user_id"`
	Provider  string         `json:"provider"`
}

func (q *Queries) UpdateUserAiConfig(ctx context.Context, arg UpdateUserAiConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAiConfig,
		arg.ApiKeyEnc,
		arg.Model,
		arg.BaseUrl,
		arg.IsActive,
		arg.UpdatedAt,
		arg.UserID,
		arg.Provider,
	)
	return err
}
