// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const writeAuditLog = `-- name: WriteAuditLog :execresult
INSERT INTO audit_logs (
  id, user_id, action, entity, entity_id, details, ip_address, user_agent, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type WriteAuditLogParams struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Action    string         `json:"action"`
	Entity    string         `json:"entity"`
	EntityID  sql.NullString `json:"entity_id"`
	Details   sql.NullString `json:"details"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt time.Time      `json:"created_at"`
}

// Append an audit log entry. Caller supplies the id (uuid) and the
// timestamp; details is a JSON blob (TEXT in MySQL) for the before/after
// diff that NestJS's AuditLogService stores.
func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, writeAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
	)
}
