// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countActivePrimaryProviders = `-- name: CountActivePrimaryProviders :one
SELECT COUNT(*) AS count
FROM user_provider_accounts
WHERE user_id = ? AND is_primary = 1 AND deleted_at IS NULL
`

// Last-primary guard for the unlink endpoint: at least one active primary
// provider must remain for a user (typically their email_password binding).
// Phase 2 T11: don't allow unlinking the last primary.
func (q *Queries) CountActivePrimaryProviders(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePrimaryProviders, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveRefreshTokensForUser = `-- name: CountActiveRefreshTokensForUser :one
SELECT COUNT(*) AS count
FROM refresh_tokens
WHERE user_id = ? AND expires_at >= ?
`

type CountActiveRefreshTokensForUserParams struct {
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Diagnostics / test helper: how many non-expired refresh tokens does a
// user currently hold? Used by the e2e reuse-detection test.
func (q *Queries) CountActiveRefreshTokensForUser(ctx context.Context, arg CountActiveRefreshTokensForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRefreshTokensForUser, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserProviderAccounts = `-- name: CountUserProviderAccounts :one
SELECT COUNT(*) AS count FROM user_provider_accounts
WHERE user_id = ? AND deleted_at IS NULL
`

// Used to refuse unlinking the last provider for a user.
func (q *Queries) CountUserProviderAccounts(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserProviderAccounts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :execresult
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// Stores a password-reset token (hashed, CHAR(64)).
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
}

const createProviderAccount = `-- name: CreateProviderAccount :execresult
INSERT INTO user_provider_accounts (
  id, user_id, provider, provider_user_id,
  email, display_name, is_primary, linked_at, last_used_at, deleted_at,
  profile, created_at, updated_at
) VALUES (
  ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?,
  ?, ?, ?
)
`

type CreateProviderAccountParams struct {
	ID             string          `json:"id"`
	UserID         string          `json:"user_id"`
	Provider       string          `json:"provider"`
	ProviderUserID string          `json:"provider_user_id"`
	Email          sql.NullString  `json:"email"`
	DisplayName    sql.NullString  `json:"display_name"`
	IsPrimary      bool            `json:"is_primary"`
	LinkedAt       time.Time       `json:"linked_at"`
	LastUsedAt     time.Time       `json:"last_used_at"`
	DeletedAt      sql.NullTime    `json:"deleted_at"`
	Profile        json.RawMessage `json:"profile"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

// Binds a new auth provider to a user (email_password / oauth.google / sso.saml).
func (q *Queries) CreateProviderAccount(ctx context.Context, arg CreateProviderAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProviderAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.DisplayName,
		arg.IsPrimary,
		arg.LinkedAt,
		arg.LastUsedAt,
		arg.DeletedAt,
		arg.Profile,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createRefreshToken = `-- name: CreateRefreshToken :execresult
INSERT INTO refresh_tokens (id, token, user_id, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateRefreshTokenParams struct {
	ID        string    `json:"id"`
	Token     string    `json:"token"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// Stores a refresh token. Caller supplies the opaque token value.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < ?
`

// Periodic janitor. Wipes all tokens whose expires_at is in the past.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens, expiresAt)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE id = ?
`

// Revoke a single refresh token (rotation / logout).
func (q *Queries) DeleteRefreshToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, id)
	return err
}

const deleteRefreshTokenByToken = `-- name: DeleteRefreshTokenByToken :execrows
DELETE FROM refresh_tokens
WHERE token = ? AND expires_at >= ?
`

type DeleteRefreshTokenByTokenParams struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Atomic consume a refresh token by its hashed value. Returns the number of
// rows deleted (0 = token was already consumed / rotated / never existed;
// 1 = this call consumed it). Used by /auth/refresh for race-free rotation.
func (q *Queries) DeleteRefreshTokenByToken(ctx context.Context, arg DeleteRefreshTokenByTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRefreshTokenByToken, arg.Token, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = ?
`

// Look up by the hashed token. Service compares the hash of the submitted value.
func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderAccountByID = `-- name: GetProviderAccountByID :one
SELECT id, user_id, provider, provider_user_id,
       email, display_name, is_primary, linked_at, last_used_at, deleted_at,
       profile, created_at, updated_at
FROM user_provider_accounts
WHERE id = ?
`

// Look up a specific provider binding by id. Used by the unlink endpoint
// to verify ownership and read is_primary for the last-primary guard.
func (q *Queries) GetProviderAccountByID(ctx context.Context, id string) (UserProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getProviderAccountByID, id)
	var i UserProviderAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.DisplayName,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.Profile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderAccountByProvider = `-- name: GetProviderAccountByProvider :one
SELECT id, user_id, provider, provider_user_id,
       email, display_name, is_primary, linked_at, last_used_at, deleted_at,
       profile, created_at, updated_at
FROM user_provider_accounts
WHERE provider = ? AND provider_user_id = ? AND deleted_at IS NULL
`

type GetProviderAccountByProviderParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

// OAuth/SAML callback flow: look up (provider, providerUserId).
func (q *Queries) GetProviderAccountByProvider(ctx context.Context, arg GetProviderAccountByProviderParams) (UserProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getProviderAccountByProvider, arg.Provider, arg.ProviderUserID)
	var i UserProviderAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.DisplayName,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.Profile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token, user_id, expires_at, created_at
FROM refresh_tokens
WHERE token = ?
`

// Looks up a refresh token by its raw value. Used on /auth/refresh.
func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProviderAccountsByUser = `-- name: ListProviderAccountsByUser :many
SELECT id, user_id, provider, provider_user_id,
       email, display_name, is_primary, linked_at, last_used_at, deleted_at,
       profile, created_at, updated_at
FROM user_provider_accounts
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY is_primary DESC, linked_at ASC
`

// User's BindingsPage.
func (q *Queries) ListProviderAccountsByUser(ctx context.Context, userID string) ([]UserProviderAccount, error) {
	rows, err := q.db.QueryContext(ctx, listProviderAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserProviderAccount{}
	for rows.Next() {
		var i UserProviderAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.DisplayName,
			&i.IsPrimary,
			&i.LinkedAt,
			&i.LastUsedAt,
			&i.DeletedAt,
			&i.Profile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used_at = ?
WHERE id = ?
`

type MarkPasswordResetTokenUsedParams struct {
	UsedAt sql.NullTime `json:"used_at"`
	ID     string       `json:"id"`
}

// Once the user has reset their password, mark the token consumed.
func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, arg.UsedAt, arg.ID)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
DELETE FROM refresh_tokens
WHERE user_id = ?
`

// Cascade revoke: wipe every refresh token for a given user. Used for
// reuse detection (replay of a rotated token) and password-reset
// "log out everywhere" semantics. T7 deliverable.
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const softDeleteProviderAccount = `-- name: SoftDeleteProviderAccount :exec
UPDATE user_provider_accounts
SET deleted_at = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteProviderAccountParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

// Unlink a provider from a user. Soft delete keeps the audit trail
// (P2 redesign: don't hard-delete bindings, in case a user re-binds and
// we want to see history).
func (q *Queries) SoftDeleteProviderAccount(ctx context.Context, arg SoftDeleteProviderAccountParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteProviderAccount, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const unlinkProviderAccount = `-- name: UnlinkProviderAccount :execrows
UPDATE user_provider_accounts SET deleted_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type UnlinkProviderAccountParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
}

func (q *Queries) UnlinkProviderAccount(ctx context.Context, arg UnlinkProviderAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unlinkProviderAccount, arg.DeletedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
