// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: badges.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countBadgeDistribution = `-- name: CountBadgeDistribution :many
SELECT badge_id, COUNT(*) AS cnt FROM user_badges GROUP BY badge_id ORDER BY cnt DESC
`

type CountBadgeDistributionRow struct {
	BadgeID string `json:"badge_id"`
	Cnt     int64  `json:"cnt"`
}

func (q *Queries) CountBadgeDistribution(ctx context.Context) ([]CountBadgeDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, countBadgeDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBadgeDistributionRow{}
	for rows.Next() {
		var i CountBadgeDistributionRow
		if err := rows.Scan(&i.BadgeID, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUserBadges = `-- name: CountUserBadges :one
SELECT COUNT(*) FROM user_badges
`

func (q *Queries) CountUserBadges(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserBadges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBadge = `-- name: CreateBadge :execresult
INSERT INTO badges (id, code, name, description, icon, category, criteria_type, criteria_value, criteria_json, points, is_active, order_index, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBadgeParams struct {
	ID            string             `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          string             `json:"icon"`
	Category      string             `json:"category"`
	CriteriaType  BadgesCriteriaType `json:"criteria_type"`
	CriteriaValue int32              `json:"criteria_value"`
	CriteriaJson  json.RawMessage    `json:"criteria_json"`
	Points        int32              `json:"points"`
	IsActive      bool               `json:"is_active"`
	OrderIndex    int32              `json:"order_index"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBadge,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Category,
		arg.CriteriaType,
		arg.CriteriaValue,
		arg.CriteriaJson,
		arg.Points,
		arg.IsActive,
		arg.OrderIndex,
		arg.UpdatedAt,
	)
}

const createUserBadge = `-- name: CreateUserBadge :execresult
INSERT INTO user_badges (id, user_id, badge_id, unlocked_at)
VALUES (?, ?, ?, ?)
`

type CreateUserBadgeParams struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	BadgeID    string    `json:"badge_id"`
	UnlockedAt time.Time `json:"unlocked_at"`
}

func (q *Queries) CreateUserBadge(ctx context.Context, arg CreateUserBadgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserBadge,
		arg.ID,
		arg.UserID,
		arg.BadgeID,
		arg.UnlockedAt,
	)
}

const deleteBadge = `-- name: DeleteBadge :exec
DELETE FROM badges WHERE id = ?
`

func (q *Queries) DeleteBadge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBadge, id)
	return err
}

const getBadgeByCode = `-- name: GetBadgeByCode :one
SELECT id, code, name, description, icon, category, criteria_type,
       criteria_value, IFNULL(criteria_json, JSON_OBJECT()) AS criteria_json,
       points, is_active, order_index, created_at, updated_at
FROM badges WHERE code = ?
`

type GetBadgeByCodeRow struct {
	ID            string             `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          string             `json:"icon"`
	Category      string             `json:"category"`
	CriteriaType  BadgesCriteriaType `json:"criteria_type"`
	CriteriaValue int32              `json:"criteria_value"`
	CriteriaJson  interface{}        `json:"criteria_json"`
	Points        int32              `json:"points"`
	IsActive      bool               `json:"is_active"`
	OrderIndex    int32              `json:"order_index"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

func (q *Queries) GetBadgeByCode(ctx context.Context, code string) (GetBadgeByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getBadgeByCode, code)
	var i GetBadgeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Category,
		&i.CriteriaType,
		&i.CriteriaValue,
		&i.CriteriaJson,
		&i.Points,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBadgeByID = `-- name: GetBadgeByID :one
SELECT id, code, name, description, icon, category, criteria_type,
       criteria_value, IFNULL(criteria_json, JSON_OBJECT()) AS criteria_json,
       points, is_active, order_index, created_at, updated_at
FROM badges WHERE id = ?
`

type GetBadgeByIDRow struct {
	ID            string             `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          string             `json:"icon"`
	Category      string             `json:"category"`
	CriteriaType  BadgesCriteriaType `json:"criteria_type"`
	CriteriaValue int32              `json:"criteria_value"`
	CriteriaJson  interface{}        `json:"criteria_json"`
	Points        int32              `json:"points"`
	IsActive      bool               `json:"is_active"`
	OrderIndex    int32              `json:"order_index"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

func (q *Queries) GetBadgeByID(ctx context.Context, id string) (GetBadgeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBadgeByID, id)
	var i GetBadgeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Category,
		&i.CriteriaType,
		&i.CriteriaValue,
		&i.CriteriaJson,
		&i.Points,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBadge = `-- name: GetUserBadge :one
SELECT id, user_id, badge_id, unlocked_at FROM user_badges WHERE user_id = ? AND badge_id = ?
`

type GetUserBadgeParams struct {
	UserID  string `json:"user_id"`
	BadgeID string `json:"badge_id"`
}

// Used by checkAndAward to detect duplicates (unique key on user_id+badge_id).
func (q *Queries) GetUserBadge(ctx context.Context, arg GetUserBadgeParams) (UserBadge, error) {
	row := q.db.QueryRowContext(ctx, getUserBadge, arg.UserID, arg.BadgeID)
	var i UserBadge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BadgeID,
		&i.UnlockedAt,
	)
	return i, err
}

const listActiveBadges = `-- name: ListActiveBadges :many
SELECT id, code, name, description, icon, category, criteria_type,
       criteria_value, IFNULL(criteria_json, JSON_OBJECT()) AS criteria_json,
       points, is_active, order_index, created_at, updated_at
FROM badges WHERE is_active = 1
ORDER BY category ASC, order_index ASC, created_at ASC
`

type ListActiveBadgesRow struct {
	ID            string             `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          string             `json:"icon"`
	Category      string             `json:"category"`
	CriteriaType  BadgesCriteriaType `json:"criteria_type"`
	CriteriaValue int32              `json:"criteria_value"`
	CriteriaJson  interface{}        `json:"criteria_json"`
	Points        int32              `json:"points"`
	IsActive      bool               `json:"is_active"`
	OrderIndex    int32              `json:"order_index"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// Public list — only active badges, sorted by category + order.
// IFNULL(criteria_json, ...) returns an empty JSON object instead of
// NULL so the *json.RawMessage scan target doesn't fail.
func (q *Queries) ListActiveBadges(ctx context.Context) ([]ListActiveBadgesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBadgesRow{}
	for rows.Next() {
		var i ListActiveBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Category,
			&i.CriteriaType,
			&i.CriteriaValue,
			&i.CriteriaJson,
			&i.Points,
			&i.IsActive,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBadges = `-- name: ListAllBadges :many
SELECT id, code, name, description, icon, category, criteria_type,
       criteria_value, IFNULL(criteria_json, JSON_OBJECT()) AS criteria_json,
       points, is_active, order_index, created_at, updated_at
FROM badges
ORDER BY category ASC, order_index ASC, created_at ASC
`

type ListAllBadgesRow struct {
	ID            string             `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          string             `json:"icon"`
	Category      string             `json:"category"`
	CriteriaType  BadgesCriteriaType `json:"criteria_type"`
	CriteriaValue int32              `json:"criteria_value"`
	CriteriaJson  interface{}        `json:"criteria_json"`
	Points        int32              `json:"points"`
	IsActive      bool               `json:"is_active"`
	OrderIndex    int32              `json:"order_index"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// Admin list — includes inactive badges.
func (q *Queries) ListAllBadges(ctx context.Context) ([]ListAllBadgesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBadgesRow{}
	for rows.Next() {
		var i ListAllBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Category,
			&i.CriteriaType,
			&i.CriteriaValue,
			&i.CriteriaJson,
			&i.Points,
			&i.IsActive,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBadges = `-- name: ListUserBadges :many
SELECT id, user_id, badge_id, unlocked_at FROM user_badges WHERE user_id = ?
`

func (q *Queries) ListUserBadges(ctx context.Context, userID string) ([]UserBadge, error) {
	rows, err := q.db.QueryContext(ctx, listUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBadge{}
	for rows.Next() {
		var i UserBadge
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BadgeID,
			&i.UnlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBadge = `-- name: UpdateBadge :exec
UPDATE badges
SET code = ?, name = ?, description = ?, icon = ?, category = ?,
    criteria_type = ?, criteria_value = ?, criteria_json = ?, points = ?,
    is_active = ?, order_index = ?, updated_at = ?
WHERE id = ?
`

type UpdateBadgeParams struct {
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          string             `json:"icon"`
	Category      string             `json:"category"`
	CriteriaType  BadgesCriteriaType `json:"criteria_type"`
	CriteriaValue int32              `json:"criteria_value"`
	CriteriaJson  json.RawMessage    `json:"criteria_json"`
	Points        int32              `json:"points"`
	IsActive      bool               `json:"is_active"`
	OrderIndex    int32              `json:"order_index"`
	UpdatedAt     time.Time          `json:"updated_at"`
	ID            string             `json:"id"`
}

func (q *Queries) UpdateBadge(ctx context.Context, arg UpdateBadgeParams) error {
	_, err := q.db.ExecContext(ctx, updateBadge,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Category,
		arg.CriteriaType,
		arg.CriteriaValue,
		arg.CriteriaJson,
		arg.Points,
		arg.IsActive,
		arg.OrderIndex,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
