// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countSerialByPrefix = `-- name: CountSerialByPrefix :one
SELECT COUNT(*) FROM certificates WHERE serial_number LIKE ?
`

// Returns the count of existing certificates with the same serial prefix.
// Used by the serial number generator to detect when to bump the sequence.
// Note: the actual seq is parsed from the serial_number string at the Go
// layer (serial format: OCSG-{year}-{TYPE}-{0001..N}).
func (q *Queries) CountSerialByPrefix(ctx context.Context, serialNumber string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSerialByPrefix, serialNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCertificate = `-- name: CreateCertificate :execresult
INSERT INTO certificates
  (id, user_id, type, ref_id, title, description, serial_number, issued_at, completed_at, image_url, verify_url, metadata, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCertificateParams struct {
	ID           string           `json:"id"`
	UserID       string           `json:"user_id"`
	Type         CertificatesType `json:"type"`
	RefID        string           `json:"ref_id"`
	Title        string           `json:"title"`
	Description  sql.NullString   `json:"description"`
	SerialNumber string           `json:"serial_number"`
	IssuedAt     time.Time        `json:"issued_at"`
	CompletedAt  time.Time        `json:"completed_at"`
	ImageUrl     sql.NullString   `json:"image_url"`
	VerifyUrl    sql.NullString   `json:"verify_url"`
	Metadata     json.RawMessage  `json:"metadata"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCertificate,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.RefID,
		arg.Title,
		arg.Description,
		arg.SerialNumber,
		arg.IssuedAt,
		arg.CompletedAt,
		arg.ImageUrl,
		arg.VerifyUrl,
		arg.Metadata,
		arg.UpdatedAt,
	)
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, user_id, type, ref_id, title, description, serial_number,
       issued_at, completed_at, image_url, verify_url,
       IFNULL(metadata, JSON_OBJECT()) AS metadata,
       revoked_at, created_at, updated_at
FROM certificates WHERE id = ?
`

type GetCertificateByIDRow struct {
	ID           string           `json:"id"`
	UserID       string           `json:"user_id"`
	Type         CertificatesType `json:"type"`
	RefID        string           `json:"ref_id"`
	Title        string           `json:"title"`
	Description  sql.NullString   `json:"description"`
	SerialNumber string           `json:"serial_number"`
	IssuedAt     time.Time        `json:"issued_at"`
	CompletedAt  time.Time        `json:"completed_at"`
	ImageUrl     sql.NullString   `json:"image_url"`
	VerifyUrl    sql.NullString   `json:"verify_url"`
	Metadata     interface{}      `json:"metadata"`
	RevokedAt    sql.NullTime     `json:"revoked_at"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

func (q *Queries) GetCertificateByID(ctx context.Context, id string) (GetCertificateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateByID, id)
	var i GetCertificateByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.RefID,
		&i.Title,
		&i.Description,
		&i.SerialNumber,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.ImageUrl,
		&i.VerifyUrl,
		&i.Metadata,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificateBySerial = `-- name: GetCertificateBySerial :one
SELECT id, user_id, type, ref_id, title, description, serial_number,
       issued_at, completed_at, image_url, verify_url,
       IFNULL(metadata, JSON_OBJECT()) AS metadata,
       revoked_at, created_at, updated_at
FROM certificates WHERE serial_number = ?
`

type GetCertificateBySerialRow struct {
	ID           string           `json:"id"`
	UserID       string           `json:"user_id"`
	Type         CertificatesType `json:"type"`
	RefID        string           `json:"ref_id"`
	Title        string           `json:"title"`
	Description  sql.NullString   `json:"description"`
	SerialNumber string           `json:"serial_number"`
	IssuedAt     time.Time        `json:"issued_at"`
	CompletedAt  time.Time        `json:"completed_at"`
	ImageUrl     sql.NullString   `json:"image_url"`
	VerifyUrl    sql.NullString   `json:"verify_url"`
	Metadata     interface{}      `json:"metadata"`
	RevokedAt    sql.NullTime     `json:"revoked_at"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

// Used by verifyCertificate for the public /verify/:serial endpoint.
func (q *Queries) GetCertificateBySerial(ctx context.Context, serialNumber string) (GetCertificateBySerialRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateBySerial, serialNumber)
	var i GetCertificateBySerialRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.RefID,
		&i.Title,
		&i.Description,
		&i.SerialNumber,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.ImageUrl,
		&i.VerifyUrl,
		&i.Metadata,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificateByUserTypeRef = `-- name: GetCertificateByUserTypeRef :one
SELECT id, user_id, type, ref_id, title, description, serial_number,
       issued_at, completed_at, image_url, verify_url,
       IFNULL(metadata, JSON_OBJECT()) AS metadata,
       revoked_at, created_at, updated_at
FROM certificates WHERE user_id = ? AND type = ? AND ref_id = ?
`

type GetCertificateByUserTypeRefParams struct {
	UserID string           `json:"user_id"`
	Type   CertificatesType `json:"type"`
	RefID  string           `json:"ref_id"`
}

type GetCertificateByUserTypeRefRow struct {
	ID           string           `json:"id"`
	UserID       string           `json:"user_id"`
	Type         CertificatesType `json:"type"`
	RefID        string           `json:"ref_id"`
	Title        string           `json:"title"`
	Description  sql.NullString   `json:"description"`
	SerialNumber string           `json:"serial_number"`
	IssuedAt     time.Time        `json:"issued_at"`
	CompletedAt  time.Time        `json:"completed_at"`
	ImageUrl     sql.NullString   `json:"image_url"`
	VerifyUrl    sql.NullString   `json:"verify_url"`
	Metadata     interface{}      `json:"metadata"`
	RevokedAt    sql.NullTime     `json:"revoked_at"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

// Idempotency check for issueCertificate: same (user, type, ref) returns
// the existing certificate.
func (q *Queries) GetCertificateByUserTypeRef(ctx context.Context, arg GetCertificateByUserTypeRefParams) (GetCertificateByUserTypeRefRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateByUserTypeRef, arg.UserID, arg.Type, arg.RefID)
	var i GetCertificateByUserTypeRefRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.RefID,
		&i.Title,
		&i.Description,
		&i.SerialNumber,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.ImageUrl,
		&i.VerifyUrl,
		&i.Metadata,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMyCertificates = `-- name: ListMyCertificates :many
SELECT id, user_id, type, ref_id, title, description, serial_number,
       issued_at, completed_at, image_url, verify_url,
       IFNULL(metadata, JSON_OBJECT()) AS metadata,
       revoked_at, created_at, updated_at
FROM certificates
WHERE user_id = ? AND revoked_at IS NULL
  AND (? = '' OR type = ?)
ORDER BY issued_at DESC
`

type ListMyCertificatesParams struct {
	UserID  string           `json:"user_id"`
	Column2 interface{}      `json:"column_2"`
	Type    CertificatesType `json:"type"`
}

type ListMyCertificatesRow struct {
	ID           string           `json:"id"`
	UserID       string           `json:"user_id"`
	Type         CertificatesType `json:"type"`
	RefID        string           `json:"ref_id"`
	Title        string           `json:"title"`
	Description  sql.NullString   `json:"description"`
	SerialNumber string           `json:"serial_number"`
	IssuedAt     time.Time        `json:"issued_at"`
	CompletedAt  time.Time        `json:"completed_at"`
	ImageUrl     sql.NullString   `json:"image_url"`
	VerifyUrl    sql.NullString   `json:"verify_url"`
	Metadata     interface{}      `json:"metadata"`
	RevokedAt    sql.NullTime     `json:"revoked_at"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

// Returns the user's certificates, newest first, optionally filtered by type.
// Excludes revoked certificates (revokedAt IS NULL).
func (q *Queries) ListMyCertificates(ctx context.Context, arg ListMyCertificatesParams) ([]ListMyCertificatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyCertificates, arg.UserID, arg.Column2, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyCertificatesRow{}
	for rows.Next() {
		var i ListMyCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.RefID,
			&i.Title,
			&i.Description,
			&i.SerialNumber,
			&i.IssuedAt,
			&i.CompletedAt,
			&i.ImageUrl,
			&i.VerifyUrl,
			&i.Metadata,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :exec
UPDATE certificates SET revoked_at = ?, updated_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeCertificateParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) error {
	_, err := q.db.ExecContext(ctx, revokeCertificate, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	return err
}
