// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapters.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const chaptersByIDs = `-- name: ChaptersByIDs :many
SELECT id, course_id FROM chapters WHERE id IN (/*SLICE:ids*/?)
`

type ChaptersByIDsRow struct {
	ID       string `json:"id"`
	CourseID string `json:"course_id"`
}

// Used by reorder to fetch ownership in one query. Returns each
// chapter's id and course_id so the service can verify all belong to
// the same course (NestJS does the same in chapters.controller.ts:163-178).
func (q *Queries) ChaptersByIDs(ctx context.Context, ids []string) ([]ChaptersByIDsRow, error) {
	query := chaptersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChaptersByIDsRow{}
	for rows.Next() {
		var i ChaptersByIDsRow
		if err := rows.Scan(&i.ID, &i.CourseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChaptersInCourse = `-- name: CountChaptersInCourse :one
SELECT COUNT(*) AS count FROM chapters WHERE course_id = ? AND deleted_at IS NULL
`

// Sanity check / count.
func (q *Queries) CountChaptersInCourse(ctx context.Context, courseID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChaptersInCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChapter = `-- name: CreateChapter :execresult
INSERT INTO chapters (id, course_id, title, description, order_index, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateChapterParams struct {
	ID          string         `json:"id"`
	CourseID    string         `json:"course_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	OrderIndex  int32          `json:"order_index"`
	CreatedAt   time.Time      `json:"created_at"`
}

// Inserts a new chapter. Caller supplies id (uuid).
func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChapter,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.CreatedAt,
	)
}

const getChapterByID = `-- name: GetChapterByID :one
SELECT id, course_id, title, description, order_index, created_at, deleted_at
FROM chapters
WHERE id = ? AND deleted_at IS NULL
`

// Look up a chapter by primary key. Filters out soft-deleted.
func (q *Queries) GetChapterByID(ctx context.Context, id string) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapterByID, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChapterByIDIncludingDeleted = `-- name: GetChapterByIDIncludingDeleted :one
SELECT id, course_id, title, description, order_index, created_at, deleted_at
FROM chapters
WHERE id = ?
`

// Admin / internal: returns the chapter regardless of deleted_at.
func (q *Queries) GetChapterByIDIncludingDeleted(ctx context.Context, id string) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapterByIDIncludingDeleted, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChaptersByCourse = `-- name: ListChaptersByCourse :many
SELECT id, course_id, title, description, order_index, created_at, deleted_at
FROM chapters
WHERE course_id = ? AND deleted_at IS NULL
ORDER BY order_index ASC
`

// All non-deleted chapters for a course, ordered by orderIndex ASC.
func (q *Queries) ListChaptersByCourse(ctx context.Context, courseID string) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxChapterOrderIndex = `-- name: MaxChapterOrderIndex :one
SELECT COALESCE(MAX(order_index), -1) AS max_idx
FROM chapters WHERE course_id = ? AND deleted_at IS NULL
`

// For Create: figure out the next orderIndex. COALESCE(-1) so the
// first chapter gets 0.
func (q *Queries) MaxChapterOrderIndex(ctx context.Context, courseID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxChapterOrderIndex, courseID)
	var max_idx interface{}
	err := row.Scan(&max_idx)
	return max_idx, err
}

const softDeleteChapter = `-- name: SoftDeleteChapter :exec
UPDATE chapters
SET deleted_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteChapterParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        string       `json:"id"`
}

// Soft-delete a single chapter. Idempotent.
func (q *Queries) SoftDeleteChapter(ctx context.Context, arg SoftDeleteChapterParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteChapter, arg.DeletedAt, arg.ID)
	return err
}

const softDeleteChaptersByCourse = `-- name: SoftDeleteChaptersByCourse :execrows
UPDATE chapters
SET deleted_at = ?
WHERE course_id = ? AND deleted_at IS NULL
`

type SoftDeleteChaptersByCourseParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	CourseID  string       `json:"course_id"`
}

// Bulk soft-delete all chapters of a course. Returns count (used by
// ChapterService.Delete to cascade to lessons).
func (q *Queries) SoftDeleteChaptersByCourse(ctx context.Context, arg SoftDeleteChaptersByCourseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteChaptersByCourse, arg.DeletedAt, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateChapter = `-- name: UpdateChapter :exec
UPDATE chapters
SET title = ?, description = ?, order_index = ?
WHERE id = ?
`

type UpdateChapterParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	OrderIndex  int32          `json:"order_index"`
	ID          string         `json:"id"`
}

// Partial update. Caller shapes the patch (UpdateChapterPatch).
func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) error {
	_, err := q.db.ExecContext(ctx, updateChapter,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}
