// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createChatMessage = `-- name: CreateChatMessage :execresult
INSERT INTO chat_messages (id, session_id, role, content, tokens, created_at)
VALUES (?, ?, ?, ?, 0, ?)
`

type CreateChatMessageParams struct {
	ID        string           `json:"id"`
	SessionID string           `json:"session_id"`
	Role      ChatMessagesRole `json:"role"`
	Content   string           `json:"content"`
	CreatedAt time.Time        `json:"created_at"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
}

const createChatSession = `-- name: CreateChatSession :execresult
INSERT INTO chat_sessions (id, user_id, lesson_id, title, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateChatSessionParams struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	LessonID  sql.NullString `json:"lesson_id"`
	Title     sql.NullString `json:"title"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatSession,
		arg.ID,
		arg.UserID,
		arg.LessonID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteChatSession = `-- name: DeleteChatSession :execrows
DELETE FROM chat_sessions WHERE id = ? AND user_id = ?
`

type DeleteChatSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// Hard-delete (cascades to chat_messages via FK).
func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChatSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, user_id, lesson_id, title, created_at, updated_at
FROM chat_sessions
WHERE id = ? AND user_id = ?
`

type GetChatSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getChatSession, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LessonID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, session_id, role, content, tokens, created_at
FROM chat_messages
WHERE session_id = ?
ORDER BY created_at ASC
LIMIT 500
`

func (q *Queries) ListChatMessages(ctx context.Context, sessionID string) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Tokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT s.id, s.user_id, s.lesson_id, s.title, s.created_at, s.updated_at,
       (SELECT COUNT(*) FROM chat_messages m WHERE m.session_id = s.id) AS message_count
FROM chat_sessions s
WHERE s.user_id = ? AND s.lesson_id IS NULL
ORDER BY s.updated_at DESC
LIMIT 100
`

type ListChatSessionsRow struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	LessonID     sql.NullString `json:"lesson_id"`
	Title        sql.NullString `json:"title"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	MessageCount int64          `json:"message_count"`
}

// Returns the user's general-scope sessions, newest first, with message count.
func (q *Queries) ListChatSessions(ctx context.Context, userID string) ([]ListChatSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatSessionsRow{}
	for rows.Next() {
		var i ListChatSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChatSession = `-- name: TouchChatSession :exec
UPDATE chat_sessions SET updated_at = ? WHERE id = ?
`

type TouchChatSessionParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

// Bump updated_at when a new message is added.
func (q *Queries) TouchChatSession(ctx context.Context, arg TouchChatSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchChatSession, arg.UpdatedAt, arg.ID)
	return err
}
