// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cms.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"time"
)

const createAppSetting = `-- name: CreateAppSetting :execresult
INSERT INTO app_settings (` + "`" + `key` + "`" + `, value_json, scope, description, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAppSettingParams struct {
	Key         string           `json:"key"`
	ValueJson   json.RawMessage  `json:"value_json"`
	Scope       AppSettingsScope `json:"scope"`
	Description sql.NullString   `json:"description"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

func (q *Queries) CreateAppSetting(ctx context.Context, arg CreateAppSettingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAppSetting,
		arg.Key,
		arg.ValueJson,
		arg.Scope,
		arg.Description,
		arg.UpdatedAt,
	)
}

const createAuthProvider = `-- name: CreateAuthProvider :execresult
INSERT INTO auth_providers
  (id, label, icon, is_active, order_index, config)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAuthProviderParams struct {
	ID         string          `json:"id"`
	Label      string          `json:"label"`
	Icon       string          `json:"icon"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
	Config     json.RawMessage `json:"config"`
}

func (q *Queries) CreateAuthProvider(ctx context.Context, arg CreateAuthProviderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAuthProvider,
		arg.ID,
		arg.Label,
		arg.Icon,
		arg.IsActive,
		arg.OrderIndex,
		arg.Config,
	)
}

const createCourseCategory = `-- name: CreateCourseCategory :execresult
INSERT INTO course_categories
  (id, ` + "`" + `key` + "`" + `, label, is_active, order_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateCourseCategoryParams struct {
	ID         string `json:"id"`
	Key        string `json:"key"`
	Label      string `json:"label"`
	IsActive   bool   `json:"is_active"`
	OrderIndex int32  `json:"order_index"`
}

func (q *Queries) CreateCourseCategory(ctx context.Context, arg CreateCourseCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourseCategory,
		arg.ID,
		arg.Key,
		arg.Label,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const createDateFormatTemplate = `-- name: CreateDateFormatTemplate :execresult
INSERT INTO date_format_templates (scope, locale, template) VALUES (?, ?, ?)
`

type CreateDateFormatTemplateParams struct {
	Scope    DateFormatTemplatesScope `json:"scope"`
	Locale   string                   `json:"locale"`
	Template string                   `json:"template"`
}

func (q *Queries) CreateDateFormatTemplate(ctx context.Context, arg CreateDateFormatTemplateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDateFormatTemplate, arg.Scope, arg.Locale, arg.Template)
}

const createEnterpriseMethod = `-- name: CreateEnterpriseMethod :execresult
INSERT INTO enterprise_methods
  (id, num, title, ` + "`" + `desc` + "`" + `, bullets, is_active, order_index)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEnterpriseMethodParams struct {
	ID         string          `json:"id"`
	Num        string          `json:"num"`
	Title      string          `json:"title"`
	Desc       string          `json:"desc"`
	Bullets    json.RawMessage `json:"bullets"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
}

func (q *Queries) CreateEnterpriseMethod(ctx context.Context, arg CreateEnterpriseMethodParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEnterpriseMethod,
		arg.ID,
		arg.Num,
		arg.Title,
		arg.Desc,
		arg.Bullets,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const createEnumTranslation = `-- name: CreateEnumTranslation :execresult
INSERT INTO enum_translations
  (enum_type, enum_value, locale, label, color_class, icon, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEnumTranslationParams struct {
	EnumType   string         `json:"enum_type"`
	EnumValue  string         `json:"enum_value"`
	Locale     string         `json:"locale"`
	Label      string         `json:"label"`
	ColorClass sql.NullString `json:"color_class"`
	Icon       sql.NullString `json:"icon"`
	SortOrder  int32          `json:"sort_order"`
}

func (q *Queries) CreateEnumTranslation(ctx context.Context, arg CreateEnumTranslationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEnumTranslation,
		arg.EnumType,
		arg.EnumValue,
		arg.Locale,
		arg.Label,
		arg.ColorClass,
		arg.Icon,
		arg.SortOrder,
	)
}

const createFooterColumn = `-- name: CreateFooterColumn :execresult
INSERT INTO footer_columns (id, title, links, is_active, order_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateFooterColumnParams struct {
	ID         string          `json:"id"`
	Title      string          `json:"title"`
	Links      json.RawMessage `json:"links"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
}

func (q *Queries) CreateFooterColumn(ctx context.Context, arg CreateFooterColumnParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFooterColumn,
		arg.ID,
		arg.Title,
		arg.Links,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const createHotKeyword = `-- name: CreateHotKeyword :execresult
INSERT INTO hot_keywords
  (id, keyword, scope, is_active, order_index)
VALUES (?, ?, ?, ?, ?)
`

type CreateHotKeywordParams struct {
	ID         string           `json:"id"`
	Keyword    string           `json:"keyword"`
	Scope      HotKeywordsScope `json:"scope"`
	IsActive   bool             `json:"is_active"`
	OrderIndex int32            `json:"order_index"`
}

func (q *Queries) CreateHotKeyword(ctx context.Context, arg CreateHotKeywordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHotKeyword,
		arg.ID,
		arg.Keyword,
		arg.Scope,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const createI18nMessage = `-- name: CreateI18nMessage :execresult
INSERT INTO i18n_messages (` + "`" + `key` + "`" + `, locale, value, category) VALUES (?, ?, ?, ?)
`

type CreateI18nMessageParams struct {
	Key      string               `json:"key"`
	Locale   string               `json:"locale"`
	Value    string               `json:"value"`
	Category I18nMessagesCategory `json:"category"`
}

func (q *Queries) CreateI18nMessage(ctx context.Context, arg CreateI18nMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createI18nMessage,
		arg.Key,
		arg.Locale,
		arg.Value,
		arg.Category,
	)
}

const createIndustry = `-- name: CreateIndustry :execresult
INSERT INTO industries
  (id, ` + "`" + `key` + "`" + `, label, description, icon, methodology, is_active, order_index, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateIndustryParams struct {
	ID          string          `json:"id"`
	Key         string          `json:"key"`
	Label       string          `json:"label"`
	Description sql.NullString  `json:"description"`
	Icon        sql.NullString  `json:"icon"`
	Methodology json.RawMessage `json:"methodology"`
	IsActive    bool            `json:"is_active"`
	OrderIndex  int32           `json:"order_index"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Caller supplies id (cuid), created_at, updated_at.
func (q *Queries) CreateIndustry(ctx context.Context, arg CreateIndustryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIndustry,
		arg.ID,
		arg.Key,
		arg.Label,
		arg.Description,
		arg.Icon,
		arg.Methodology,
		arg.IsActive,
		arg.OrderIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createPageSetting = `-- name: CreatePageSetting :execresult
INSERT INTO page_settings (page, ` + "`" + `key` + "`" + `, value, description, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreatePageSettingParams struct {
	Page        string          `json:"page"`
	Key         string          `json:"key"`
	Value       json.RawMessage `json:"value"`
	Description sql.NullString  `json:"description"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) CreatePageSetting(ctx context.Context, arg CreatePageSettingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPageSetting,
		arg.Page,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.UpdatedAt,
	)
}

const createPopularSearch = `-- name: CreatePopularSearch :execresult
INSERT INTO popular_searches
  (id, keyword, click_count, is_active, order_index)
VALUES (?, ?, ?, ?, ?)
`

type CreatePopularSearchParams struct {
	ID         string `json:"id"`
	Keyword    string `json:"keyword"`
	ClickCount int32  `json:"click_count"`
	IsActive   bool   `json:"is_active"`
	OrderIndex int32  `json:"order_index"`
}

func (q *Queries) CreatePopularSearch(ctx context.Context, arg CreatePopularSearchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPopularSearch,
		arg.ID,
		arg.Keyword,
		arg.ClickCount,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const createQuickPrompt = `-- name: CreateQuickPrompt :execresult
INSERT INTO quick_prompts
  (id, emoji, label, prompt_text, scope, is_active, order_index)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateQuickPromptParams struct {
	ID         string            `json:"id"`
	Emoji      string            `json:"emoji"`
	Label      string            `json:"label"`
	PromptText string            `json:"prompt_text"`
	Scope      QuickPromptsScope `json:"scope"`
	IsActive   bool              `json:"is_active"`
	OrderIndex int32             `json:"order_index"`
}

func (q *Queries) CreateQuickPrompt(ctx context.Context, arg CreateQuickPromptParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createQuickPrompt,
		arg.ID,
		arg.Emoji,
		arg.Label,
		arg.PromptText,
		arg.Scope,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const createSiteSetting = `-- name: CreateSiteSetting :execresult
INSERT INTO site_settings (` + "`" + `key` + "`" + `, value, scope, description, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSiteSettingParams struct {
	Key         string            `json:"key"`
	Value       json.RawMessage   `json:"value"`
	Scope       SiteSettingsScope `json:"scope"`
	Description sql.NullString    `json:"description"`
	UpdatedAt   time.Time         `json:"updated_at"`
}

func (q *Queries) CreateSiteSetting(ctx context.Context, arg CreateSiteSettingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSiteSetting,
		arg.Key,
		arg.Value,
		arg.Scope,
		arg.Description,
		arg.UpdatedAt,
	)
}

const createTestimonial = `-- name: CreateTestimonial :execresult
INSERT INTO testimonials
  (id, name, title, quote, avatar, is_active, order_index)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTestimonialParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Title      string         `json:"title"`
	Quote      string         `json:"quote"`
	Avatar     sql.NullString `json:"avatar"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTestimonial,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Quote,
		arg.Avatar,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const createTopNavItem = `-- name: CreateTopNavItem :execresult
INSERT INTO top_nav_items
  (id, label, path, icon, is_active, order_index)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTopNavItemParams struct {
	ID         string         `json:"id"`
	Label      string         `json:"label"`
	Path       string         `json:"path"`
	Icon       sql.NullString `json:"icon"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
}

func (q *Queries) CreateTopNavItem(ctx context.Context, arg CreateTopNavItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTopNavItem,
		arg.ID,
		arg.Label,
		arg.Path,
		arg.Icon,
		arg.IsActive,
		arg.OrderIndex,
	)
}

const deleteAppSetting = `-- name: DeleteAppSetting :execresult
DELETE FROM app_settings WHERE ` + "`" + `key` + "`" + ` = ?
`

// Returns sql.Result so the service can check rows affected and
// surface 404 instead of 200 when the key doesn't exist.
func (q *Queries) DeleteAppSetting(ctx context.Context, key string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAppSetting, key)
}

const deleteAuthProvider = `-- name: DeleteAuthProvider :execresult
DELETE FROM auth_providers WHERE id = ?
`

func (q *Queries) DeleteAuthProvider(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAuthProvider, id)
}

const deleteCourseCategory = `-- name: DeleteCourseCategory :execresult
DELETE FROM course_categories WHERE id = ?
`

func (q *Queries) DeleteCourseCategory(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCourseCategory, id)
}

const deleteDateFormatTemplate = `-- name: DeleteDateFormatTemplate :execresult
DELETE FROM date_format_templates WHERE scope = ? AND locale = ?
`

type DeleteDateFormatTemplateParams struct {
	Scope  DateFormatTemplatesScope `json:"scope"`
	Locale string                   `json:"locale"`
}

func (q *Queries) DeleteDateFormatTemplate(ctx context.Context, arg DeleteDateFormatTemplateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDateFormatTemplate, arg.Scope, arg.Locale)
}

const deleteEnterpriseMethod = `-- name: DeleteEnterpriseMethod :execresult
DELETE FROM enterprise_methods WHERE id = ?
`

func (q *Queries) DeleteEnterpriseMethod(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEnterpriseMethod, id)
}

const deleteEnumTranslation = `-- name: DeleteEnumTranslation :execresult
DELETE FROM enum_translations
WHERE enum_type = ? AND enum_value = ? AND locale = ?
`

type DeleteEnumTranslationParams struct {
	EnumType  string `json:"enum_type"`
	EnumValue string `json:"enum_value"`
	Locale    string `json:"locale"`
}

func (q *Queries) DeleteEnumTranslation(ctx context.Context, arg DeleteEnumTranslationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEnumTranslation, arg.EnumType, arg.EnumValue, arg.Locale)
}

const deleteFooterColumn = `-- name: DeleteFooterColumn :execresult
DELETE FROM footer_columns WHERE id = ?
`

func (q *Queries) DeleteFooterColumn(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFooterColumn, id)
}

const deleteHotKeyword = `-- name: DeleteHotKeyword :execresult
DELETE FROM hot_keywords WHERE id = ?
`

func (q *Queries) DeleteHotKeyword(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteHotKeyword, id)
}

const deleteI18nMessage = `-- name: DeleteI18nMessage :execresult
DELETE FROM i18n_messages WHERE ` + "`" + `key` + "`" + ` = ? AND locale = ?
`

type DeleteI18nMessageParams struct {
	Key    string `json:"key"`
	Locale string `json:"locale"`
}

func (q *Queries) DeleteI18nMessage(ctx context.Context, arg DeleteI18nMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteI18nMessage, arg.Key, arg.Locale)
}

const deleteIndustry = `-- name: DeleteIndustry :execresult
DELETE FROM industries WHERE id = ?
`

func (q *Queries) DeleteIndustry(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteIndustry, id)
}

const deletePageSetting = `-- name: DeletePageSetting :execresult
DELETE FROM page_settings WHERE page = ? AND ` + "`" + `key` + "`" + ` = ?
`

type DeletePageSettingParams struct {
	Page string `json:"page"`
	Key  string `json:"key"`
}

func (q *Queries) DeletePageSetting(ctx context.Context, arg DeletePageSettingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePageSetting, arg.Page, arg.Key)
}

const deletePopularSearch = `-- name: DeletePopularSearch :execresult
DELETE FROM popular_searches WHERE id = ?
`

func (q *Queries) DeletePopularSearch(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePopularSearch, id)
}

const deleteQuickPrompt = `-- name: DeleteQuickPrompt :execresult
DELETE FROM quick_prompts WHERE id = ?
`

func (q *Queries) DeleteQuickPrompt(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuickPrompt, id)
}

const deleteSiteSetting = `-- name: DeleteSiteSetting :execresult
DELETE FROM site_settings WHERE ` + "`" + `key` + "`" + ` = ?
`

func (q *Queries) DeleteSiteSetting(ctx context.Context, key string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSiteSetting, key)
}

const deleteTestimonial = `-- name: DeleteTestimonial :execresult
DELETE FROM testimonials WHERE id = ?
`

func (q *Queries) DeleteTestimonial(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTestimonial, id)
}

const deleteTopNavItem = `-- name: DeleteTopNavItem :execresult
DELETE FROM top_nav_items WHERE id = ?
`

func (q *Queries) DeleteTopNavItem(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTopNavItem, id)
}

const getAppSettingByKey = `-- name: GetAppSettingByKey :one
SELECT ` + "`" + `key` + "`" + `, value_json, scope, description, updated_at FROM app_settings WHERE ` + "`" + `key` + "`" + ` = ?
`

func (q *Queries) GetAppSettingByKey(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSettingByKey, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.ValueJson,
		&i.Scope,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthProviderByID = `-- name: GetAuthProviderByID :one
SELECT id, label, icon, is_active, order_index, config FROM auth_providers WHERE id = ?
`

func (q *Queries) GetAuthProviderByID(ctx context.Context, id string) (AuthProvider, error) {
	row := q.db.QueryRowContext(ctx, getAuthProviderByID, id)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Icon,
		&i.IsActive,
		&i.OrderIndex,
		&i.Config,
	)
	return i, err
}

const getCourseCategoryByID = `-- name: GetCourseCategoryByID :one
SELECT id, ` + "`" + `key` + "`" + `, label, is_active, order_index FROM course_categories WHERE id = ?
`

func (q *Queries) GetCourseCategoryByID(ctx context.Context, id string) (CourseCategory, error) {
	row := q.db.QueryRowContext(ctx, getCourseCategoryByID, id)
	var i CourseCategory
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const getDateFormatTemplate = `-- name: GetDateFormatTemplate :one
SELECT scope, locale, template FROM date_format_templates WHERE scope = ? AND locale = ?
`

type GetDateFormatTemplateParams struct {
	Scope  DateFormatTemplatesScope `json:"scope"`
	Locale string                   `json:"locale"`
}

func (q *Queries) GetDateFormatTemplate(ctx context.Context, arg GetDateFormatTemplateParams) (DateFormatTemplate, error) {
	row := q.db.QueryRowContext(ctx, getDateFormatTemplate, arg.Scope, arg.Locale)
	var i DateFormatTemplate
	err := row.Scan(&i.Scope, &i.Locale, &i.Template)
	return i, err
}

const getEnterpriseMethodByID = `-- name: GetEnterpriseMethodByID :one
SELECT id, num, title, ` + "`" + `desc` + "`" + `, bullets, is_active, order_index FROM enterprise_methods WHERE id = ?
`

func (q *Queries) GetEnterpriseMethodByID(ctx context.Context, id string) (EnterpriseMethod, error) {
	row := q.db.QueryRowContext(ctx, getEnterpriseMethodByID, id)
	var i EnterpriseMethod
	err := row.Scan(
		&i.ID,
		&i.Num,
		&i.Title,
		&i.Desc,
		&i.Bullets,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const getEnumTranslation = `-- name: GetEnumTranslation :one
SELECT enum_type, enum_value, locale, label, color_class, icon, sort_order FROM enum_translations
WHERE enum_type = ? AND enum_value = ? AND locale = ?
`

type GetEnumTranslationParams struct {
	EnumType  string `json:"enum_type"`
	EnumValue string `json:"enum_value"`
	Locale    string `json:"locale"`
}

func (q *Queries) GetEnumTranslation(ctx context.Context, arg GetEnumTranslationParams) (EnumTranslation, error) {
	row := q.db.QueryRowContext(ctx, getEnumTranslation, arg.EnumType, arg.EnumValue, arg.Locale)
	var i EnumTranslation
	err := row.Scan(
		&i.EnumType,
		&i.EnumValue,
		&i.Locale,
		&i.Label,
		&i.ColorClass,
		&i.Icon,
		&i.SortOrder,
	)
	return i, err
}

const getFooterColumnByID = `-- name: GetFooterColumnByID :one
SELECT id, title, links, is_active, order_index FROM footer_columns WHERE id = ?
`

func (q *Queries) GetFooterColumnByID(ctx context.Context, id string) (FooterColumn, error) {
	row := q.db.QueryRowContext(ctx, getFooterColumnByID, id)
	var i FooterColumn
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Links,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const getHotKeywordByID = `-- name: GetHotKeywordByID :one
SELECT id, keyword, scope, is_active, order_index FROM hot_keywords WHERE id = ?
`

func (q *Queries) GetHotKeywordByID(ctx context.Context, id string) (HotKeyword, error) {
	row := q.db.QueryRowContext(ctx, getHotKeywordByID, id)
	var i HotKeyword
	err := row.Scan(
		&i.ID,
		&i.Keyword,
		&i.Scope,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const getI18nMessage = `-- name: GetI18nMessage :one
SELECT ` + "`" + `key` + "`" + `, locale, value, category FROM i18n_messages WHERE ` + "`" + `key` + "`" + ` = ? AND locale = ?
`

type GetI18nMessageParams struct {
	Key    string `json:"key"`
	Locale string `json:"locale"`
}

func (q *Queries) GetI18nMessage(ctx context.Context, arg GetI18nMessageParams) (I18nMessage, error) {
	row := q.db.QueryRowContext(ctx, getI18nMessage, arg.Key, arg.Locale)
	var i I18nMessage
	err := row.Scan(
		&i.Key,
		&i.Locale,
		&i.Value,
		&i.Category,
	)
	return i, err
}

const getIndustryByID = `-- name: GetIndustryByID :one
SELECT id, ` + "`" + `key` + "`" + `, label, description, icon, methodology, is_active, order_index, created_at, updated_at FROM industries WHERE id = ?
`

func (q *Queries) GetIndustryByID(ctx context.Context, id string) (Industry, error) {
	row := q.db.QueryRowContext(ctx, getIndustryByID, id)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.Icon,
		&i.Methodology,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageSetting = `-- name: GetPageSetting :one
SELECT page, ` + "`" + `key` + "`" + `, value, description, updated_at FROM page_settings WHERE page = ? AND ` + "`" + `key` + "`" + ` = ?
`

type GetPageSettingParams struct {
	Page string `json:"page"`
	Key  string `json:"key"`
}

func (q *Queries) GetPageSetting(ctx context.Context, arg GetPageSettingParams) (PageSetting, error) {
	row := q.db.QueryRowContext(ctx, getPageSetting, arg.Page, arg.Key)
	var i PageSetting
	err := row.Scan(
		&i.Page,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getPopularSearchByID = `-- name: GetPopularSearchByID :one
SELECT id, keyword, click_count, is_active, order_index FROM popular_searches WHERE id = ?
`

func (q *Queries) GetPopularSearchByID(ctx context.Context, id string) (PopularSearch, error) {
	row := q.db.QueryRowContext(ctx, getPopularSearchByID, id)
	var i PopularSearch
	err := row.Scan(
		&i.ID,
		&i.Keyword,
		&i.ClickCount,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const getQuickPromptByID = `-- name: GetQuickPromptByID :one
SELECT id, emoji, label, prompt_text, scope, is_active, order_index FROM quick_prompts WHERE id = ?
`

func (q *Queries) GetQuickPromptByID(ctx context.Context, id string) (QuickPrompt, error) {
	row := q.db.QueryRowContext(ctx, getQuickPromptByID, id)
	var i QuickPrompt
	err := row.Scan(
		&i.ID,
		&i.Emoji,
		&i.Label,
		&i.PromptText,
		&i.Scope,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const getSiteSettingByKey = `-- name: GetSiteSettingByKey :one
SELECT ` + "`" + `key` + "`" + `, value, scope, description, updated_at FROM site_settings WHERE ` + "`" + `key` + "`" + ` = ?
`

func (q *Queries) GetSiteSettingByKey(ctx context.Context, key string) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettingByKey, key)
	var i SiteSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Scope,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getTestimonialByID = `-- name: GetTestimonialByID :one
SELECT id, name, title, quote, avatar, is_active, order_index FROM testimonials WHERE id = ?
`

func (q *Queries) GetTestimonialByID(ctx context.Context, id string) (Testimonial, error) {
	row := q.db.QueryRowContext(ctx, getTestimonialByID, id)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Quote,
		&i.Avatar,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const getTopNavItemByID = `-- name: GetTopNavItemByID :one
SELECT id, label, path, icon, is_active, order_index FROM top_nav_items WHERE id = ?
`

func (q *Queries) GetTopNavItemByID(ctx context.Context, id string) (TopNavItem, error) {
	row := q.db.QueryRowContext(ctx, getTopNavItemByID, id)
	var i TopNavItem
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Path,
		&i.Icon,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}

const listAppSettings = `-- name: ListAppSettings :many


SELECT ` + "`" + `key` + "`" + `, value_json, scope, description, updated_at FROM app_settings
WHERE (? IS NULL OR scope = ?)
ORDER BY ` + "`" + `key` + "`" + ` ASC
`

type ListAppSettingsParams struct {
	Scope NullAppSettingsScope `json:"scope"`
}

// ============================================================================
// CMS module queries — Phase 2 T23.
//
// 16 resource tables, ~80 admin endpoints (cms-admin.controller.ts) + 17
// public endpoints (cms-config / cms-content / cms-enum / cms-i18n /
// sitemap). All admin endpoints map 1:1 to {list, get, create, update,
// delete} over a 16-resource set; the public endpoints are read-only.
//
// Conventions:
//   - Composite-PK resources (enum_translations, date_format_templates,
//     page_settings, i18n_messages) use natural-key get/update/delete.
//   - The 12 "content" resources with a String @id (industries, …,
//     footer_columns) use plain :one and :exec queries.
//   - The 4 "config" resources (app_settings, site_settings, …) use
//     `key` as the natural primary key.
//
// ============================================================================
// =========================== app_settings ===========================
// Public + admin: optionally filtered by scope.
func (q *Queries) ListAppSettings(ctx context.Context, arg ListAppSettingsParams) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAppSettings, arg.Scope, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.ValueJson,
			&i.Scope,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthProviders = `-- name: ListAuthProviders :many

SELECT id, label, icon, is_active, order_index, config FROM auth_providers ORDER BY order_index ASC, id ASC
`

// =========================== auth_providers ===========================
// Admin list (full rows, including `config` JSON).
func (q *Queries) ListAuthProviders(ctx context.Context) ([]AuthProvider, error) {
	rows, err := q.db.QueryContext(ctx, listAuthProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthProvider{}
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Icon,
			&i.IsActive,
			&i.OrderIndex,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthProvidersPublic = `-- name: ListAuthProvidersPublic :many
SELECT id, label, icon, is_active, order_index
FROM auth_providers
WHERE is_active = TRUE
ORDER BY order_index ASC, id ASC
`

type ListAuthProvidersPublicRow struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	Icon       string `json:"icon"`
	IsActive   bool   `json:"is_active"`
	OrderIndex int32  `json:"order_index"`
}

// Public list — strips `config` to avoid leaking OAuth client_secret.
func (q *Queries) ListAuthProvidersPublic(ctx context.Context) ([]ListAuthProvidersPublicRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthProvidersPublic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthProvidersPublicRow{}
	for rows.Next() {
		var i ListAuthProvidersPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Icon,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseCategories = `-- name: ListCourseCategories :many

SELECT id, ` + "`" + `key` + "`" + `, label, is_active, order_index FROM course_categories
WHERE (? IS NULL OR is_active = ?)
ORDER BY order_index ASC, id ASC
`

type ListCourseCategoriesParams struct {
	IsActive sql.NullBool `json:"is_active"`
}

// =========================== course_categories ===========================
func (q *Queries) ListCourseCategories(ctx context.Context, arg ListCourseCategoriesParams) ([]CourseCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCourseCategories, arg.IsActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseCategory{}
	for rows.Next() {
		var i CourseCategory
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDateFormatTemplates = `-- name: ListDateFormatTemplates :many

SELECT scope, locale, template FROM date_format_templates
WHERE (? IS NULL OR scope = ?)
  AND (? IS NULL OR locale = ?)
ORDER BY scope ASC, locale ASC
`

type ListDateFormatTemplatesParams struct {
	Scope  NullDateFormatTemplatesScope `json:"scope"`
	Locale sql.NullString               `json:"locale"`
}

// =========================== date_format_templates ===========================
// Composite PK: (scope, locale).
// URL :id form is "scope:locale".
func (q *Queries) ListDateFormatTemplates(ctx context.Context, arg ListDateFormatTemplatesParams) ([]DateFormatTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listDateFormatTemplates,
		arg.Scope,
		arg.Scope,
		arg.Locale,
		arg.Locale,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DateFormatTemplate{}
	for rows.Next() {
		var i DateFormatTemplate
		if err := rows.Scan(&i.Scope, &i.Locale, &i.Template); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnterpriseMethods = `-- name: ListEnterpriseMethods :many

SELECT id, num, title, ` + "`" + `desc` + "`" + `, bullets, is_active, order_index FROM enterprise_methods
WHERE (? IS NULL OR is_active = ?)
ORDER BY order_index ASC, id ASC
`

type ListEnterpriseMethodsParams struct {
	IsActive sql.NullBool `json:"is_active"`
}

// =========================== enterprise_methods ===========================
func (q *Queries) ListEnterpriseMethods(ctx context.Context, arg ListEnterpriseMethodsParams) ([]EnterpriseMethod, error) {
	rows, err := q.db.QueryContext(ctx, listEnterpriseMethods, arg.IsActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnterpriseMethod{}
	for rows.Next() {
		var i EnterpriseMethod
		if err := rows.Scan(
			&i.ID,
			&i.Num,
			&i.Title,
			&i.Desc,
			&i.Bullets,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnumTranslations = `-- name: ListEnumTranslations :many

SELECT enum_type, enum_value, locale, label, color_class, icon, sort_order FROM enum_translations
WHERE (? IS NULL OR enum_type = ?)
  AND (? IS NULL OR locale = ?)
ORDER BY enum_type ASC, sort_order ASC, enum_value ASC
`

type ListEnumTranslationsParams struct {
	EnumType sql.NullString `json:"enum_type"`
	Locale   sql.NullString `json:"locale"`
}

// =========================== enum_translations ===========================
// Composite PK: (enum_type, enum_value, locale).
// URL :id form is "enumType:enumValue:locale".
func (q *Queries) ListEnumTranslations(ctx context.Context, arg ListEnumTranslationsParams) ([]EnumTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listEnumTranslations,
		arg.EnumType,
		arg.EnumType,
		arg.Locale,
		arg.Locale,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnumTranslation{}
	for rows.Next() {
		var i EnumTranslation
		if err := rows.Scan(
			&i.EnumType,
			&i.EnumValue,
			&i.Locale,
			&i.Label,
			&i.ColorClass,
			&i.Icon,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFooterColumns = `-- name: ListFooterColumns :many

SELECT id, title, links, is_active, order_index FROM footer_columns
WHERE (? IS NULL OR is_active = ?)
ORDER BY order_index ASC, id ASC
`

type ListFooterColumnsParams struct {
	IsActive sql.NullBool `json:"is_active"`
}

// =========================== footer_columns ===========================
func (q *Queries) ListFooterColumns(ctx context.Context, arg ListFooterColumnsParams) ([]FooterColumn, error) {
	rows, err := q.db.QueryContext(ctx, listFooterColumns, arg.IsActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FooterColumn{}
	for rows.Next() {
		var i FooterColumn
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Links,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotKeywords = `-- name: ListHotKeywords :many

SELECT id, keyword, scope, is_active, order_index FROM hot_keywords
WHERE (? IS NULL OR is_active = ?)
  AND (? IS NULL OR scope = ?)
ORDER BY order_index ASC, id ASC
`

type ListHotKeywordsParams struct {
	IsActive sql.NullBool         `json:"is_active"`
	Scope    NullHotKeywordsScope `json:"scope"`
}

// =========================== hot_keywords ===========================
func (q *Queries) ListHotKeywords(ctx context.Context, arg ListHotKeywordsParams) ([]HotKeyword, error) {
	rows, err := q.db.QueryContext(ctx, listHotKeywords,
		arg.IsActive,
		arg.IsActive,
		arg.Scope,
		arg.Scope,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotKeyword{}
	for rows.Next() {
		var i HotKeyword
		if err := rows.Scan(
			&i.ID,
			&i.Keyword,
			&i.Scope,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listI18nMessages = `-- name: ListI18nMessages :many

SELECT ` + "`" + `key` + "`" + `, locale, value, category FROM i18n_messages
WHERE (? IS NULL OR locale = ?)
  AND (? IS NULL OR category = ?)
ORDER BY category ASC, ` + "`" + `key` + "`" + ` ASC
`

type ListI18nMessagesParams struct {
	Locale   sql.NullString           `json:"locale"`
	Category NullI18nMessagesCategory `json:"category"`
}

// =========================== i18n_messages ===========================
// Composite PK: (key, locale).
// URL :id form is "key:locale".
func (q *Queries) ListI18nMessages(ctx context.Context, arg ListI18nMessagesParams) ([]I18nMessage, error) {
	rows, err := q.db.QueryContext(ctx, listI18nMessages,
		arg.Locale,
		arg.Locale,
		arg.Category,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []I18nMessage{}
	for rows.Next() {
		var i I18nMessage
		if err := rows.Scan(
			&i.Key,
			&i.Locale,
			&i.Value,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndustries = `-- name: ListIndustries :many

SELECT id, ` + "`" + `key` + "`" + `, label, description, icon, methodology, is_active, order_index, created_at, updated_at FROM industries
WHERE (? IS NULL OR is_active = ?)
ORDER BY order_index ASC, id ASC
`

type ListIndustriesParams struct {
	IsActive sql.NullBool `json:"is_active"`
}

// =========================== industries ===========================
func (q *Queries) ListIndustries(ctx context.Context, arg ListIndustriesParams) ([]Industry, error) {
	rows, err := q.db.QueryContext(ctx, listIndustries, arg.IsActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Industry{}
	for rows.Next() {
		var i Industry
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Description,
			&i.Icon,
			&i.Methodology,
			&i.IsActive,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageSettings = `-- name: ListPageSettings :many

SELECT page, ` + "`" + `key` + "`" + `, value, description, updated_at FROM page_settings
WHERE (? IS NULL OR page = ?)
ORDER BY page ASC, ` + "`" + `key` + "`" + ` ASC
`

type ListPageSettingsParams struct {
	Page sql.NullString `json:"page"`
}

// =========================== page_settings ===========================
func (q *Queries) ListPageSettings(ctx context.Context, arg ListPageSettingsParams) ([]PageSetting, error) {
	rows, err := q.db.QueryContext(ctx, listPageSettings, arg.Page, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageSetting{}
	for rows.Next() {
		var i PageSetting
		if err := rows.Scan(
			&i.Page,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageSettingsByPages = `-- name: ListPageSettingsByPages :many
SELECT page, ` + "`" + `key` + "`" + `, value, description, updated_at
FROM page_settings
WHERE page IN (/*SLICE:pages*/?)
`

// Public GET /page-settings?page=home&page=courses — batch fetch.
func (q *Queries) ListPageSettingsByPages(ctx context.Context, pages []string) ([]PageSetting, error) {
	query := listPageSettingsByPages
	var queryParams []interface{}
	if len(pages) > 0 {
		for _, v := range pages {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:pages*/?", strings.Repeat(",?", len(pages))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:pages*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageSetting{}
	for rows.Next() {
		var i PageSetting
		if err := rows.Scan(
			&i.Page,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularSearches = `-- name: ListPopularSearches :many

SELECT id, keyword, click_count, is_active, order_index FROM popular_searches
WHERE (? IS NULL OR is_active = ?)
ORDER BY order_index ASC, id ASC
`

type ListPopularSearchesParams struct {
	IsActive sql.NullBool `json:"is_active"`
}

// =========================== popular_searches ===========================
func (q *Queries) ListPopularSearches(ctx context.Context, arg ListPopularSearchesParams) ([]PopularSearch, error) {
	rows, err := q.db.QueryContext(ctx, listPopularSearches, arg.IsActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PopularSearch{}
	for rows.Next() {
		var i PopularSearch
		if err := rows.Scan(
			&i.ID,
			&i.Keyword,
			&i.ClickCount,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicHackathonsForSitemap = `-- name: ListPublicHackathonsForSitemap :many
SELECT id, updated_at FROM hackathons
WHERE status IN ('upcoming', 'active', 'finished')
ORDER BY updated_at DESC
LIMIT 200
`

type ListPublicHackathonsForSitemapRow struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListPublicHackathonsForSitemap(ctx context.Context) ([]ListPublicHackathonsForSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicHackathonsForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicHackathonsForSitemapRow{}
	for rows.Next() {
		var i ListPublicHackathonsForSitemapRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCoursesForSitemap = `-- name: ListPublishedCoursesForSitemap :many

SELECT id, updated_at FROM courses
WHERE status = 'published'
ORDER BY updated_at DESC
LIMIT 1000
`

type ListPublishedCoursesForSitemapRow struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// =========================== sitemap ===========================
// Sitemap is a public read-only endpoint over published courses /
// degrees / hackathons. Lives in the same module so all "public CMS"
// queries stay together.
func (q *Queries) ListPublishedCoursesForSitemap(ctx context.Context) ([]ListPublishedCoursesForSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedCoursesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedCoursesForSitemapRow{}
	for rows.Next() {
		var i ListPublishedCoursesForSitemapRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedDegreesForSitemap = `-- name: ListPublishedDegreesForSitemap :many
SELECT id, updated_at FROM nano_degrees
WHERE status = 'published'
ORDER BY updated_at DESC
LIMIT 500
`

type ListPublishedDegreesForSitemapRow struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListPublishedDegreesForSitemap(ctx context.Context) ([]ListPublishedDegreesForSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedDegreesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedDegreesForSitemapRow{}
	for rows.Next() {
		var i ListPublishedDegreesForSitemapRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickPrompts = `-- name: ListQuickPrompts :many

SELECT id, emoji, label, prompt_text, scope, is_active, order_index FROM quick_prompts
WHERE (? IS NULL OR is_active = ?)
  AND (? IS NULL OR scope = ?)
ORDER BY order_index ASC, id ASC
`

type ListQuickPromptsParams struct {
	IsActive sql.NullBool          `json:"is_active"`
	Scope    NullQuickPromptsScope `json:"scope"`
}

// =========================== quick_prompts ===========================
func (q *Queries) ListQuickPrompts(ctx context.Context, arg ListQuickPromptsParams) ([]QuickPrompt, error) {
	rows, err := q.db.QueryContext(ctx, listQuickPrompts,
		arg.IsActive,
		arg.IsActive,
		arg.Scope,
		arg.Scope,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuickPrompt{}
	for rows.Next() {
		var i QuickPrompt
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.Label,
			&i.PromptText,
			&i.Scope,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteSettings = `-- name: ListSiteSettings :many

SELECT ` + "`" + `key` + "`" + `, value, scope, description, updated_at FROM site_settings
WHERE (? IS NULL OR scope = ?)
ORDER BY ` + "`" + `key` + "`" + ` ASC
`

type ListSiteSettingsParams struct {
	Scope NullSiteSettingsScope `json:"scope"`
}

// =========================== site_settings ===========================
func (q *Queries) ListSiteSettings(ctx context.Context, arg ListSiteSettingsParams) ([]SiteSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSiteSettings, arg.Scope, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Scope,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteSettingsByKeys = `-- name: ListSiteSettingsByKeys :many
SELECT ` + "`" + `key` + "`" + `, value, scope, description, updated_at
FROM site_settings
WHERE ` + "`" + `key` + "`" + ` IN (/*SLICE:keys*/?)
`

// Public GET /site-settings?keys=a,b,c — batch fetch by key set.
func (q *Queries) ListSiteSettingsByKeys(ctx context.Context, keys []string) ([]SiteSetting, error) {
	query := listSiteSettingsByKeys
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Scope,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestimonials = `-- name: ListTestimonials :many

SELECT id, name, title, quote, avatar, is_active, order_index FROM testimonials
WHERE (? IS NULL OR is_active = ?)
ORDER BY order_index ASC, id ASC
`

type ListTestimonialsParams struct {
	IsActive sql.NullBool `json:"is_active"`
}

// =========================== testimonials ===========================
func (q *Queries) ListTestimonials(ctx context.Context, arg ListTestimonialsParams) ([]Testimonial, error) {
	rows, err := q.db.QueryContext(ctx, listTestimonials, arg.IsActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testimonial{}
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Quote,
			&i.Avatar,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopNavItems = `-- name: ListTopNavItems :many

SELECT id, label, path, icon, is_active, order_index FROM top_nav_items
WHERE (? IS NULL OR is_active = ?)
ORDER BY order_index ASC, id ASC
`

type ListTopNavItemsParams struct {
	IsActive sql.NullBool `json:"is_active"`
}

// =========================== top_nav_items ===========================
func (q *Queries) ListTopNavItems(ctx context.Context, arg ListTopNavItemsParams) ([]TopNavItem, error) {
	rows, err := q.db.QueryContext(ctx, listTopNavItems, arg.IsActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopNavItem{}
	for rows.Next() {
		var i TopNavItem
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Path,
			&i.Icon,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppSetting = `-- name: UpdateAppSetting :exec
UPDATE app_settings
SET value_json = ?, scope = ?, description = ?, updated_at = ?
WHERE ` + "`" + `key` + "`" + ` = ?
`

type UpdateAppSettingParams struct {
	ValueJson   json.RawMessage  `json:"value_json"`
	Scope       AppSettingsScope `json:"scope"`
	Description sql.NullString   `json:"description"`
	UpdatedAt   time.Time        `json:"updated_at"`
	Key         string           `json:"key"`
}

// Full update by key. value_json / scope / description are coalesced so
// the handler can read-then-merge before calling.
func (q *Queries) UpdateAppSetting(ctx context.Context, arg UpdateAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateAppSetting,
		arg.ValueJson,
		arg.Scope,
		arg.Description,
		arg.UpdatedAt,
		arg.Key,
	)
	return err
}

const updateAuthProvider = `-- name: UpdateAuthProvider :exec
UPDATE auth_providers
SET label = ?, icon = ?, is_active = ?, order_index = ?, config = ?
WHERE id = ?
`

type UpdateAuthProviderParams struct {
	Label      string          `json:"label"`
	Icon       string          `json:"icon"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
	Config     json.RawMessage `json:"config"`
	ID         string          `json:"id"`
}

func (q *Queries) UpdateAuthProvider(ctx context.Context, arg UpdateAuthProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthProvider,
		arg.Label,
		arg.Icon,
		arg.IsActive,
		arg.OrderIndex,
		arg.Config,
		arg.ID,
	)
	return err
}

const updateCourseCategory = `-- name: UpdateCourseCategory :exec
UPDATE course_categories
SET ` + "`" + `key` + "`" + ` = ?, label = ?, is_active = ?, order_index = ?
WHERE id = ?
`

type UpdateCourseCategoryParams struct {
	Key        string `json:"key"`
	Label      string `json:"label"`
	IsActive   bool   `json:"is_active"`
	OrderIndex int32  `json:"order_index"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateCourseCategory(ctx context.Context, arg UpdateCourseCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCourseCategory,
		arg.Key,
		arg.Label,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}

const updateDateFormatTemplate = `-- name: UpdateDateFormatTemplate :exec
UPDATE date_format_templates
SET template = ?
WHERE scope = ? AND locale = ?
`

type UpdateDateFormatTemplateParams struct {
	Template string                   `json:"template"`
	Scope    DateFormatTemplatesScope `json:"scope"`
	Locale   string                   `json:"locale"`
}

func (q *Queries) UpdateDateFormatTemplate(ctx context.Context, arg UpdateDateFormatTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateDateFormatTemplate, arg.Template, arg.Scope, arg.Locale)
	return err
}

const updateEnterpriseMethod = `-- name: UpdateEnterpriseMethod :exec
UPDATE enterprise_methods
SET num = ?, title = ?, ` + "`" + `desc` + "`" + ` = ?, bullets = ?,
    is_active = ?, order_index = ?
WHERE id = ?
`

type UpdateEnterpriseMethodParams struct {
	Num        string          `json:"num"`
	Title      string          `json:"title"`
	Desc       string          `json:"desc"`
	Bullets    json.RawMessage `json:"bullets"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
	ID         string          `json:"id"`
}

func (q *Queries) UpdateEnterpriseMethod(ctx context.Context, arg UpdateEnterpriseMethodParams) error {
	_, err := q.db.ExecContext(ctx, updateEnterpriseMethod,
		arg.Num,
		arg.Title,
		arg.Desc,
		arg.Bullets,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}

const updateEnumTranslation = `-- name: UpdateEnumTranslation :exec
UPDATE enum_translations
SET label = ?, color_class = ?, icon = ?, sort_order = ?
WHERE enum_type = ? AND enum_value = ? AND locale = ?
`

type UpdateEnumTranslationParams struct {
	Label      string         `json:"label"`
	ColorClass sql.NullString `json:"color_class"`
	Icon       sql.NullString `json:"icon"`
	SortOrder  int32          `json:"sort_order"`
	EnumType   string         `json:"enum_type"`
	EnumValue  string         `json:"enum_value"`
	Locale     string         `json:"locale"`
}

func (q *Queries) UpdateEnumTranslation(ctx context.Context, arg UpdateEnumTranslationParams) error {
	_, err := q.db.ExecContext(ctx, updateEnumTranslation,
		arg.Label,
		arg.ColorClass,
		arg.Icon,
		arg.SortOrder,
		arg.EnumType,
		arg.EnumValue,
		arg.Locale,
	)
	return err
}

const updateFooterColumn = `-- name: UpdateFooterColumn :exec
UPDATE footer_columns
SET title = ?, links = ?, is_active = ?, order_index = ?
WHERE id = ?
`

type UpdateFooterColumnParams struct {
	Title      string          `json:"title"`
	Links      json.RawMessage `json:"links"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
	ID         string          `json:"id"`
}

func (q *Queries) UpdateFooterColumn(ctx context.Context, arg UpdateFooterColumnParams) error {
	_, err := q.db.ExecContext(ctx, updateFooterColumn,
		arg.Title,
		arg.Links,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}

const updateHotKeyword = `-- name: UpdateHotKeyword :exec
UPDATE hot_keywords
SET keyword = ?, scope = ?, is_active = ?, order_index = ?
WHERE id = ?
`

type UpdateHotKeywordParams struct {
	Keyword    string           `json:"keyword"`
	Scope      HotKeywordsScope `json:"scope"`
	IsActive   bool             `json:"is_active"`
	OrderIndex int32            `json:"order_index"`
	ID         string           `json:"id"`
}

func (q *Queries) UpdateHotKeyword(ctx context.Context, arg UpdateHotKeywordParams) error {
	_, err := q.db.ExecContext(ctx, updateHotKeyword,
		arg.Keyword,
		arg.Scope,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}

const updateI18nMessage = `-- name: UpdateI18nMessage :exec
UPDATE i18n_messages
SET value = ?, category = ?
WHERE ` + "`" + `key` + "`" + ` = ? AND locale = ?
`

type UpdateI18nMessageParams struct {
	Value    string               `json:"value"`
	Category I18nMessagesCategory `json:"category"`
	Key      string               `json:"key"`
	Locale   string               `json:"locale"`
}

func (q *Queries) UpdateI18nMessage(ctx context.Context, arg UpdateI18nMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateI18nMessage,
		arg.Value,
		arg.Category,
		arg.Key,
		arg.Locale,
	)
	return err
}

const updateIndustry = `-- name: UpdateIndustry :exec
UPDATE industries
SET ` + "`" + `key` + "`" + ` = ?, label = ?, description = ?, icon = ?, methodology = ?,
    is_active = ?, order_index = ?, updated_at = ?
WHERE id = ?
`

type UpdateIndustryParams struct {
	Key         string          `json:"key"`
	Label       string          `json:"label"`
	Description sql.NullString  `json:"description"`
	Icon        sql.NullString  `json:"icon"`
	Methodology json.RawMessage `json:"methodology"`
	IsActive    bool            `json:"is_active"`
	OrderIndex  int32           `json:"order_index"`
	UpdatedAt   time.Time       `json:"updated_at"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdateIndustry(ctx context.Context, arg UpdateIndustryParams) error {
	_, err := q.db.ExecContext(ctx, updateIndustry,
		arg.Key,
		arg.Label,
		arg.Description,
		arg.Icon,
		arg.Methodology,
		arg.IsActive,
		arg.OrderIndex,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updatePageSetting = `-- name: UpdatePageSetting :exec
UPDATE page_settings
SET value = ?, description = ?, updated_at = ?
WHERE page = ? AND ` + "`" + `key` + "`" + ` = ?
`

type UpdatePageSettingParams struct {
	Value       json.RawMessage `json:"value"`
	Description sql.NullString  `json:"description"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Page        string          `json:"page"`
	Key         string          `json:"key"`
}

func (q *Queries) UpdatePageSetting(ctx context.Context, arg UpdatePageSettingParams) error {
	_, err := q.db.ExecContext(ctx, updatePageSetting,
		arg.Value,
		arg.Description,
		arg.UpdatedAt,
		arg.Page,
		arg.Key,
	)
	return err
}

const updatePopularSearch = `-- name: UpdatePopularSearch :exec
UPDATE popular_searches
SET keyword = ?, click_count = ?, is_active = ?, order_index = ?
WHERE id = ?
`

type UpdatePopularSearchParams struct {
	Keyword    string `json:"keyword"`
	ClickCount int32  `json:"click_count"`
	IsActive   bool   `json:"is_active"`
	OrderIndex int32  `json:"order_index"`
	ID         string `json:"id"`
}

func (q *Queries) UpdatePopularSearch(ctx context.Context, arg UpdatePopularSearchParams) error {
	_, err := q.db.ExecContext(ctx, updatePopularSearch,
		arg.Keyword,
		arg.ClickCount,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}

const updateQuickPrompt = `-- name: UpdateQuickPrompt :exec
UPDATE quick_prompts
SET emoji = ?, label = ?, prompt_text = ?, scope = ?,
    is_active = ?, order_index = ?
WHERE id = ?
`

type UpdateQuickPromptParams struct {
	Emoji      string            `json:"emoji"`
	Label      string            `json:"label"`
	PromptText string            `json:"prompt_text"`
	Scope      QuickPromptsScope `json:"scope"`
	IsActive   bool              `json:"is_active"`
	OrderIndex int32             `json:"order_index"`
	ID         string            `json:"id"`
}

func (q *Queries) UpdateQuickPrompt(ctx context.Context, arg UpdateQuickPromptParams) error {
	_, err := q.db.ExecContext(ctx, updateQuickPrompt,
		arg.Emoji,
		arg.Label,
		arg.PromptText,
		arg.Scope,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}

const updateSiteSetting = `-- name: UpdateSiteSetting :exec
UPDATE site_settings
SET value = ?, scope = ?, description = ?, updated_at = ?
WHERE ` + "`" + `key` + "`" + ` = ?
`

type UpdateSiteSettingParams struct {
	Value       json.RawMessage   `json:"value"`
	Scope       SiteSettingsScope `json:"scope"`
	Description sql.NullString    `json:"description"`
	UpdatedAt   time.Time         `json:"updated_at"`
	Key         string            `json:"key"`
}

func (q *Queries) UpdateSiteSetting(ctx context.Context, arg UpdateSiteSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteSetting,
		arg.Value,
		arg.Scope,
		arg.Description,
		arg.UpdatedAt,
		arg.Key,
	)
	return err
}

const updateTestimonial = `-- name: UpdateTestimonial :exec
UPDATE testimonials
SET name = ?, title = ?, quote = ?, avatar = ?,
    is_active = ?, order_index = ?
WHERE id = ?
`

type UpdateTestimonialParams struct {
	Name       string         `json:"name"`
	Title      string         `json:"title"`
	Quote      string         `json:"quote"`
	Avatar     sql.NullString `json:"avatar"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) error {
	_, err := q.db.ExecContext(ctx, updateTestimonial,
		arg.Name,
		arg.Title,
		arg.Quote,
		arg.Avatar,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}

const updateTopNavItem = `-- name: UpdateTopNavItem :exec
UPDATE top_nav_items
SET label = ?, path = ?, icon = ?, is_active = ?, order_index = ?
WHERE id = ?
`

type UpdateTopNavItemParams struct {
	Label      string         `json:"label"`
	Path       string         `json:"path"`
	Icon       sql.NullString `json:"icon"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTopNavItem(ctx context.Context, arg UpdateTopNavItemParams) error {
	_, err := q.db.ExecContext(ctx, updateTopNavItem,
		arg.Label,
		arg.Path,
		arg.Icon,
		arg.IsActive,
		arg.OrderIndex,
		arg.ID,
	)
	return err
}
