// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*) AS count FROM courses
WHERE (? = '' OR status = ?)
`

type CountCoursesParams struct {
	Column1 interface{}   `json:"column_1"`
	Status  CoursesStatus `json:"status"`
}

// Total courses matching the optional status filter.
func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCourses, arg.Column1, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :execresult
INSERT INTO courses (
  id, title, description, learning_points, instructor, level, duration,
  thumbnail, tags, cost_type, price, status, course_type, external_url,
  source_video_url, source_platform, created_at, updated_at,
  industry_id, category_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?
)
`

type CreateCourseParams struct {
	ID             string            `json:"id"`
	Title          string            `json:"title"`
	Description    string            `json:"description"`
	LearningPoints string            `json:"learning_points"`
	Instructor     string            `json:"instructor"`
	Level          CoursesLevel      `json:"level"`
	Duration       string            `json:"duration"`
	Thumbnail      string            `json:"thumbnail"`
	Tags           string            `json:"tags"`
	CostType       CoursesCostType   `json:"cost_type"`
	Price          string            `json:"price"`
	Status         CoursesStatus     `json:"status"`
	CourseType     CoursesCourseType `json:"course_type"`
	ExternalUrl    sql.NullString    `json:"external_url"`
	SourceVideoUrl sql.NullString    `json:"source_video_url"`
	SourcePlatform sql.NullString    `json:"source_platform"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	IndustryID     sql.NullString    `json:"industry_id"`
	CategoryID     sql.NullString    `json:"category_id"`
}

// Inserts a new course. Caller generates id (uuid or cuid).
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.LearningPoints,
		arg.Instructor,
		arg.Level,
		arg.Duration,
		arg.Thumbnail,
		arg.Tags,
		arg.CostType,
		arg.Price,
		arg.Status,
		arg.CourseType,
		arg.ExternalUrl,
		arg.SourceVideoUrl,
		arg.SourcePlatform,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IndustryID,
		arg.CategoryID,
	)
}

const createDegreeCourse = `-- name: CreateDegreeCourse :execresult
INSERT INTO degree_courses (degree_id, course_id, order_index) VALUES (?, ?, ?)
`

type CreateDegreeCourseParams struct {
	DegreeID   string `json:"degree_id"`
	CourseID   string `json:"course_id"`
	OrderIndex int32  `json:"order_index"`
}

// Append a (degree, course) link at the supplied order_index.
func (q *Queries) CreateDegreeCourse(ctx context.Context, arg CreateDegreeCourseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDegreeCourse, arg.DegreeID, arg.CourseID, arg.OrderIndex)
}

const degreeCourseExists = `-- name: DegreeCourseExists :one
SELECT EXISTS(
  SELECT 1 FROM degree_courses WHERE degree_id = ? AND course_id = ?
)
`

type DegreeCourseExistsParams struct {
	DegreeID string `json:"degree_id"`
	CourseID string `json:"course_id"`
}

// Idempotency guard for linkDegrees: skip if (degree, course) pair already
// exists (the @@unique constraint catches inserts, but we want a clean
// "skipped" count in the response).
func (q *Queries) DegreeCourseExists(ctx context.Context, arg DegreeCourseExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, degreeCourseExists, arg.DegreeID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = ?
`

// Hard delete. Cascades to chapters / lessons / resources / enrollments
// per the FK constraints. Admin only; service layer verifies role.
func (q *Queries) DeleteCourse(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, title, description, learning_points, instructor, level, duration,
       thumbnail, tags, cost_type, price, status, course_type, external_url,
       source_video_url, source_platform, created_at, updated_at,
       industry_id, category_id
FROM courses
WHERE id = ? AND status = 'published'
`

// Retrieves a course by id. Filters out drafts from non-admin callers — for
// the API boundary, the admin/owner path will use a separate unscoped query.
func (q *Queries) GetCourseByID(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LearningPoints,
		&i.Instructor,
		&i.Level,
		&i.Duration,
		&i.Thumbnail,
		&i.Tags,
		&i.CostType,
		&i.Price,
		&i.Status,
		&i.CourseType,
		&i.ExternalUrl,
		&i.SourceVideoUrl,
		&i.SourcePlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndustryID,
		&i.CategoryID,
	)
	return i, err
}

const getCourseByIDAnyStatus = `-- name: GetCourseByIDAnyStatus :one
SELECT id, title, description, learning_points, instructor, level, duration,
       thumbnail, tags, cost_type, price, status, course_type, external_url,
       source_video_url, source_platform, created_at, updated_at,
       industry_id, category_id
FROM courses
WHERE id = ?
`

// Admin / internal: returns the course regardless of status.
func (q *Queries) GetCourseByIDAnyStatus(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByIDAnyStatus, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LearningPoints,
		&i.Instructor,
		&i.Level,
		&i.Duration,
		&i.Thumbnail,
		&i.Tags,
		&i.CostType,
		&i.Price,
		&i.Status,
		&i.CourseType,
		&i.ExternalUrl,
		&i.SourceVideoUrl,
		&i.SourcePlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndustryID,
		&i.CategoryID,
	)
	return i, err
}

const listAllCourses = `-- name: ListAllCourses :many
SELECT id, title, description, learning_points, instructor, level, duration,
       thumbnail, tags, cost_type, price, status, course_type, external_url,
       source_video_url, source_platform, created_at, updated_at,
       industry_id, category_id
FROM courses
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAllCoursesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin catalog: all statuses, newest first. Paged.
func (q *Queries) ListAllCourses(ctx context.Context, arg ListAllCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listAllCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.LearningPoints,
			&i.Instructor,
			&i.Level,
			&i.Duration,
			&i.Thumbnail,
			&i.Tags,
			&i.CostType,
			&i.Price,
			&i.Status,
			&i.CourseType,
			&i.ExternalUrl,
			&i.SourceVideoUrl,
			&i.SourcePlatform,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndustryID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByStatus = `-- name: ListCoursesByStatus :many
SELECT id, title, description, learning_points, instructor, level, duration,
       thumbnail, tags, cost_type, price, status, course_type, external_url,
       source_video_url, source_platform, created_at, updated_at,
       industry_id, category_id
FROM courses
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCoursesByStatusParams struct {
	Status CoursesStatus `json:"status"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

// Course catalog listing, filter by status, newest first. Paged.
func (q *Queries) ListCoursesByStatus(ctx context.Context, arg ListCoursesByStatusParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCoursesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.LearningPoints,
			&i.Instructor,
			&i.Level,
			&i.Duration,
			&i.Thumbnail,
			&i.Tags,
			&i.CostType,
			&i.Price,
			&i.Status,
			&i.CourseType,
			&i.ExternalUrl,
			&i.SourceVideoUrl,
			&i.SourcePlatform,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndustryID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxOrderIndexInDegree = `-- name: MaxOrderIndexInDegree :one
SELECT COALESCE(MAX(order_index), -1) AS max_idx
FROM degree_courses WHERE degree_id = ?
`

// For linkDegrees: figure out the next order index in a given degree.
func (q *Queries) MaxOrderIndexInDegree(ctx context.Context, degreeID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxOrderIndexInDegree, degreeID)
	var max_idx interface{}
	err := row.Scan(&max_idx)
	return max_idx, err
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses
SET title = ?, description = ?, learning_points = ?, instructor = ?,
    level = ?, duration = ?, thumbnail = ?, tags = ?, cost_type = ?,
    price = ?, course_type = ?, external_url = ?, source_video_url = ?,
    source_platform = ?, industry_id = ?, category_id = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateCourseParams struct {
	Title          string            `json:"title"`
	Description    string            `json:"description"`
	LearningPoints string            `json:"learning_points"`
	Instructor     string            `json:"instructor"`
	Level          CoursesLevel      `json:"level"`
	Duration       string            `json:"duration"`
	Thumbnail      string            `json:"thumbnail"`
	Tags           string            `json:"tags"`
	CostType       CoursesCostType   `json:"cost_type"`
	Price          string            `json:"price"`
	CourseType     CoursesCourseType `json:"course_type"`
	ExternalUrl    sql.NullString    `json:"external_url"`
	SourceVideoUrl sql.NullString    `json:"source_video_url"`
	SourcePlatform sql.NullString    `json:"source_platform"`
	IndustryID     sql.NullString    `json:"industry_id"`
	CategoryID     sql.NullString    `json:"category_id"`
	UpdatedAt      time.Time         `json:"updated_at"`
	ID             string            `json:"id"`
}

// Partial update for the admin PATCH endpoint. Only the fields the
// caller explicitly supplies are written; the rest keep their existing
// values. Caller is responsible for shaping the patch (UpdateCoursePatch
// in courses.sql.go).
func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.ExecContext(ctx, updateCourse,
		arg.Title,
		arg.Description,
		arg.LearningPoints,
		arg.Instructor,
		arg.Level,
		arg.Duration,
		arg.Thumbnail,
		arg.Tags,
		arg.CostType,
		arg.Price,
		arg.CourseType,
		arg.ExternalUrl,
		arg.SourceVideoUrl,
		arg.SourcePlatform,
		arg.IndustryID,
		arg.CategoryID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateCourseStatus = `-- name: UpdateCourseStatus :exec
UPDATE courses
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateCourseStatusParams struct {
	Status    CoursesStatus `json:"status"`
	UpdatedAt time.Time     `json:"updated_at"`
	ID        string        `json:"id"`
}

// Admin: publishes / archives / drafts a course.
func (q *Queries) UpdateCourseStatus(ctx context.Context, arg UpdateCourseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCourseStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
