// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: degrees.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countActiveEnrollmentsByDegree = `-- name: CountActiveEnrollmentsByDegree :one
SELECT COUNT(*) FROM enrollments WHERE degree_id = ? AND deleted_at IS NULL
`

// Used by delete to ensure no one is actively enrolled.
func (q *Queries) CountActiveEnrollmentsByDegree(ctx context.Context, degreeID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveEnrollmentsByDegree, degreeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDegreeCourses = `-- name: CountDegreeCourses :one
SELECT COUNT(*) FROM degree_courses WHERE degree_id = ?
`

func (q *Queries) CountDegreeCourses(ctx context.Context, degreeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDegreeCourses, degreeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDegree = `-- name: CreateDegree :execresult
INSERT INTO nano_degrees
  (id, title, description, learning_points, price, icon, cost_type, thumbnail, status, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDegreeParams struct {
	ID             string              `json:"id"`
	Title          string              `json:"title"`
	Description    string              `json:"description"`
	LearningPoints string              `json:"learning_points"`
	Price          string              `json:"price"`
	Icon           string              `json:"icon"`
	CostType       NanoDegreesCostType `json:"cost_type"`
	Thumbnail      sql.NullString      `json:"thumbnail"`
	Status         NanoDegreesStatus   `json:"status"`
	UpdatedAt      time.Time           `json:"updated_at"`
}

func (q *Queries) CreateDegree(ctx context.Context, arg CreateDegreeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDegree,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.LearningPoints,
		arg.Price,
		arg.Icon,
		arg.CostType,
		arg.Thumbnail,
		arg.Status,
		arg.UpdatedAt,
	)
}

const deleteDegree = `-- name: DeleteDegree :exec
DELETE FROM nano_degrees WHERE id = ?
`

func (q *Queries) DeleteDegree(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDegree, id)
	return err
}

const getDegreeByID = `-- name: GetDegreeByID :one
SELECT id, title, description, learning_points, price, icon, cost_type, thumbnail, status, created_at, updated_at FROM nano_degrees WHERE id = ?
`

// Used by findOne and update. No soft-delete on degrees (use
// status='archived' instead per the schema).
func (q *Queries) GetDegreeByID(ctx context.Context, id string) (NanoDegree, error) {
	row := q.db.QueryRowContext(ctx, getDegreeByID, id)
	var i NanoDegree
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.LearningPoints,
		&i.Price,
		&i.Icon,
		&i.CostType,
		&i.Thumbnail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDegreeCourseLink = `-- name: GetDegreeCourseLink :one
SELECT order_index FROM degree_courses WHERE degree_id = ? AND course_id = ?
`

type GetDegreeCourseLinkParams struct {
	DegreeID string `json:"degree_id"`
	CourseID string `json:"course_id"`
}

// Used by linkCourses to detect duplicate (degree_id, course_id) pairs
// when bulk-inserting.
func (q *Queries) GetDegreeCourseLink(ctx context.Context, arg GetDegreeCourseLinkParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getDegreeCourseLink, arg.DegreeID, arg.CourseID)
	var order_index int32
	err := row.Scan(&order_index)
	return order_index, err
}

const listDegreeCourses = `-- name: ListDegreeCourses :many
SELECT course_id FROM degree_courses WHERE degree_id = ? ORDER BY order_index ASC
`

// Returns the courses linked to a degree in curriculum order.
func (q *Queries) ListDegreeCourses(ctx context.Context, degreeID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDegreeCourses, degreeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var course_id string
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDegrees = `-- name: ListDegrees :many
SELECT id, title, description, cost_type, price, status, thumbnail
FROM nano_degrees
ORDER BY created_at DESC
LIMIT 200
`

type ListDegreesRow struct {
	ID          string              `json:"id"`
	Title       string              `json:"title"`
	Description string              `json:"description"`
	CostType    NanoDegreesCostType `json:"cost_type"`
	Price       string              `json:"price"`
	Status      NanoDegreesStatus   `json:"status"`
	Thumbnail   sql.NullString      `json:"thumbnail"`
}

// Public list (status filter applied by service layer to enforce
// "drafts hidden from public"). Search is by title OR description LIKE.
// Returns all 4 fields needed for the list view.
func (q *Queries) ListDegrees(ctx context.Context) ([]ListDegreesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDegrees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDegreesRow{}
	for rows.Next() {
		var i ListDegreesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CostType,
			&i.Price,
			&i.Status,
			&i.Thumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxDegreeCourseOrder = `-- name: MaxDegreeCourseOrder :one
SELECT COALESCE(MAX(order_index), -1) FROM degree_courses WHERE degree_id = ?
`

// Used by linkCourses when no order_index is provided (default = max + 1).
func (q *Queries) MaxDegreeCourseOrder(ctx context.Context, degreeID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxDegreeCourseOrder, degreeID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateDegree = `-- name: UpdateDegree :exec
UPDATE nano_degrees
SET title = ?, description = ?, learning_points = ?, price = ?,
    icon = ?, cost_type = ?, thumbnail = ?, status = ?, updated_at = ?
WHERE id = ?
`

type UpdateDegreeParams struct {
	Title          string              `json:"title"`
	Description    string              `json:"description"`
	LearningPoints string              `json:"learning_points"`
	Price          string              `json:"price"`
	Icon           string              `json:"icon"`
	CostType       NanoDegreesCostType `json:"cost_type"`
	Thumbnail      sql.NullString      `json:"thumbnail"`
	Status         NanoDegreesStatus   `json:"status"`
	UpdatedAt      time.Time           `json:"updated_at"`
	ID             string              `json:"id"`
}

func (q *Queries) UpdateDegree(ctx context.Context, arg UpdateDegreeParams) error {
	_, err := q.db.ExecContext(ctx, updateDegree,
		arg.Title,
		arg.Description,
		arg.LearningPoints,
		arg.Price,
		arg.Icon,
		arg.CostType,
		arg.Thumbnail,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertDegreeCourse = `-- name: UpsertDegreeCourse :exec
INSERT INTO degree_courses (degree_id, course_id, order_index)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE order_index = VALUES(order_index)
`

type UpsertDegreeCourseParams struct {
	DegreeID   string `json:"degree_id"`
	CourseID   string `json:"course_id"`
	OrderIndex int32  `json:"order_index"`
}

func (q *Queries) UpsertDegreeCourse(ctx context.Context, arg UpsertDegreeCourseParams) error {
	_, err := q.db.ExecContext(ctx, upsertDegreeCourse, arg.DegreeID, arg.CourseID, arg.OrderIndex)
	return err
}
