// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createEnrollment = `-- name: CreateEnrollment :execresult
INSERT INTO enrollments (
  id, user_id, course_id, degree_id, enrolled_at, expires_at, source, deleted_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateEnrollmentParams struct {
	ID         string            `json:"id"`
	UserID     string            `json:"user_id"`
	CourseID   sql.NullString    `json:"course_id"`
	DegreeID   sql.NullString    `json:"degree_id"`
	EnrolledAt time.Time         `json:"enrolled_at"`
	ExpiresAt  sql.NullTime      `json:"expires_at"`
	Source     EnrollmentsSource `json:"source"`
	DeletedAt  sql.NullTime      `json:"deleted_at"`
}

// Inserts a new enrollment. Caller supplies id (uuid).
// The @@unique([userId, courseId]) constraint enforces one active enrollment per (user, course);
// Service layer uses upsert to revive a soft-deleted row.
func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEnrollment,
		arg.ID,
		arg.UserID,
		arg.CourseID,
		arg.DegreeID,
		arg.EnrolledAt,
		arg.ExpiresAt,
		arg.Source,
		arg.DeletedAt,
	)
}

const getEnrollmentByID = `-- name: GetEnrollmentByID :one
SELECT id, user_id, course_id, degree_id, enrolled_at, expires_at, source, deleted_at
FROM enrollments
WHERE id = ?
`

// Retrieves an enrollment by id.
func (q *Queries) GetEnrollmentByID(ctx context.Context, id string) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentByID, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.DegreeID,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.Source,
		&i.DeletedAt,
	)
	return i, err
}

const getUserCourseEnrollment = `-- name: GetUserCourseEnrollment :one
SELECT id, user_id, course_id, degree_id, enrolled_at, expires_at, source, deleted_at
FROM enrollments
WHERE user_id = ? AND course_id = ? AND deleted_at IS NULL
`

type GetUserCourseEnrollmentParams struct {
	UserID   string         `json:"user_id"`
	CourseID sql.NullString `json:"course_id"`
}

// Look up a specific course enrollment for a user. Returns ErrNoRows if not enrolled.
func (q *Queries) GetUserCourseEnrollment(ctx context.Context, arg GetUserCourseEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, getUserCourseEnrollment, arg.UserID, arg.CourseID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.DegreeID,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.Source,
		&i.DeletedAt,
	)
	return i, err
}

const listEnrollmentsByUser = `-- name: ListEnrollmentsByUser :many
SELECT id, user_id, course_id, degree_id, enrolled_at, expires_at, source, deleted_at
FROM enrollments
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY enrolled_at DESC
`

// All non-deleted enrollments for a user, newest first. Used by /me dashboard.
func (q *Queries) ListEnrollmentsByUser(ctx context.Context, userID string) ([]Enrollment, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.DegreeID,
			&i.EnrolledAt,
			&i.ExpiresAt,
			&i.Source,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEnrollment = `-- name: SoftDeleteEnrollment :exec
UPDATE enrollments
SET deleted_at = ?, source = source
WHERE id = ?
`

type SoftDeleteEnrollmentParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        string       `json:"id"`
}

// Admin withdraw / user drop / batch cleanup. Enrollments use soft-delete
// because the cert/point trail depends on enrollment history.
func (q *Queries) SoftDeleteEnrollment(ctx context.Context, arg SoftDeleteEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteEnrollment, arg.DeletedAt, arg.ID)
	return err
}
