// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enterprise.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countEnterpriseInquiriesByStatus = `-- name: CountEnterpriseInquiriesByStatus :one
SELECT COUNT(*) FROM enterprise_inquiries WHERE status = ? AND deleted_at IS NULL
`

// Lightweight count used for the admin dashboard chip. Includes all
// rows (admin wants to see archived / closed counts too).
func (q *Queries) CountEnterpriseInquiriesByStatus(ctx context.Context, status EnterpriseInquiriesStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnterpriseInquiriesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnterpriseInquiry = `-- name: CreateEnterpriseInquiry :execresult
INSERT INTO enterprise_inquiries
  (id, name, email, company, team_size, phone, topic, description, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEnterpriseInquiryParams struct {
	ID          string                    `json:"id"`
	Name        string                    `json:"name"`
	Email       string                    `json:"email"`
	Company     string                    `json:"company"`
	TeamSize    string                    `json:"team_size"`
	Phone       sql.NullString            `json:"phone"`
	Topic       string                    `json:"topic"`
	Description sql.NullString            `json:"description"`
	Status      EnterpriseInquiriesStatus `json:"status"`
	CreatedAt   time.Time                 `json:"created_at"`
	UpdatedAt   time.Time                 `json:"updated_at"`
}

// Insert a new B2B inquiry row. Caller (service) sets the UUID and
// timestamps; default status 'pending' is applied at the DB layer.
func (q *Queries) CreateEnterpriseInquiry(ctx context.Context, arg CreateEnterpriseInquiryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEnterpriseInquiry,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Company,
		arg.TeamSize,
		arg.Phone,
		arg.Topic,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteEnterpriseInquiry = `-- name: DeleteEnterpriseInquiry :exec
DELETE FROM enterprise_inquiries WHERE id = ?
`

// Hard delete — NestJS service.delete() also issues a plain delete.
// (Soft-delete via deletedAt is supported by the schema but the
// service uses hard delete for the admin "delete inquiry" action.)
func (q *Queries) DeleteEnterpriseInquiry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEnterpriseInquiry, id)
	return err
}

const getEnterpriseInquiryByID = `-- name: GetEnterpriseInquiryByID :one
SELECT id, name, email, company, team_size, phone, topic, description, status, deleted_at, created_at, updated_at FROM enterprise_inquiries WHERE id = ?
`

func (q *Queries) GetEnterpriseInquiryByID(ctx context.Context, id string) (EnterpriseInquiry, error) {
	row := q.db.QueryRowContext(ctx, getEnterpriseInquiryByID, id)
	var i EnterpriseInquiry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Company,
		&i.TeamSize,
		&i.Phone,
		&i.Topic,
		&i.Description,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnterpriseInquiries = `-- name: ListEnterpriseInquiries :many
SELECT id, name, email, company, team_size, phone, topic, description, status, deleted_at, created_at, updated_at FROM enterprise_inquiries
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

// All non-deleted inquiries, newest first. Mirrors the NestJS
// service.findAll() ordering.
func (q *Queries) ListEnterpriseInquiries(ctx context.Context) ([]EnterpriseInquiry, error) {
	rows, err := q.db.QueryContext(ctx, listEnterpriseInquiries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnterpriseInquiry{}
	for rows.Next() {
		var i EnterpriseInquiry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Company,
			&i.TeamSize,
			&i.Phone,
			&i.Topic,
			&i.Description,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnterpriseInquiryStatus = `-- name: UpdateEnterpriseInquiryStatus :exec
UPDATE enterprise_inquiries
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateEnterpriseInquiryStatusParams struct {
	Status    EnterpriseInquiriesStatus `json:"status"`
	UpdatedAt time.Time                 `json:"updated_at"`
	ID        string                    `json:"id"`
}

// Patch only the status column. updated_at is set by the service.
func (q *Queries) UpdateEnterpriseInquiryStatus(ctx context.Context, arg UpdateEnterpriseInquiryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEnterpriseInquiryStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
