// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hackathons.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelRegistration = `-- name: CancelRegistration :execrows
UPDATE hackathon_registrations
SET status = 'cancelled', deleted_at = ?
WHERE hackathon_id = ? AND user_id = ? AND deleted_at IS NULL
`

type CancelRegistrationParams struct {
	DeletedAt   sql.NullTime `json:"deleted_at"`
	HackathonID string       `json:"hackathon_id"`
	UserID      string       `json:"user_id"`
}

func (q *Queries) CancelRegistration(ctx context.Context, arg CancelRegistrationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelRegistration, arg.DeletedAt, arg.HackathonID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countRegistrationsByHackathon = `-- name: CountRegistrationsByHackathon :one
SELECT COUNT(*) FROM hackathon_registrations
WHERE hackathon_id = ? AND status = 'registered' AND deleted_at IS NULL
`

func (q *Queries) CountRegistrationsByHackathon(ctx context.Context, hackathonID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRegistrationsByHackathon, hackathonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) FROM team_members WHERE team_id = ?
`

// Submission count placeholder — NestJS uses _count.submissions. The
// Go port just calls this + a small SQL aggregate for the count.
func (q *Queries) CountTeamMembers(ctx context.Context, teamID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembers, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamsByHackathon = `-- name: CountTeamsByHackathon :one
SELECT COUNT(*) FROM teams WHERE hackathon_id = ?
`

func (q *Queries) CountTeamsByHackathon(ctx context.Context, hackathonID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamsByHackathon, hackathonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :execresult
INSERT INTO announcements (id, hackathon_id, title, content, is_pinned, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAnnouncementParams struct {
	ID          string    `json:"id"`
	HackathonID string    `json:"hackathon_id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	IsPinned    bool      `json:"is_pinned"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAnnouncement,
		arg.ID,
		arg.HackathonID,
		arg.Title,
		arg.Content,
		arg.IsPinned,
		arg.CreatedAt,
	)
}

const createHackathon = `-- name: CreateHackathon :execresult
INSERT INTO hackathons
  (id, title, description, banner_url, status, start_date, end_date, register_deadline, submission_deadline, max_team_size, min_team_size, location, rules, submission_requirements, prizes, registration_url, registration_label, organizer_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHackathonParams struct {
	ID                     string           `json:"id"`
	Title                  string           `json:"title"`
	Description            string           `json:"description"`
	BannerUrl              sql.NullString   `json:"banner_url"`
	Status                 HackathonsStatus `json:"status"`
	StartDate              time.Time        `json:"start_date"`
	EndDate                time.Time        `json:"end_date"`
	RegisterDeadline       sql.NullTime     `json:"register_deadline"`
	SubmissionDeadline     sql.NullTime     `json:"submission_deadline"`
	MaxTeamSize            int32            `json:"max_team_size"`
	MinTeamSize            int32            `json:"min_team_size"`
	Location               sql.NullString   `json:"location"`
	Rules                  sql.NullString   `json:"rules"`
	SubmissionRequirements sql.NullString   `json:"submission_requirements"`
	Prizes                 sql.NullString   `json:"prizes"`
	RegistrationUrl        sql.NullString   `json:"registration_url"`
	RegistrationLabel      sql.NullString   `json:"registration_label"`
	OrganizerID            sql.NullString   `json:"organizer_id"`
	CreatedAt              time.Time        `json:"created_at"`
	UpdatedAt              time.Time        `json:"updated_at"`
}

func (q *Queries) CreateHackathon(ctx context.Context, arg CreateHackathonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHackathon,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.BannerUrl,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.RegisterDeadline,
		arg.SubmissionDeadline,
		arg.MaxTeamSize,
		arg.MinTeamSize,
		arg.Location,
		arg.Rules,
		arg.SubmissionRequirements,
		arg.Prizes,
		arg.RegistrationUrl,
		arg.RegistrationLabel,
		arg.OrganizerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createJudge = `-- name: CreateJudge :execresult
INSERT INTO judges (id, hackathon_id, user_id, name, title, avatar_url, bio, order_index, role)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJudgeParams struct {
	ID          string         `json:"id"`
	HackathonID string         `json:"hackathon_id"`
	UserID      sql.NullString `json:"user_id"`
	Name        string         `json:"name"`
	Title       sql.NullString `json:"title"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
	OrderIndex  int32          `json:"order_index"`
	Role        string         `json:"role"`
}

// judges has NO created_at/updated_at. Just the static columns.
func (q *Queries) CreateJudge(ctx context.Context, arg CreateJudgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createJudge,
		arg.ID,
		arg.HackathonID,
		arg.UserID,
		arg.Name,
		arg.Title,
		arg.AvatarUrl,
		arg.Bio,
		arg.OrderIndex,
		arg.Role,
	)
}

const createSponsor = `-- name: CreateSponsor :execresult
INSERT INTO sponsors (id, hackathon_id, name, logo_url, website_url, tier, order_index, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSponsorParams struct {
	ID          string         `json:"id"`
	HackathonID string         `json:"hackathon_id"`
	Name        string         `json:"name"`
	LogoUrl     sql.NullString `json:"logo_url"`
	WebsiteUrl  sql.NullString `json:"website_url"`
	Tier        string         `json:"tier"`
	OrderIndex  int32          `json:"order_index"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// sponsors has created_at + updated_at. Both are set on insert.
func (q *Queries) CreateSponsor(ctx context.Context, arg CreateSponsorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSponsor,
		arg.ID,
		arg.HackathonID,
		arg.Name,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.Tier,
		arg.OrderIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createSubmission = `-- name: CreateSubmission :execresult
INSERT INTO submissions
  (id, hackathon_id, team_id, user_id, title, description, demo_url, repo_url,
   video_url, status, score, feedback, submitted_at, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)
`

type CreateSubmissionParams struct {
	ID          string            `json:"id"`
	HackathonID string            `json:"hackathon_id"`
	TeamID      sql.NullString    `json:"team_id"`
	UserID      sql.NullString    `json:"user_id"`
	Title       string            `json:"title"`
	Description string            `json:"description"`
	DemoUrl     sql.NullString    `json:"demo_url"`
	RepoUrl     sql.NullString    `json:"repo_url"`
	VideoUrl    sql.NullString    `json:"video_url"`
	Status      SubmissionsStatus `json:"status"`
	Score       sql.NullString    `json:"score"`
	Feedback    sql.NullString    `json:"feedback"`
	SubmittedAt sql.NullTime      `json:"submitted_at"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
}

// submissions HAS updated_at. We set it on insert for consistency with
// the UPDATE path (NestJS also sets both on create).
func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSubmission,
		arg.ID,
		arg.HackathonID,
		arg.TeamID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.DemoUrl,
		arg.RepoUrl,
		arg.VideoUrl,
		arg.Status,
		arg.Score,
		arg.Feedback,
		arg.SubmittedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createTeam = `-- name: CreateTeam :execresult
INSERT INTO teams (id, hackathon_id, name, slogan, captain_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTeamParams struct {
	ID          string         `json:"id"`
	HackathonID string         `json:"hackathon_id"`
	Name        string         `json:"name"`
	Slogan      sql.NullString `json:"slogan"`
	CaptainID   string         `json:"captain_id"`
	CreatedAt   time.Time      `json:"created_at"`
}

// teams has NO updated_at / deleted_at; only created_at. Caller supplies id.
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTeam,
		arg.ID,
		arg.HackathonID,
		arg.Name,
		arg.Slogan,
		arg.CaptainID,
		arg.CreatedAt,
	)
}

const createTeamMember = `-- name: CreateTeamMember :execresult
INSERT INTO team_members (id, team_id, user_id, role)
VALUES (?, ?, ?, ?)
`

type CreateTeamMemberParams struct {
	ID     string          `json:"id"`
	TeamID string          `json:"team_id"`
	UserID string          `json:"user_id"`
	Role   TeamMembersRole `json:"role"`
}

// Inserts a team_member row. UNIQUE(team_id, user_id) enforces no dupes.
func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTeamMember,
		arg.ID,
		arg.TeamID,
		arg.UserID,
		arg.Role,
	)
}

const deleteHackathon = `-- name: DeleteHackathon :execrows
DELETE FROM hackathons WHERE id = ?
`

// Hard delete. The schema has no deleted_at column, so soft-delete is
// encoded as status='cancelled' via SoftDeleteHackathon.
func (q *Queries) DeleteHackathon(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHackathon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteJudge = `-- name: DeleteJudge :execrows
DELETE FROM judges WHERE id = ?
`

// Hard delete. NestJS uses prisma.judge.delete.
func (q *Queries) DeleteJudge(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteJudge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSponsor = `-- name: DeleteSponsor :execrows
DELETE FROM sponsors WHERE id = ?
`

// Hard delete. NestJS uses prisma.sponsor.delete.
func (q *Queries) DeleteSponsor(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSponsor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTeam = `-- name: DeleteTeam :execrows
DELETE FROM teams WHERE id = ?
`

// Hard delete. NestJS uses prisma.team.delete (CASCADE removes members
// + submissions via FK ON DELETE CASCADE). No soft delete column.
func (q *Queries) DeleteTeam(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTeam, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTeamMember = `-- name: DeleteTeamMember :execrows
DELETE FROM team_members WHERE id = ?
`

func (q *Queries) DeleteTeamMember(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTeamMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findTeamByHackathonAndName = `-- name: FindTeamByHackathonAndName :one
SELECT id FROM teams WHERE hackathon_id = ? AND name = ? LIMIT 1
`

type FindTeamByHackathonAndNameParams struct {
	HackathonID string `json:"hackathon_id"`
	Name        string `json:"name"`
}

// Service uses this for the "name already exists in this hackathon" 400.
func (q *Queries) FindTeamByHackathonAndName(ctx context.Context, arg FindTeamByHackathonAndNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findTeamByHackathonAndName, arg.HackathonID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findTeamMembershipForUserInHackathon = `-- name: FindTeamMembershipForUserInHackathon :one
SELECT tm.id, tm.team_id, tm.user_id, tm.role
FROM team_members tm
JOIN teams t ON t.id = tm.team_id
WHERE tm.user_id = ? AND t.hackathon_id = ?
LIMIT 1
`

type FindTeamMembershipForUserInHackathonParams struct {
	UserID      string `json:"user_id"`
	HackathonID string `json:"hackathon_id"`
}

// Used by joinTeam/createTeam to enforce "you can only be in one team
// per hackathon" — the unique index on (team_id, user_id) doesn't
// span hackathons, so this query joins teams.
func (q *Queries) FindTeamMembershipForUserInHackathon(ctx context.Context, arg FindTeamMembershipForUserInHackathonParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, findTeamMembershipForUserInHackathon, arg.UserID, arg.HackathonID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const getHackathonByID = `-- name: GetHackathonByID :one
SELECT id, title, description, banner_url, status, start_date, end_date, register_deadline, submission_deadline, max_team_size, min_team_size, location, rules, submission_requirements, prizes, registration_url, registration_label, organizer_id, created_at, updated_at FROM hackathons WHERE id = ?
`

// The hackathons table has NO deleted_at column. The cancelled status
// is a real state, not a tombstone — see effectiveStatus in service.
func (q *Queries) GetHackathonByID(ctx context.Context, id string) (Hackathon, error) {
	row := q.db.QueryRowContext(ctx, getHackathonByID, id)
	var i Hackathon
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.RegisterDeadline,
		&i.SubmissionDeadline,
		&i.MaxTeamSize,
		&i.MinTeamSize,
		&i.Location,
		&i.Rules,
		&i.SubmissionRequirements,
		&i.Prizes,
		&i.RegistrationUrl,
		&i.RegistrationLabel,
		&i.OrganizerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHackathonResponseRow = `-- name: GetHackathonResponseRow :one
SELECT
  h.id, h.title, h.description, h.banner_url, h.status, h.start_date, h.end_date,
  h.register_deadline, h.submission_deadline, h.max_team_size, h.min_team_size,
  h.location, h.rules, h.submission_requirements, h.prizes, h.registration_url,
  h.registration_label, h.organizer_id, h.created_at, h.updated_at,
  ou.id AS organizer_user_id, ou.name AS organizer_name, ou.avatar_url AS organizer_avatar_url,
  (SELECT COUNT(*) FROM hackathon_registrations hr
    WHERE hr.hackathon_id = h.id AND hr.status = 'registered' AND hr.deleted_at IS NULL) AS registration_count,
  (SELECT COUNT(*) FROM teams t WHERE t.hackathon_id = h.id) AS team_count,
  (SELECT COUNT(*) FROM submissions s WHERE s.hackathon_id = h.id AND s.deleted_at IS NULL) AS submission_count,
  mr.id AS my_registration_id, mr.user_id AS my_registration_user_id,
  mr.status AS my_registration_status, mr.registered_at AS my_registration_registered_at,
  mr.checked_in_at AS my_registration_checked_in_at
FROM hackathons h
LEFT JOIN users ou ON ou.id = h.organizer_id
LEFT JOIN hackathon_registrations mr ON mr.hackathon_id = h.id AND mr.user_id = ?
WHERE h.id = ?
`

type GetHackathonResponseRowParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetHackathonResponseRowRow struct {
	ID                         string                           `json:"id"`
	Title                      string                           `json:"title"`
	Description                string                           `json:"description"`
	BannerUrl                  sql.NullString                   `json:"banner_url"`
	Status                     HackathonsStatus                 `json:"status"`
	StartDate                  time.Time                        `json:"start_date"`
	EndDate                    time.Time                        `json:"end_date"`
	RegisterDeadline           sql.NullTime                     `json:"register_deadline"`
	SubmissionDeadline         sql.NullTime                     `json:"submission_deadline"`
	MaxTeamSize                int32                            `json:"max_team_size"`
	MinTeamSize                int32                            `json:"min_team_size"`
	Location                   sql.NullString                   `json:"location"`
	Rules                      sql.NullString                   `json:"rules"`
	SubmissionRequirements     sql.NullString                   `json:"submission_requirements"`
	Prizes                     sql.NullString                   `json:"prizes"`
	RegistrationUrl            sql.NullString                   `json:"registration_url"`
	RegistrationLabel          sql.NullString                   `json:"registration_label"`
	OrganizerID                sql.NullString                   `json:"organizer_id"`
	CreatedAt                  time.Time                        `json:"created_at"`
	UpdatedAt                  time.Time                        `json:"updated_at"`
	OrganizerUserID            sql.NullString                   `json:"organizer_user_id"`
	OrganizerName              sql.NullString                   `json:"organizer_name"`
	OrganizerAvatarUrl         sql.NullString                   `json:"organizer_avatar_url"`
	RegistrationCount          int64                            `json:"registration_count"`
	TeamCount                  int64                            `json:"team_count"`
	SubmissionCount            int64                            `json:"submission_count"`
	MyRegistrationID           sql.NullString                   `json:"my_registration_id"`
	MyRegistrationUserID       sql.NullString                   `json:"my_registration_user_id"`
	MyRegistrationStatus       NullHackathonRegistrationsStatus `json:"my_registration_status"`
	MyRegistrationRegisteredAt sql.NullTime                     `json:"my_registration_registered_at"`
	MyRegistrationCheckedInAt  sql.NullTime                     `json:"my_registration_checked_in_at"`
}

func (q *Queries) GetHackathonResponseRow(ctx context.Context, arg GetHackathonResponseRowParams) (GetHackathonResponseRowRow, error) {
	row := q.db.QueryRowContext(ctx, getHackathonResponseRow, arg.UserID, arg.ID)
	var i GetHackathonResponseRowRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.RegisterDeadline,
		&i.SubmissionDeadline,
		&i.MaxTeamSize,
		&i.MinTeamSize,
		&i.Location,
		&i.Rules,
		&i.SubmissionRequirements,
		&i.Prizes,
		&i.RegistrationUrl,
		&i.RegistrationLabel,
		&i.OrganizerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizerUserID,
		&i.OrganizerName,
		&i.OrganizerAvatarUrl,
		&i.RegistrationCount,
		&i.TeamCount,
		&i.SubmissionCount,
		&i.MyRegistrationID,
		&i.MyRegistrationUserID,
		&i.MyRegistrationStatus,
		&i.MyRegistrationRegisteredAt,
		&i.MyRegistrationCheckedInAt,
	)
	return i, err
}

const getJudgeByID = `-- name: GetJudgeByID :one

SELECT id, hackathon_id, user_id, name, title, avatar_url, bio, order_index, role FROM judges WHERE id = ?
`

// ==================== Judges ====================
// judges has NO deleted_at. Direct lookup.
func (q *Queries) GetJudgeByID(ctx context.Context, id string) (Judge, error) {
	row := q.db.QueryRowContext(ctx, getJudgeByID, id)
	var i Judge
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.UserID,
		&i.Name,
		&i.Title,
		&i.AvatarUrl,
		&i.Bio,
		&i.OrderIndex,
		&i.Role,
	)
	return i, err
}

const getRegistration = `-- name: GetRegistration :one
SELECT id, hackathon_id, user_id, status, registered_at, checked_in_at
FROM hackathon_registrations
WHERE hackathon_id = ? AND user_id = ? AND deleted_at IS NULL
`

type GetRegistrationParams struct {
	HackathonID string `json:"hackathon_id"`
	UserID      string `json:"user_id"`
}

type GetRegistrationRow struct {
	ID           string                       `json:"id"`
	HackathonID  string                       `json:"hackathon_id"`
	UserID       string                       `json:"user_id"`
	Status       HackathonRegistrationsStatus `json:"status"`
	RegisteredAt time.Time                    `json:"registered_at"`
	CheckedInAt  sql.NullTime                 `json:"checked_in_at"`
}

// hackathon_registrations HAS a deleted_at column, so this filter is valid.
func (q *Queries) GetRegistration(ctx context.Context, arg GetRegistrationParams) (GetRegistrationRow, error) {
	row := q.db.QueryRowContext(ctx, getRegistration, arg.HackathonID, arg.UserID)
	var i GetRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.UserID,
		&i.Status,
		&i.RegisteredAt,
		&i.CheckedInAt,
	)
	return i, err
}

const getRegistrationIncludingCancelled = `-- name: GetRegistrationIncludingCancelled :one
SELECT id, hackathon_id, user_id, status, registered_at, checked_in_at
FROM hackathon_registrations
WHERE hackathon_id = ? AND user_id = ?
`

type GetRegistrationIncludingCancelledParams struct {
	HackathonID string `json:"hackathon_id"`
	UserID      string `json:"user_id"`
}

type GetRegistrationIncludingCancelledRow struct {
	ID           string                       `json:"id"`
	HackathonID  string                       `json:"hackathon_id"`
	UserID       string                       `json:"user_id"`
	Status       HackathonRegistrationsStatus `json:"status"`
	RegisteredAt time.Time                    `json:"registered_at"`
	CheckedInAt  sql.NullTime                 `json:"checked_in_at"`
}

// For my-registration endpoint: return the row even if status='cancelled'
// so the client can render the "you cancelled" state.
func (q *Queries) GetRegistrationIncludingCancelled(ctx context.Context, arg GetRegistrationIncludingCancelledParams) (GetRegistrationIncludingCancelledRow, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationIncludingCancelled, arg.HackathonID, arg.UserID)
	var i GetRegistrationIncludingCancelledRow
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.UserID,
		&i.Status,
		&i.RegisteredAt,
		&i.CheckedInAt,
	)
	return i, err
}

const getSponsorByID = `-- name: GetSponsorByID :one

SELECT id, hackathon_id, name, logo_url, website_url, tier, order_index, created_at, updated_at FROM sponsors WHERE id = ?
`

// ==================== Sponsors ====================
func (q *Queries) GetSponsorByID(ctx context.Context, id string) (Sponsor, error) {
	row := q.db.QueryRowContext(ctx, getSponsorByID, id)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.Name,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.Tier,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one

SELECT id, hackathon_id, team_id, user_id, title, description, demo_url, repo_url, video_url, status, score, feedback, submitted_at, created_at, updated_at, deleted_at FROM submissions WHERE id = ? AND deleted_at IS NULL
`

// ==================== Submissions ====================
// submissions has deleted_at; we filter it here so a soft-deleted row
// can't be referenced by id (matches NestJS findFirst behavior).
func (q *Queries) GetSubmissionByID(ctx context.Context, id string) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.TeamID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.VideoUrl,
		&i.Status,
		&i.Score,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSubmissionIncludingDeleted = `-- name: GetSubmissionIncludingDeleted :one
SELECT id, hackathon_id, team_id, user_id, title, description, demo_url, repo_url, video_url, status, score, feedback, submitted_at, created_at, updated_at, deleted_at FROM submissions WHERE id = ?
`

// Admin / audit path: returns the row even if soft-deleted.
func (q *Queries) GetSubmissionIncludingDeleted(ctx context.Context, id string) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionIncludingDeleted, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.TeamID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.VideoUrl,
		&i.Status,
		&i.Score,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one


SELECT id, hackathon_id, name, slogan, captain_id, created_at FROM teams WHERE id = ?
`

// ============================================================================
// T19.1 — Teams / TeamMembers / Submissions / Judges / Sponsors
// Schema caveats (verified against db/migrations/0001_init.sql):
//   - teams: NO slug, NO updated_at, NO deleted_at. columns: id, hackathon_id,
//     name, slogan, captain_id, created_at.
//   - team_members: NO joined_at, NO deleted_at. columns: id, team_id, user_id,
//     role (ENUM 'captain'|'member').
//   - submissions: HAS deleted_at (soft delete). columns: ..., demo_url,
//     repo_url, video_url, status, score, feedback, submitted_at, ...
//   - judges: NO created_at, NO updated_at, NO deleted_at. columns: id,
//     hackathon_id, user_id, name, title, avatar_url, bio, order_index, role.
//   - sponsors: NO deleted_at. columns: id, hackathon_id, name, logo_url,
//     website_url, tier, order_index, created_at, updated_at.
//
// ============================================================================
// ==================== Teams ====================
// Returns a team by primary key. Used for owner-checks + lookups.
func (q *Queries) GetTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.Name,
		&i.Slogan,
		&i.CaptainID,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMemberByID = `-- name: GetTeamMemberByID :one

SELECT id, team_id, user_id, role FROM team_members WHERE id = ?
`

// ==================== TeamMembers ====================
func (q *Queries) GetTeamMemberByID(ctx context.Context, id string) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getTeamMemberByID, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const getTeamMemberForUserAndTeam = `-- name: GetTeamMemberForUserAndTeam :one
SELECT id, team_id, user_id, role FROM team_members WHERE team_id = ? AND user_id = ? LIMIT 1
`

type GetTeamMemberForUserAndTeamParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

// Used by leaveTeam to find the (team, user) membership.
func (q *Queries) GetTeamMemberForUserAndTeam(ctx context.Context, arg GetTeamMemberForUserAndTeamParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getTeamMemberForUserAndTeam, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, hackathon_id, title, content, is_pinned, created_at
FROM announcements
WHERE hackathon_id = ?
ORDER BY is_pinned DESC, created_at DESC
LIMIT ?
`

type ListAnnouncementsParams struct {
	HackathonID string `json:"hackathon_id"`
	Limit       int32  `json:"limit"`
}

// announcements has no updated_at column (see schema).
func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements, arg.HackathonID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHackathonResponseRows = `-- name: ListHackathonResponseRows :many
SELECT
  h.id, h.title, h.description, h.banner_url, h.status, h.start_date, h.end_date,
  h.register_deadline, h.submission_deadline, h.max_team_size, h.min_team_size,
  h.location, h.rules, h.submission_requirements, h.prizes, h.registration_url,
  h.registration_label, h.organizer_id, h.created_at, h.updated_at,
  ou.id AS organizer_user_id, ou.name AS organizer_name, ou.avatar_url AS organizer_avatar_url,
  (SELECT COUNT(*) FROM hackathon_registrations hr
    WHERE hr.hackathon_id = h.id AND hr.status = 'registered' AND hr.deleted_at IS NULL) AS registration_count,
  (SELECT COUNT(*) FROM teams t WHERE t.hackathon_id = h.id) AS team_count,
  (SELECT COUNT(*) FROM submissions s WHERE s.hackathon_id = h.id AND s.deleted_at IS NULL) AS submission_count,
  mr.id AS my_registration_id, mr.user_id AS my_registration_user_id,
  mr.status AS my_registration_status, mr.registered_at AS my_registration_registered_at,
  mr.checked_in_at AS my_registration_checked_in_at
FROM hackathons h
LEFT JOIN users ou ON ou.id = h.organizer_id
LEFT JOIN hackathon_registrations mr ON mr.hackathon_id = h.id AND mr.user_id = ?
WHERE (
    ? = ''
    OR h.title LIKE CONCAT('%', ?, '%')
    OR h.description LIKE CONCAT('%', ?, '%')
    OR h.location LIKE CONCAT('%', ?, '%')
  )
ORDER BY h.start_date DESC
LIMIT ?
`

type ListHackathonResponseRowsParams struct {
	UserID string      `json:"user_id"`
	Search interface{} `json:"search"`
	Limit  int32       `json:"limit"`
}

type ListHackathonResponseRowsRow struct {
	ID                         string                           `json:"id"`
	Title                      string                           `json:"title"`
	Description                string                           `json:"description"`
	BannerUrl                  sql.NullString                   `json:"banner_url"`
	Status                     HackathonsStatus                 `json:"status"`
	StartDate                  time.Time                        `json:"start_date"`
	EndDate                    time.Time                        `json:"end_date"`
	RegisterDeadline           sql.NullTime                     `json:"register_deadline"`
	SubmissionDeadline         sql.NullTime                     `json:"submission_deadline"`
	MaxTeamSize                int32                            `json:"max_team_size"`
	MinTeamSize                int32                            `json:"min_team_size"`
	Location                   sql.NullString                   `json:"location"`
	Rules                      sql.NullString                   `json:"rules"`
	SubmissionRequirements     sql.NullString                   `json:"submission_requirements"`
	Prizes                     sql.NullString                   `json:"prizes"`
	RegistrationUrl            sql.NullString                   `json:"registration_url"`
	RegistrationLabel          sql.NullString                   `json:"registration_label"`
	OrganizerID                sql.NullString                   `json:"organizer_id"`
	CreatedAt                  time.Time                        `json:"created_at"`
	UpdatedAt                  time.Time                        `json:"updated_at"`
	OrganizerUserID            sql.NullString                   `json:"organizer_user_id"`
	OrganizerName              sql.NullString                   `json:"organizer_name"`
	OrganizerAvatarUrl         sql.NullString                   `json:"organizer_avatar_url"`
	RegistrationCount          int64                            `json:"registration_count"`
	TeamCount                  int64                            `json:"team_count"`
	SubmissionCount            int64                            `json:"submission_count"`
	MyRegistrationID           sql.NullString                   `json:"my_registration_id"`
	MyRegistrationUserID       sql.NullString                   `json:"my_registration_user_id"`
	MyRegistrationStatus       NullHackathonRegistrationsStatus `json:"my_registration_status"`
	MyRegistrationRegisteredAt sql.NullTime                     `json:"my_registration_registered_at"`
	MyRegistrationCheckedInAt  sql.NullTime                     `json:"my_registration_checked_in_at"`
}

// API list projection in one round-trip: organizer, all aggregate counts and
// the optional caller registration. The service still computes effectiveStatus.
func (q *Queries) ListHackathonResponseRows(ctx context.Context, arg ListHackathonResponseRowsParams) ([]ListHackathonResponseRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHackathonResponseRows,
		arg.UserID,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHackathonResponseRowsRow{}
	for rows.Next() {
		var i ListHackathonResponseRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.BannerUrl,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.RegisterDeadline,
			&i.SubmissionDeadline,
			&i.MaxTeamSize,
			&i.MinTeamSize,
			&i.Location,
			&i.Rules,
			&i.SubmissionRequirements,
			&i.Prizes,
			&i.RegistrationUrl,
			&i.RegistrationLabel,
			&i.OrganizerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizerUserID,
			&i.OrganizerName,
			&i.OrganizerAvatarUrl,
			&i.RegistrationCount,
			&i.TeamCount,
			&i.SubmissionCount,
			&i.MyRegistrationID,
			&i.MyRegistrationUserID,
			&i.MyRegistrationStatus,
			&i.MyRegistrationRegisteredAt,
			&i.MyRegistrationCheckedInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHackathons = `-- name: ListHackathons :many
SELECT id, title, description, banner_url, status, start_date, end_date, register_deadline, submission_deadline, max_team_size, min_team_size, location, rules, submission_requirements, prizes, registration_url, registration_label, organizer_id, created_at, updated_at FROM hackathons
WHERE (? = '' OR status = ?)
  AND (
    ? = ''
    OR title LIKE ?
    OR description LIKE ?
    OR location LIKE ?
  )
ORDER BY start_date DESC
LIMIT ?
`

type ListHackathonsParams struct {
	Column1     interface{}      `json:"column_1"`
	Status      HackathonsStatus `json:"status"`
	Column3     interface{}      `json:"column_3"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Location    sql.NullString   `json:"location"`
	Limit       int32            `json:"limit"`
}

// Public list. The hackathons table has NO deleted_at column; soft-delete
// is encoded as status='cancelled' (see SoftDeleteHackathon below).
// statusFilter: when non-empty, applied at SQL level. When empty, all rows
// are returned and the service layer applies date-based effectiveStatus
// inference (mirrors NestJS findAll).
func (q *Queries) ListHackathons(ctx context.Context, arg ListHackathonsParams) ([]Hackathon, error) {
	rows, err := q.db.QueryContext(ctx, listHackathons,
		arg.Column1,
		arg.Status,
		arg.Column3,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hackathon{}
	for rows.Next() {
		var i Hackathon
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.BannerUrl,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.RegisterDeadline,
			&i.SubmissionDeadline,
			&i.MaxTeamSize,
			&i.MinTeamSize,
			&i.Location,
			&i.Rules,
			&i.SubmissionRequirements,
			&i.Prizes,
			&i.RegistrationUrl,
			&i.RegistrationLabel,
			&i.OrganizerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJudgesByHackathon = `-- name: ListJudgesByHackathon :many
SELECT id, hackathon_id, user_id, name, title, avatar_url, bio, order_index, role FROM judges
WHERE hackathon_id = ?
ORDER BY order_index ASC, name ASC
LIMIT ?
`

type ListJudgesByHackathonParams struct {
	HackathonID string `json:"hackathon_id"`
	Limit       int32  `json:"limit"`
}

// Public list, ordered by orderIndex ASC (NestJS parity).
func (q *Queries) ListJudgesByHackathon(ctx context.Context, arg ListJudgesByHackathonParams) ([]Judge, error) {
	rows, err := q.db.QueryContext(ctx, listJudgesByHackathon, arg.HackathonID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Judge{}
	for rows.Next() {
		var i Judge
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.UserID,
			&i.Name,
			&i.Title,
			&i.AvatarUrl,
			&i.Bio,
			&i.OrderIndex,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMySubmissions = `-- name: ListMySubmissions :many
SELECT s.id, s.hackathon_id, s.team_id, s.user_id, s.title, s.description, s.demo_url, s.repo_url, s.video_url, s.status, s.score, s.feedback, s.submitted_at, s.created_at, s.updated_at, s.deleted_at FROM submissions s
LEFT JOIN team_members tm ON tm.team_id = s.team_id AND tm.user_id = ?
WHERE s.hackathon_id = ?
  AND s.deleted_at IS NULL
  AND (s.user_id = ? OR tm.id IS NOT NULL)
GROUP BY s.id
ORDER BY s.created_at DESC
LIMIT ?
`

type ListMySubmissionsParams struct {
	UserID      string         `json:"user_id"`
	HackathonID string         `json:"hackathon_id"`
	UserID_2    sql.NullString `json:"user_id_2"`
	Limit       int32          `json:"limit"`
}

// "My submissions" — owned by user OR by a team the user is a member of.
// Uses OR-clause in SQL. (NestJS does the same via Prisma's
// `OR: [{ userId }, { team: { members: { some: { userId } } } }]`.)
// The two `?` slots that hold the user id are positionally identical at
// runtime; sqlc names them UserID + UserID_2 in the generated params.
func (q *Queries) ListMySubmissions(ctx context.Context, arg ListMySubmissionsParams) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listMySubmissions,
		arg.UserID,
		arg.HackathonID,
		arg.UserID_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.TeamID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.DemoUrl,
			&i.RepoUrl,
			&i.VideoUrl,
			&i.Status,
			&i.Score,
			&i.Feedback,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSponsorsByHackathon = `-- name: ListSponsorsByHackathon :many
SELECT id, hackathon_id, name, logo_url, website_url, tier, order_index, created_at, updated_at FROM sponsors
WHERE hackathon_id = ?
ORDER BY tier ASC, order_index ASC, name ASC
LIMIT ?
`

type ListSponsorsByHackathonParams struct {
	HackathonID string `json:"hackathon_id"`
	Limit       int32  `json:"limit"`
}

// Public list, ordered by tier ASC, orderIndex ASC (NestJS parity).
func (q *Queries) ListSponsorsByHackathon(ctx context.Context, arg ListSponsorsByHackathonParams) ([]Sponsor, error) {
	rows, err := q.db.QueryContext(ctx, listSponsorsByHackathon, arg.HackathonID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sponsor{}
	for rows.Next() {
		var i Sponsor
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.Name,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.Tier,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByHackathon = `-- name: ListSubmissionsByHackathon :many
SELECT id, hackathon_id, team_id, user_id, title, description, demo_url, repo_url, video_url, status, score, feedback, submitted_at, created_at, updated_at, deleted_at FROM submissions
WHERE hackathon_id = ? AND deleted_at IS NULL
ORDER BY status ASC, created_at DESC
LIMIT ?
`

type ListSubmissionsByHackathonParams struct {
	HackathonID string `json:"hackathon_id"`
	Limit       int32  `json:"limit"`
}

// Admin's "all submissions" view. No user/team filter.
func (q *Queries) ListSubmissionsByHackathon(ctx context.Context, arg ListSubmissionsByHackathonParams) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByHackathon, arg.HackathonID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.TeamID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.DemoUrl,
			&i.RepoUrl,
			&i.VideoUrl,
			&i.Status,
			&i.Score,
			&i.Feedback,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersByTeam = `-- name: ListTeamMembersByTeam :many
SELECT
  tm.id           AS tm_id,
  tm.team_id      AS tm_team_id,
  tm.user_id      AS tm_user_id,
  tm.role         AS tm_role,
  u.id            AS user_id,
  u.name          AS user_name,
  u.avatar_url    AS user_avatar_url
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = ?
ORDER BY (tm.role = 'captain') DESC, tm.id ASC
`

type ListTeamMembersByTeamRow struct {
	TmID          string          `json:"tm_id"`
	TmTeamID      string          `json:"tm_team_id"`
	TmUserID      string          `json:"tm_user_id"`
	TmRole        TeamMembersRole `json:"tm_role"`
	UserID        string          `json:"user_id"`
	UserName      string          `json:"user_name"`
	UserAvatarUrl sql.NullString  `json:"user_avatar_url"`
}

// Includes user name + avatar via JOIN. The frontend can render the
// team roster without a second roundtrip.
func (q *Queries) ListTeamMembersByTeam(ctx context.Context, teamID string) ([]ListTeamMembersByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersByTeamRow{}
	for rows.Next() {
		var i ListTeamMembersByTeamRow
		if err := rows.Scan(
			&i.TmID,
			&i.TmTeamID,
			&i.TmUserID,
			&i.TmRole,
			&i.UserID,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByHackathon = `-- name: ListTeamsByHackathon :many
SELECT id, hackathon_id, name, slogan, captain_id, created_at FROM teams
WHERE hackathon_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListTeamsByHackathonParams struct {
	HackathonID string `json:"hackathon_id"`
	Limit       int32  `json:"limit"`
}

// Public list. NestJS includes members + submission count, but the Go
// port uses a second query (ListTeamMembersByTeam + submission count) so
// the team row is hydrated in the service layer.
func (q *Queries) ListTeamsByHackathon(ctx context.Context, arg ListTeamsByHackathonParams) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByHackathon, arg.HackathonID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.Name,
			&i.Slogan,
			&i.CaptainID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteHackathon = `-- name: SoftDeleteHackathon :execrows
UPDATE hackathons SET status = 'cancelled', updated_at = ? WHERE id = ?
`

type SoftDeleteHackathonParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

// Mark as cancelled (the hackathons table's notion of "soft delete"
// since there is no deleted_at column). Idempotent.
func (q *Queries) SoftDeleteHackathon(ctx context.Context, arg SoftDeleteHackathonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteHackathon, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteSubmission = `-- name: SoftDeleteSubmission :execrows
UPDATE submissions SET deleted_at = ?, updated_at = ? WHERE id = ?
`

type SoftDeleteSubmissionParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

// Sets deleted_at to soft-delete. (Not in NestJS for submissions, but
// the column is in the schema, so we support it for the API surface
// parity. NestJS uses prisma.submission.delete() — we follow the
// schema instead and soft-delete by default; tests assert this.)
func (q *Queries) SoftDeleteSubmission(ctx context.Context, arg SoftDeleteSubmissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteSubmission, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateHackathon = `-- name: UpdateHackathon :execrows
UPDATE hackathons
SET title = ?, description = ?, status = ?, start_date = ?, end_date = ?,
    register_deadline = ?, submission_deadline = ?, max_team_size = ?, min_team_size = ?,
    banner_url = ?, location = ?, rules = ?, submission_requirements = ?, prizes = ?,
    registration_url = ?, registration_label = ?, organizer_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateHackathonParams struct {
	Title                  string           `json:"title"`
	Description            string           `json:"description"`
	Status                 HackathonsStatus `json:"status"`
	StartDate              time.Time        `json:"start_date"`
	EndDate                time.Time        `json:"end_date"`
	RegisterDeadline       sql.NullTime     `json:"register_deadline"`
	SubmissionDeadline     sql.NullTime     `json:"submission_deadline"`
	MaxTeamSize            int32            `json:"max_team_size"`
	MinTeamSize            int32            `json:"min_team_size"`
	BannerUrl              sql.NullString   `json:"banner_url"`
	Location               sql.NullString   `json:"location"`
	Rules                  sql.NullString   `json:"rules"`
	SubmissionRequirements sql.NullString   `json:"submission_requirements"`
	Prizes                 sql.NullString   `json:"prizes"`
	RegistrationUrl        sql.NullString   `json:"registration_url"`
	RegistrationLabel      sql.NullString   `json:"registration_label"`
	OrganizerID            sql.NullString   `json:"organizer_id"`
	UpdatedAt              time.Time        `json:"updated_at"`
	ID                     string           `json:"id"`
}

// The hackathons table has NO deleted_at column.
func (q *Queries) UpdateHackathon(ctx context.Context, arg UpdateHackathonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateHackathon,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.RegisterDeadline,
		arg.SubmissionDeadline,
		arg.MaxTeamSize,
		arg.MinTeamSize,
		arg.BannerUrl,
		arg.Location,
		arg.Rules,
		arg.SubmissionRequirements,
		arg.Prizes,
		arg.RegistrationUrl,
		arg.RegistrationLabel,
		arg.OrganizerID,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJudge = `-- name: UpdateJudge :exec
UPDATE judges
SET user_id = ?, name = ?, title = ?, avatar_url = ?, bio = ?, order_index = ?, role = ?
WHERE id = ?
`

type UpdateJudgeParams struct {
	UserID     sql.NullString `json:"user_id"`
	Name       string         `json:"name"`
	Title      sql.NullString `json:"title"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	Bio        sql.NullString `json:"bio"`
	OrderIndex int32          `json:"order_index"`
	Role       string         `json:"role"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateJudge(ctx context.Context, arg UpdateJudgeParams) error {
	_, err := q.db.ExecContext(ctx, updateJudge,
		arg.UserID,
		arg.Name,
		arg.Title,
		arg.AvatarUrl,
		arg.Bio,
		arg.OrderIndex,
		arg.Role,
		arg.ID,
	)
	return err
}

const updateSponsor = `-- name: UpdateSponsor :exec
UPDATE sponsors
SET name = ?, logo_url = ?, website_url = ?, tier = ?, order_index = ?, updated_at = ?
WHERE id = ?
`

type UpdateSponsorParams struct {
	Name       string         `json:"name"`
	LogoUrl    sql.NullString `json:"logo_url"`
	WebsiteUrl sql.NullString `json:"website_url"`
	Tier       string         `json:"tier"`
	OrderIndex int32          `json:"order_index"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateSponsor(ctx context.Context, arg UpdateSponsorParams) error {
	_, err := q.db.ExecContext(ctx, updateSponsor,
		arg.Name,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.Tier,
		arg.OrderIndex,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSubmission = `-- name: UpdateSubmission :exec
UPDATE submissions
SET title = ?, description = ?, demo_url = ?, repo_url = ?, video_url = ?,
    status = ?, score = ?, feedback = ?, submitted_at = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateSubmissionParams struct {
	Title       string            `json:"title"`
	Description string            `json:"description"`
	DemoUrl     sql.NullString    `json:"demo_url"`
	RepoUrl     sql.NullString    `json:"repo_url"`
	VideoUrl    sql.NullString    `json:"video_url"`
	Status      SubmissionsStatus `json:"status"`
	Score       sql.NullString    `json:"score"`
	Feedback    sql.NullString    `json:"feedback"`
	SubmittedAt sql.NullTime      `json:"submitted_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
	ID          string            `json:"id"`
}

// Partial update. Service reads the row first and passes the merged
// patch + the resolved submittedAt timestamp.
func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubmission,
		arg.Title,
		arg.Description,
		arg.DemoUrl,
		arg.RepoUrl,
		arg.VideoUrl,
		arg.Status,
		arg.Score,
		arg.Feedback,
		arg.SubmittedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertRegistration = `-- name: UpsertRegistration :execresult
INSERT INTO hackathon_registrations
  (id, hackathon_id, user_id, status, registered_at)
VALUES (?, ?, ?, 'registered', ?)
ON DUPLICATE KEY UPDATE status = 'registered', deleted_at = NULL
`

type UpsertRegistrationParams struct {
	ID           string    `json:"id"`
	HackathonID  string    `json:"hackathon_id"`
	UserID       string    `json:"user_id"`
	RegisteredAt time.Time `json:"registered_at"`
}

// Idempotent: re-registration of a previously-cancelled user re-activates
// (status='registered', deleted_at=NULL).
func (q *Queries) UpsertRegistration(ctx context.Context, arg UpsertRegistrationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertRegistration,
		arg.ID,
		arg.HackathonID,
		arg.UserID,
		arg.RegisteredAt,
	)
}
