// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instructors.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const clearPrimaryInstructorForRole = `-- name: ClearPrimaryInstructorForRole :exec
UPDATE course_instructor_links
SET is_primary = false
WHERE course_id = ? AND role = ? AND id != ? AND is_primary = true
`

type ClearPrimaryInstructorForRoleParams struct {
	CourseID string                    `json:"course_id"`
	Role     CourseInstructorLinksRole `json:"role"`
	ID       string                    `json:"id"`
}

// When promoting a new primary instructor for a given (course, role),
// clear is_primary on every other link in the same (course, role) — the
// id of the freshly-inserted link is excluded.
func (q *Queries) ClearPrimaryInstructorForRole(ctx context.Context, arg ClearPrimaryInstructorForRoleParams) error {
	_, err := q.db.ExecContext(ctx, clearPrimaryInstructorForRole, arg.CourseID, arg.Role, arg.ID)
	return err
}

const countInstructorsByFilter = `-- name: CountInstructorsByFilter :one
SELECT COUNT(*) AS count FROM instructors
`

// Mirrors the public/admin list filter. Built dynamically by the repo
// because the WHERE composition depends on the query string.
// This static query is only used for the admin "all statuses, no filter"
// path (when no args are supplied). See repo for the dynamic version.
func (q *Queries) CountInstructorsByFilter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInstructorsByFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourseInstructorLink = `-- name: CreateCourseInstructorLink :execresult
INSERT INTO course_instructor_links
  (id, course_id, instructor_id, role, is_primary, order_index, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCourseInstructorLinkParams struct {
	ID           string                    `json:"id"`
	CourseID     string                    `json:"course_id"`
	InstructorID string                    `json:"instructor_id"`
	Role         CourseInstructorLinksRole `json:"role"`
	IsPrimary    bool                      `json:"is_primary"`
	OrderIndex   int32                     `json:"order_index"`
	CreatedAt    time.Time                 `json:"created_at"`
}

// Admin: insert a (course, instructor, role) link. The DB has a unique
// constraint on (course_id, instructor_id, role) so a duplicate insert
// errors — the service uses UpsertCourseInstructorLink instead.
func (q *Queries) CreateCourseInstructorLink(ctx context.Context, arg CreateCourseInstructorLinkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCourseInstructorLink,
		arg.ID,
		arg.CourseID,
		arg.InstructorID,
		arg.Role,
		arg.IsPrimary,
		arg.OrderIndex,
		arg.CreatedAt,
	)
}

const createExpertise = `-- name: CreateExpertise :execresult
INSERT INTO instructor_expertises
  (id, ` + "`" + `key` + "`" + `, label, label_en, is_active, order_index, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateExpertiseParams struct {
	ID         string         `json:"id"`
	Key        string         `json:"key"`
	Label      string         `json:"label"`
	LabelEn    sql.NullString `json:"label_en"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Admin: insert a new expertise. Caller supplies id (cuid) + timestamps.
func (q *Queries) CreateExpertise(ctx context.Context, arg CreateExpertiseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createExpertise,
		arg.ID,
		arg.Key,
		arg.Label,
		arg.LabelEn,
		arg.IsActive,
		arg.OrderIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createInstructor = `-- name: CreateInstructor :execresult
INSERT INTO instructors (
  id, slug, name, name_en, title, title_en, headline, headline_en,
  bio, bio_en, avatar_url, company, years_of_experience,
  linkedin_url, github_url, twitter_url, website_url,
  contact_email, notes, order_index, published_at,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?
)
`

type CreateInstructorParams struct {
	ID                string         `json:"id"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	NameEn            sql.NullString `json:"name_en"`
	Title             sql.NullString `json:"title"`
	TitleEn           sql.NullString `json:"title_en"`
	Headline          sql.NullString `json:"headline"`
	HeadlineEn        sql.NullString `json:"headline_en"`
	Bio               sql.NullString `json:"bio"`
	BioEn             sql.NullString `json:"bio_en"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Company           sql.NullString `json:"company"`
	YearsOfExperience sql.NullInt32  `json:"years_of_experience"`
	LinkedinUrl       sql.NullString `json:"linkedin_url"`
	GithubUrl         sql.NullString `json:"github_url"`
	TwitterUrl        sql.NullString `json:"twitter_url"`
	WebsiteUrl        sql.NullString `json:"website_url"`
	ContactEmail      sql.NullString `json:"contact_email"`
	Notes             sql.NullString `json:"notes"`
	OrderIndex        int32          `json:"order_index"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

// Admin: inserts a new instructor. Caller supplies id (cuid) + timestamps.
func (q *Queries) CreateInstructor(ctx context.Context, arg CreateInstructorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createInstructor,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.NameEn,
		arg.Title,
		arg.TitleEn,
		arg.Headline,
		arg.HeadlineEn,
		arg.Bio,
		arg.BioEn,
		arg.AvatarUrl,
		arg.Company,
		arg.YearsOfExperience,
		arg.LinkedinUrl,
		arg.GithubUrl,
		arg.TwitterUrl,
		arg.WebsiteUrl,
		arg.ContactEmail,
		arg.Notes,
		arg.OrderIndex,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteCourseInstructorLink = `-- name: DeleteCourseInstructorLink :exec
DELETE FROM course_instructor_links WHERE id = ?
`

func (q *Queries) DeleteCourseInstructorLink(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCourseInstructorLink, id)
	return err
}

const deleteCourseInstructorLinksByInstructor = `-- name: DeleteCourseInstructorLinksByInstructor :exec
DELETE FROM course_instructor_links WHERE instructor_id = ?
`

// Used by soft-delete (unlink all courses) and by SyncCourseLinks
// (delete-then-create in a tx).
func (q *Queries) DeleteCourseInstructorLinksByInstructor(ctx context.Context, instructorID string) error {
	_, err := q.db.ExecContext(ctx, deleteCourseInstructorLinksByInstructor, instructorID)
	return err
}

const deleteExpertise = `-- name: DeleteExpertise :exec
DELETE FROM instructor_expertises WHERE id = ?
`

// Admin: hard delete. instructor_expertise_links cascade-deletes
// automatically via FK.
func (q *Queries) DeleteExpertise(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteExpertise, id)
	return err
}

const getCourseInstructorLinkByID = `-- name: GetCourseInstructorLinkByID :one

SELECT id, course_id, instructor_id, role, is_primary, order_index, created_at FROM course_instructor_links WHERE id = ?
`

// ==================== course_instructor_links ====================
func (q *Queries) GetCourseInstructorLinkByID(ctx context.Context, id string) (CourseInstructorLink, error) {
	row := q.db.QueryRowContext(ctx, getCourseInstructorLinkByID, id)
	var i CourseInstructorLink
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Role,
		&i.IsPrimary,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getExpertiseByID = `-- name: GetExpertiseByID :one
SELECT id, ` + "`" + `key` + "`" + `, label, label_en, is_active, order_index, created_at, updated_at FROM instructor_expertises WHERE id = ?
`

func (q *Queries) GetExpertiseByID(ctx context.Context, id string) (InstructorExpertise, error) {
	row := q.db.QueryRowContext(ctx, getExpertiseByID, id)
	var i InstructorExpertise
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.LabelEn,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpertiseByKey = `-- name: GetExpertiseByKey :one
SELECT id, ` + "`" + `key` + "`" + `, label, label_en, is_active, order_index, created_at, updated_at
FROM instructor_expertises
WHERE ` + "`" + `key` + "`" + ` = ? LIMIT 1
`

// Uniqueness check during create. Throws 409 on duplicate key.
func (q *Queries) GetExpertiseByKey(ctx context.Context, key string) (InstructorExpertise, error) {
	row := q.db.QueryRowContext(ctx, getExpertiseByKey, key)
	var i InstructorExpertise
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.LabelEn,
		&i.IsActive,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstructorByID = `-- name: GetInstructorByID :one
SELECT id, slug, name, name_en, title, title_en, headline, headline_en, bio, bio_en, avatar_url, company, years_of_experience, linkedin_url, github_url, twitter_url, website_url, contact_email, notes, order_index, published_at, created_at, updated_at FROM instructors WHERE id = ?
`

// Admin / internal: returns the instructor regardless of status.
func (q *Queries) GetInstructorByID(ctx context.Context, id string) (Instructor, error) {
	row := q.db.QueryRowContext(ctx, getInstructorByID, id)
	var i Instructor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NameEn,
		&i.Title,
		&i.TitleEn,
		&i.Headline,
		&i.HeadlineEn,
		&i.Bio,
		&i.BioEn,
		&i.AvatarUrl,
		&i.Company,
		&i.YearsOfExperience,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.TwitterUrl,
		&i.WebsiteUrl,
		&i.ContactEmail,
		&i.Notes,
		&i.OrderIndex,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstructorBySlug = `-- name: GetInstructorBySlug :one
SELECT id, slug, name, name_en, title, title_en, headline, headline_en, bio, bio_en, avatar_url, company, years_of_experience, linkedin_url, github_url, twitter_url, website_url, contact_email, notes, order_index, published_at, created_at, updated_at FROM instructors WHERE slug = ?
`

// Admin / internal: returns the instructor regardless of status.
func (q *Queries) GetInstructorBySlug(ctx context.Context, slug string) (Instructor, error) {
	row := q.db.QueryRowContext(ctx, getInstructorBySlug, slug)
	var i Instructor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NameEn,
		&i.Title,
		&i.TitleEn,
		&i.Headline,
		&i.HeadlineEn,
		&i.Bio,
		&i.BioEn,
		&i.AvatarUrl,
		&i.Company,
		&i.YearsOfExperience,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.TwitterUrl,
		&i.WebsiteUrl,
		&i.ContactEmail,
		&i.Notes,
		&i.OrderIndex,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstructorBySlugAny = `-- name: GetInstructorBySlugAny :one
SELECT id, slug FROM instructors WHERE slug = ? LIMIT 1
`

type GetInstructorBySlugAnyRow struct {
	ID   string `json:"id"`
	Slug string `json:"slug"`
}

// For slug uniqueness check during create/update.
func (q *Queries) GetInstructorBySlugAny(ctx context.Context, slug string) (GetInstructorBySlugAnyRow, error) {
	row := q.db.QueryRowContext(ctx, getInstructorBySlugAny, slug)
	var i GetInstructorBySlugAnyRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const getPublishedInstructorBySlug = `-- name: GetPublishedInstructorBySlug :one
SELECT id, slug, name, name_en, title, title_en, headline, headline_en, bio, bio_en, avatar_url, company, years_of_experience, linkedin_url, github_url, twitter_url, website_url, contact_email, notes, order_index, published_at, created_at, updated_at FROM instructors WHERE slug = ? AND published_at IS NOT NULL
`

// Public-facing detail page: enforces published_at IS NOT NULL.
func (q *Queries) GetPublishedInstructorBySlug(ctx context.Context, slug string) (Instructor, error) {
	row := q.db.QueryRowContext(ctx, getPublishedInstructorBySlug, slug)
	var i Instructor
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.NameEn,
		&i.Title,
		&i.TitleEn,
		&i.Headline,
		&i.HeadlineEn,
		&i.Bio,
		&i.BioEn,
		&i.AvatarUrl,
		&i.Company,
		&i.YearsOfExperience,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.TwitterUrl,
		&i.WebsiteUrl,
		&i.ContactEmail,
		&i.Notes,
		&i.OrderIndex,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseInstructorLinksByInstructor = `-- name: ListCourseInstructorLinksByInstructor :many
SELECT id, course_id, instructor_id, role, is_primary, order_index, created_at FROM course_instructor_links
WHERE instructor_id = ?
ORDER BY role ASC, order_index ASC, created_at ASC
`

// Admin: list a single instructor's course assignments (instructor-centric).
func (q *Queries) ListCourseInstructorLinksByInstructor(ctx context.Context, instructorID string) ([]CourseInstructorLink, error) {
	rows, err := q.db.QueryContext(ctx, listCourseInstructorLinksByInstructor, instructorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseInstructorLink{}
	for rows.Next() {
		var i CourseInstructorLink
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.InstructorID,
			&i.Role,
			&i.IsPrimary,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseInstructorLinksByInstructorWithCourse = `-- name: ListCourseInstructorLinksByInstructorWithCourse :many
SELECT
  cil.id           AS cil_id,
  cil.course_id    AS cil_course_id,
  cil.instructor_id AS cil_instructor_id,
  cil.role         AS cil_role,
  cil.is_primary   AS cil_is_primary,
  cil.order_index  AS cil_order_index,
  cil.created_at   AS cil_created_at,
  c.title          AS course_title,
  c.status         AS course_status,
  c.thumbnail      AS course_thumbnail,
  c.level          AS course_level,
  c.cost_type      AS course_cost_type
FROM course_instructor_links cil
JOIN courses c ON c.id = cil.course_id
WHERE cil.instructor_id = ?
ORDER BY cil.role ASC, cil.order_index ASC, cil.created_at ASC
`

type ListCourseInstructorLinksByInstructorWithCourseRow struct {
	CilID           string                    `json:"cil_id"`
	CilCourseID     string                    `json:"cil_course_id"`
	CilInstructorID string                    `json:"cil_instructor_id"`
	CilRole         CourseInstructorLinksRole `json:"cil_role"`
	CilIsPrimary    bool                      `json:"cil_is_primary"`
	CilOrderIndex   int32                     `json:"cil_order_index"`
	CilCreatedAt    time.Time                 `json:"cil_created_at"`
	CourseTitle     string                    `json:"course_title"`
	CourseStatus    CoursesStatus             `json:"course_status"`
	CourseThumbnail string                    `json:"course_thumbnail"`
	CourseLevel     CoursesLevel              `json:"course_level"`
	CourseCostType  CoursesCostType           `json:"course_cost_type"`
}

// Admin: list a single instructor's course assignments with course info joined.
// The frontend can render the course title / status without a second roundtrip.
func (q *Queries) ListCourseInstructorLinksByInstructorWithCourse(ctx context.Context, instructorID string) ([]ListCourseInstructorLinksByInstructorWithCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listCourseInstructorLinksByInstructorWithCourse, instructorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseInstructorLinksByInstructorWithCourseRow{}
	for rows.Next() {
		var i ListCourseInstructorLinksByInstructorWithCourseRow
		if err := rows.Scan(
			&i.CilID,
			&i.CilCourseID,
			&i.CilInstructorID,
			&i.CilRole,
			&i.CilIsPrimary,
			&i.CilOrderIndex,
			&i.CilCreatedAt,
			&i.CourseTitle,
			&i.CourseStatus,
			&i.CourseThumbnail,
			&i.CourseLevel,
			&i.CourseCostType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpertises = `-- name: ListExpertises :many

SELECT id, ` + "`" + `key` + "`" + `, label, label_en, is_active, order_index, created_at, updated_at FROM instructor_expertises
ORDER BY is_active DESC, order_index ASC, id ASC
`

// ==================== instructor_expertises (T24) ====================
// Public + admin: all expertises ordered by NestJS
// `orderBy: [{ isActive: 'desc' }, { orderIndex: 'asc' }]`.
// Active rows first (true > false in MySQL ordering), then by manual order.
func (q *Queries) ListExpertises(ctx context.Context) ([]InstructorExpertise, error) {
	rows, err := q.db.QueryContext(ctx, listExpertises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstructorExpertise{}
	for rows.Next() {
		var i InstructorExpertise
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.LabelEn,
			&i.IsActive,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstructorOrderIndex = `-- name: SetInstructorOrderIndex :exec
UPDATE instructors SET order_index = ?, updated_at = ? WHERE id = ?
`

type SetInstructorOrderIndexParams struct {
	OrderIndex int32     `json:"order_index"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         string    `json:"id"`
}

// Admin: drag-sort. Service calls this in a transaction.
func (q *Queries) SetInstructorOrderIndex(ctx context.Context, arg SetInstructorOrderIndexParams) error {
	_, err := q.db.ExecContext(ctx, setInstructorOrderIndex, arg.OrderIndex, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteInstructor = `-- name: SoftDeleteInstructor :exec
UPDATE instructors SET published_at = NULL, updated_at = ? WHERE id = ?
`

type SoftDeleteInstructorParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

// Admin: sets published_at = NULL (前台 404, 课程卡 fallback). Keeps the
// row for audit + historical enrollments. The service layer unlinks
// all course_instructor_links in the same transaction.
func (q *Queries) SoftDeleteInstructor(ctx context.Context, arg SoftDeleteInstructorParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteInstructor, arg.UpdatedAt, arg.ID)
	return err
}

const updateExpertise = `-- name: UpdateExpertise :exec
UPDATE instructor_expertises
SET ` + "`" + `key` + "`" + ` = ?, label = ?, label_en = ?, is_active = ?,
    order_index = ?, updated_at = ?
WHERE id = ?
`

type UpdateExpertiseParams struct {
	Key        string         `json:"key"`
	Label      string         `json:"label"`
	LabelEn    sql.NullString `json:"label_en"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ID         string         `json:"id"`
}

// Admin: full update (service layer reads first + merges, same pattern
// as the instructors update).
func (q *Queries) UpdateExpertise(ctx context.Context, arg UpdateExpertiseParams) error {
	_, err := q.db.ExecContext(ctx, updateExpertise,
		arg.Key,
		arg.Label,
		arg.LabelEn,
		arg.IsActive,
		arg.OrderIndex,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateInstructor = `-- name: UpdateInstructor :exec
UPDATE instructors
SET slug = ?, name = ?, name_en = ?, title = ?, title_en = ?,
    headline = ?, headline_en = ?, bio = ?, bio_en = ?,
    avatar_url = ?, company = ?, years_of_experience = ?,
    linkedin_url = ?, github_url = ?, twitter_url = ?, website_url = ?,
    contact_email = ?, notes = ?, order_index = ?,
    published_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateInstructorParams struct {
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	NameEn            sql.NullString `json:"name_en"`
	Title             sql.NullString `json:"title"`
	TitleEn           sql.NullString `json:"title_en"`
	Headline          sql.NullString `json:"headline"`
	HeadlineEn        sql.NullString `json:"headline_en"`
	Bio               sql.NullString `json:"bio"`
	BioEn             sql.NullString `json:"bio_en"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Company           sql.NullString `json:"company"`
	YearsOfExperience sql.NullInt32  `json:"years_of_experience"`
	LinkedinUrl       sql.NullString `json:"linkedin_url"`
	GithubUrl         sql.NullString `json:"github_url"`
	TwitterUrl        sql.NullString `json:"twitter_url"`
	WebsiteUrl        sql.NullString `json:"website_url"`
	ContactEmail      sql.NullString `json:"contact_email"`
	Notes             sql.NullString `json:"notes"`
	OrderIndex        int32          `json:"order_index"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ID                string         `json:"id"`
}

// Admin: full update. Service layer reads the current row first and
// passes the merged patch in (idempotent re-write of unchanged fields).
func (q *Queries) UpdateInstructor(ctx context.Context, arg UpdateInstructorParams) error {
	_, err := q.db.ExecContext(ctx, updateInstructor,
		arg.Slug,
		arg.Name,
		arg.NameEn,
		arg.Title,
		arg.TitleEn,
		arg.Headline,
		arg.HeadlineEn,
		arg.Bio,
		arg.BioEn,
		arg.AvatarUrl,
		arg.Company,
		arg.YearsOfExperience,
		arg.LinkedinUrl,
		arg.GithubUrl,
		arg.TwitterUrl,
		arg.WebsiteUrl,
		arg.ContactEmail,
		arg.Notes,
		arg.OrderIndex,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertCourseInstructorLink = `-- name: UpsertCourseInstructorLink :execresult
INSERT INTO course_instructor_links
  (id, course_id, instructor_id, role, is_primary, order_index, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  is_primary = VALUES(is_primary),
  order_index = VALUES(order_index)
`

type UpsertCourseInstructorLinkParams struct {
	ID           string                    `json:"id"`
	CourseID     string                    `json:"course_id"`
	InstructorID string                    `json:"instructor_id"`
	Role         CourseInstructorLinksRole `json:"role"`
	IsPrimary    bool                      `json:"is_primary"`
	OrderIndex   int32                     `json:"order_index"`
	CreatedAt    time.Time                 `json:"created_at"`
}

// Admin: idempotent link insert. If a row with the same
// (course_id, instructor_id, role) exists, refresh its role / primary /
// order fields. NestJS uses prisma.upsert with the same composite key.
func (q *Queries) UpsertCourseInstructorLink(ctx context.Context, arg UpsertCourseInstructorLinkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertCourseInstructorLink,
		arg.ID,
		arg.CourseID,
		arg.InstructorID,
		arg.Role,
		arg.IsPrimary,
		arg.OrderIndex,
		arg.CreatedAt,
	)
}
