// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_events.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createLearningEvent = `-- name: CreateLearningEvent :execresult
INSERT INTO learning_events
  (id, user_id, lesson_id, event_type, position_sec, duration_ms, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateLearningEventParams struct {
	ID          string                  `json:"id"`
	UserID      string                  `json:"user_id"`
	LessonID    sql.NullString          `json:"lesson_id"`
	EventType   LearningEventsEventType `json:"event_type"`
	PositionSec sql.NullInt32           `json:"position_sec"`
	DurationMs  sql.NullInt32           `json:"duration_ms"`
	Metadata    json.RawMessage         `json:"metadata"`
}

func (q *Queries) CreateLearningEvent(ctx context.Context, arg CreateLearningEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLearningEvent,
		arg.ID,
		arg.UserID,
		arg.LessonID,
		arg.EventType,
		arg.PositionSec,
		arg.DurationMs,
		arg.Metadata,
	)
}

const listLearningEventsByLesson = `-- name: ListLearningEventsByLesson :many
SELECT id, user_id, lesson_id, event_type, position_sec, duration_ms,
       IFNULL(metadata, JSON_OBJECT()) AS metadata, created_at
FROM learning_events
WHERE lesson_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListLearningEventsByLessonParams struct {
	LessonID sql.NullString `json:"lesson_id"`
	Limit    int32          `json:"limit"`
}

type ListLearningEventsByLessonRow struct {
	ID          string                  `json:"id"`
	UserID      string                  `json:"user_id"`
	LessonID    sql.NullString          `json:"lesson_id"`
	EventType   LearningEventsEventType `json:"event_type"`
	PositionSec sql.NullInt32           `json:"position_sec"`
	DurationMs  sql.NullInt32           `json:"duration_ms"`
	Metadata    interface{}             `json:"metadata"`
	CreatedAt   time.Time               `json:"created_at"`
}

// All events for a lesson, newest first. Admin/instructor only.
func (q *Queries) ListLearningEventsByLesson(ctx context.Context, arg ListLearningEventsByLessonParams) ([]ListLearningEventsByLessonRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningEventsByLesson, arg.LessonID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningEventsByLessonRow{}
	for rows.Next() {
		var i ListLearningEventsByLessonRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.EventType,
			&i.PositionSec,
			&i.DurationMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningEventsByUser = `-- name: ListLearningEventsByUser :many
SELECT id, user_id, lesson_id, event_type, position_sec, duration_ms,
       IFNULL(metadata, JSON_OBJECT()) AS metadata, created_at
FROM learning_events
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListLearningEventsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type ListLearningEventsByUserRow struct {
	ID          string                  `json:"id"`
	UserID      string                  `json:"user_id"`
	LessonID    sql.NullString          `json:"lesson_id"`
	EventType   LearningEventsEventType `json:"event_type"`
	PositionSec sql.NullInt32           `json:"position_sec"`
	DurationMs  sql.NullInt32           `json:"duration_ms"`
	Metadata    interface{}             `json:"metadata"`
	CreatedAt   time.Time               `json:"created_at"`
}

// The user's most recent N events, newest first. Default 50, max 100.
// IFNULL(metadata, JSON_OBJECT()) prevents the *json.RawMessage
// scan target from failing on NULL.
func (q *Queries) ListLearningEventsByUser(ctx context.Context, arg ListLearningEventsByUserParams) ([]ListLearningEventsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningEventsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningEventsByUserRow{}
	for rows.Next() {
		var i ListLearningEventsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.EventType,
			&i.PositionSec,
			&i.DurationMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
