// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createLesson = `-- name: CreateLesson :execresult
INSERT INTO lessons
  (id, chapter_id, title, description, video_url, video_duration, order_index, is_preview, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLessonParams struct {
	ID            string         `json:"id"`
	ChapterID     string         `json:"chapter_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	VideoUrl      sql.NullString `json:"video_url"`
	VideoDuration sql.NullInt32  `json:"video_duration"`
	OrderIndex    int32          `json:"order_index"`
	IsPreview     bool           `json:"is_preview"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLesson,
		arg.ID,
		arg.ChapterID,
		arg.Title,
		arg.Description,
		arg.VideoUrl,
		arg.VideoDuration,
		arg.OrderIndex,
		arg.IsPreview,
		arg.CreatedAt,
	)
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, chapter_id, title, description, video_url, video_duration,
       order_index, is_preview, created_at, deleted_at
FROM lessons
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetLessonByID(ctx context.Context, id string) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Title,
		&i.Description,
		&i.VideoUrl,
		&i.VideoDuration,
		&i.OrderIndex,
		&i.IsPreview,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lessonsByIDs = `-- name: LessonsByIDs :many
SELECT id, chapter_id FROM lessons WHERE id IN (/*SLICE:ids*/?)
`

type LessonsByIDsRow struct {
	ID        string `json:"id"`
	ChapterID string `json:"chapter_id"`
}

// Used by reorder to fetch ownership (chapterId) for each lesson.
func (q *Queries) LessonsByIDs(ctx context.Context, ids []string) ([]LessonsByIDsRow, error) {
	query := lessonsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonsByIDsRow{}
	for rows.Next() {
		var i LessonsByIDsRow
		if err := rows.Scan(&i.ID, &i.ChapterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByChapter = `-- name: ListLessonsByChapter :many
SELECT id, chapter_id, title, description, video_url, video_duration,
       order_index, is_preview, created_at, deleted_at
FROM lessons
WHERE chapter_id = ? AND deleted_at IS NULL
ORDER BY order_index ASC
`

func (q *Queries) ListLessonsByChapter(ctx context.Context, chapterID string) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, listLessonsByChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Title,
			&i.Description,
			&i.VideoUrl,
			&i.VideoDuration,
			&i.OrderIndex,
			&i.IsPreview,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxLessonOrderIndex = `-- name: MaxLessonOrderIndex :one
SELECT COALESCE(MAX(order_index), -1) AS max_idx
FROM lessons WHERE chapter_id = ? AND deleted_at IS NULL
`

func (q *Queries) MaxLessonOrderIndex(ctx context.Context, chapterID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxLessonOrderIndex, chapterID)
	var max_idx interface{}
	err := row.Scan(&max_idx)
	return max_idx, err
}

const softDeleteLesson = `-- name: SoftDeleteLesson :exec
UPDATE lessons
SET deleted_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteLessonParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteLesson(ctx context.Context, arg SoftDeleteLessonParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteLesson, arg.DeletedAt, arg.ID)
	return err
}

const softDeleteLessonsByChapter = `-- name: SoftDeleteLessonsByChapter :execrows
UPDATE lessons
SET deleted_at = ?
WHERE chapter_id = ? AND deleted_at IS NULL
`

type SoftDeleteLessonsByChapterParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ChapterID string       `json:"chapter_id"`
}

// Cascade soft-delete for chapter delete. Returns count.
func (q *Queries) SoftDeleteLessonsByChapter(ctx context.Context, arg SoftDeleteLessonsByChapterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteLessonsByChapter, arg.DeletedAt, arg.ChapterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLesson = `-- name: UpdateLesson :exec
UPDATE lessons
SET title = ?, description = ?, video_url = ?, video_duration = ?,
    order_index = ?, is_preview = ?
WHERE id = ?
`

type UpdateLessonParams struct {
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	VideoUrl      sql.NullString `json:"video_url"`
	VideoDuration sql.NullInt32  `json:"video_duration"`
	OrderIndex    int32          `json:"order_index"`
	IsPreview     bool           `json:"is_preview"`
	ID            string         `json:"id"`
}

// Partial update — caller shapes the patch (UpdateLessonPatch).
func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) error {
	_, err := q.db.ExecContext(ctx, updateLesson,
		arg.Title,
		arg.Description,
		arg.VideoUrl,
		arg.VideoDuration,
		arg.OrderIndex,
		arg.IsPreview,
		arg.ID,
	)
	return err
}
