// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type AppSettingsScope string

const (
	AppSettingsScopeGlobal AppSettingsScope = "global"
	AppSettingsScopePage   AppSettingsScope = "page"
	AppSettingsScopeUser   AppSettingsScope = "user"
)

func (e *AppSettingsScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppSettingsScope(s)
	case string:
		*e = AppSettingsScope(s)
	default:
		return fmt.Errorf("unsupported scan type for AppSettingsScope: %T", src)
	}
	return nil
}

type NullAppSettingsScope struct {
	AppSettingsScope AppSettingsScope `json:"app_settings_scope"`
	Valid            bool             `json:"valid"` // Valid is true if AppSettingsScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppSettingsScope) Scan(value interface{}) error {
	if value == nil {
		ns.AppSettingsScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppSettingsScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppSettingsScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppSettingsScope), nil
}

func (e AppSettingsScope) Valid() bool {
	switch e {
	case AppSettingsScopeGlobal,
		AppSettingsScopePage,
		AppSettingsScopeUser:
		return true
	}
	return false
}

type BadgesCriteriaType string

const (
	BadgesCriteriaTypeCourseCompleted   BadgesCriteriaType = "course_completed"
	BadgesCriteriaTypeLessonsCompleted  BadgesCriteriaType = "lessons_completed"
	BadgesCriteriaTypeStreakDays        BadgesCriteriaType = "streak_days"
	BadgesCriteriaTypeFirstEnrollment   BadgesCriteriaType = "first_enrollment"
	BadgesCriteriaTypePracticeCompleted BadgesCriteriaType = "practice_completed"
	BadgesCriteriaTypePointsReached     BadgesCriteriaType = "points_reached"
	BadgesCriteriaTypeCourseSpecific    BadgesCriteriaType = "course_specific"
)

func (e *BadgesCriteriaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BadgesCriteriaType(s)
	case string:
		*e = BadgesCriteriaType(s)
	default:
		return fmt.Errorf("unsupported scan type for BadgesCriteriaType: %T", src)
	}
	return nil
}

type NullBadgesCriteriaType struct {
	BadgesCriteriaType BadgesCriteriaType `json:"badges_criteria_type"`
	Valid              bool               `json:"valid"` // Valid is true if BadgesCriteriaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBadgesCriteriaType) Scan(value interface{}) error {
	if value == nil {
		ns.BadgesCriteriaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BadgesCriteriaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBadgesCriteriaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BadgesCriteriaType), nil
}

func (e BadgesCriteriaType) Valid() bool {
	switch e {
	case BadgesCriteriaTypeCourseCompleted,
		BadgesCriteriaTypeLessonsCompleted,
		BadgesCriteriaTypeStreakDays,
		BadgesCriteriaTypeFirstEnrollment,
		BadgesCriteriaTypePracticeCompleted,
		BadgesCriteriaTypePointsReached,
		BadgesCriteriaTypeCourseSpecific:
		return true
	}
	return false
}

type CertificatesType string

const (
	CertificatesTypeCourse    CertificatesType = "course"
	CertificatesTypeDegree    CertificatesType = "degree"
	CertificatesTypeHackathon CertificatesType = "hackathon"
)

func (e *CertificatesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CertificatesType(s)
	case string:
		*e = CertificatesType(s)
	default:
		return fmt.Errorf("unsupported scan type for CertificatesType: %T", src)
	}
	return nil
}

type NullCertificatesType struct {
	CertificatesType CertificatesType `json:"certificates_type"`
	Valid            bool             `json:"valid"` // Valid is true if CertificatesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCertificatesType) Scan(value interface{}) error {
	if value == nil {
		ns.CertificatesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CertificatesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCertificatesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CertificatesType), nil
}

func (e CertificatesType) Valid() bool {
	switch e {
	case CertificatesTypeCourse,
		CertificatesTypeDegree,
		CertificatesTypeHackathon:
		return true
	}
	return false
}

type ChatMessagesRole string

const (
	ChatMessagesRoleUser      ChatMessagesRole = "user"
	ChatMessagesRoleAssistant ChatMessagesRole = "assistant"
	ChatMessagesRoleSystem    ChatMessagesRole = "system"
)

func (e *ChatMessagesRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatMessagesRole(s)
	case string:
		*e = ChatMessagesRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatMessagesRole: %T", src)
	}
	return nil
}

type NullChatMessagesRole struct {
	ChatMessagesRole ChatMessagesRole `json:"chat_messages_role"`
	Valid            bool             `json:"valid"` // Valid is true if ChatMessagesRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatMessagesRole) Scan(value interface{}) error {
	if value == nil {
		ns.ChatMessagesRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatMessagesRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatMessagesRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatMessagesRole), nil
}

func (e ChatMessagesRole) Valid() bool {
	switch e {
	case ChatMessagesRoleUser,
		ChatMessagesRoleAssistant,
		ChatMessagesRoleSystem:
		return true
	}
	return false
}

type CourseInstructorLinksRole string

const (
	CourseInstructorLinksRoleInstructor CourseInstructorLinksRole = "instructor"
	CourseInstructorLinksRoleMentor     CourseInstructorLinksRole = "mentor"
)

func (e *CourseInstructorLinksRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseInstructorLinksRole(s)
	case string:
		*e = CourseInstructorLinksRole(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseInstructorLinksRole: %T", src)
	}
	return nil
}

type NullCourseInstructorLinksRole struct {
	CourseInstructorLinksRole CourseInstructorLinksRole `json:"course_instructor_links_role"`
	Valid                     bool                      `json:"valid"` // Valid is true if CourseInstructorLinksRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseInstructorLinksRole) Scan(value interface{}) error {
	if value == nil {
		ns.CourseInstructorLinksRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseInstructorLinksRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseInstructorLinksRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseInstructorLinksRole), nil
}

func (e CourseInstructorLinksRole) Valid() bool {
	switch e {
	case CourseInstructorLinksRoleInstructor,
		CourseInstructorLinksRoleMentor:
		return true
	}
	return false
}

type CoursesCostType string

const (
	CoursesCostTypeFree    CoursesCostType = "free"
	CoursesCostTypePaid    CoursesCostType = "paid"
	CoursesCostTypeCharity CoursesCostType = "charity"
)

func (e *CoursesCostType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoursesCostType(s)
	case string:
		*e = CoursesCostType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoursesCostType: %T", src)
	}
	return nil
}

type NullCoursesCostType struct {
	CoursesCostType CoursesCostType `json:"courses_cost_type"`
	Valid           bool            `json:"valid"` // Valid is true if CoursesCostType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoursesCostType) Scan(value interface{}) error {
	if value == nil {
		ns.CoursesCostType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoursesCostType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoursesCostType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoursesCostType), nil
}

func (e CoursesCostType) Valid() bool {
	switch e {
	case CoursesCostTypeFree,
		CoursesCostTypePaid,
		CoursesCostTypeCharity:
		return true
	}
	return false
}

type CoursesCourseType string

const (
	CoursesCourseTypeOwn        CoursesCourseType = "own"
	CoursesCourseTypePartner    CoursesCourseType = "partner"
	CoursesCourseTypePublic     CoursesCourseType = "public"
	CoursesCourseTypeThirdParty CoursesCourseType = "third_party"
)

func (e *CoursesCourseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoursesCourseType(s)
	case string:
		*e = CoursesCourseType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoursesCourseType: %T", src)
	}
	return nil
}

type NullCoursesCourseType struct {
	CoursesCourseType CoursesCourseType `json:"courses_course_type"`
	Valid             bool              `json:"valid"` // Valid is true if CoursesCourseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoursesCourseType) Scan(value interface{}) error {
	if value == nil {
		ns.CoursesCourseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoursesCourseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoursesCourseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoursesCourseType), nil
}

func (e CoursesCourseType) Valid() bool {
	switch e {
	case CoursesCourseTypeOwn,
		CoursesCourseTypePartner,
		CoursesCourseTypePublic,
		CoursesCourseTypeThirdParty:
		return true
	}
	return false
}

type CoursesLevel string

const (
	CoursesLevelBeginner     CoursesLevel = "Beginner"
	CoursesLevelIntermediate CoursesLevel = "Intermediate"
	CoursesLevelAdvanced     CoursesLevel = "Advanced"
	CoursesLevelExpert       CoursesLevel = "Expert"
)

func (e *CoursesLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoursesLevel(s)
	case string:
		*e = CoursesLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for CoursesLevel: %T", src)
	}
	return nil
}

type NullCoursesLevel struct {
	CoursesLevel CoursesLevel `json:"courses_level"`
	Valid        bool         `json:"valid"` // Valid is true if CoursesLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoursesLevel) Scan(value interface{}) error {
	if value == nil {
		ns.CoursesLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoursesLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoursesLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoursesLevel), nil
}

func (e CoursesLevel) Valid() bool {
	switch e {
	case CoursesLevelBeginner,
		CoursesLevelIntermediate,
		CoursesLevelAdvanced,
		CoursesLevelExpert:
		return true
	}
	return false
}

type CoursesStatus string

const (
	CoursesStatusDraft     CoursesStatus = "draft"
	CoursesStatusPublished CoursesStatus = "published"
	CoursesStatusArchived  CoursesStatus = "archived"
)

func (e *CoursesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoursesStatus(s)
	case string:
		*e = CoursesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoursesStatus: %T", src)
	}
	return nil
}

type NullCoursesStatus struct {
	CoursesStatus CoursesStatus `json:"courses_status"`
	Valid         bool          `json:"valid"` // Valid is true if CoursesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoursesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoursesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoursesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoursesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoursesStatus), nil
}

func (e CoursesStatus) Valid() bool {
	switch e {
	case CoursesStatusDraft,
		CoursesStatusPublished,
		CoursesStatusArchived:
		return true
	}
	return false
}

type DateFormatTemplatesScope string

const (
	DateFormatTemplatesScopeGlobal                  DateFormatTemplatesScope = "global"
	DateFormatTemplatesScopeLocale                  DateFormatTemplatesScope = "locale"
	DateFormatTemplatesScopeAdminUsersList          DateFormatTemplatesScope = "admin_users_list"
	DateFormatTemplatesScopeCommonDate              DateFormatTemplatesScope = "common_date"
	DateFormatTemplatesScopeDashboardLessonDuration DateFormatTemplatesScope = "dashboard_lesson_duration"
)

func (e *DateFormatTemplatesScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DateFormatTemplatesScope(s)
	case string:
		*e = DateFormatTemplatesScope(s)
	default:
		return fmt.Errorf("unsupported scan type for DateFormatTemplatesScope: %T", src)
	}
	return nil
}

type NullDateFormatTemplatesScope struct {
	DateFormatTemplatesScope DateFormatTemplatesScope `json:"date_format_templates_scope"`
	Valid                    bool                     `json:"valid"` // Valid is true if DateFormatTemplatesScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDateFormatTemplatesScope) Scan(value interface{}) error {
	if value == nil {
		ns.DateFormatTemplatesScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DateFormatTemplatesScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDateFormatTemplatesScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DateFormatTemplatesScope), nil
}

func (e DateFormatTemplatesScope) Valid() bool {
	switch e {
	case DateFormatTemplatesScopeGlobal,
		DateFormatTemplatesScopeLocale,
		DateFormatTemplatesScopeAdminUsersList,
		DateFormatTemplatesScopeCommonDate,
		DateFormatTemplatesScopeDashboardLessonDuration:
		return true
	}
	return false
}

type EnrollmentsSource string

const (
	EnrollmentsSourceDirect    EnrollmentsSource = "direct"
	EnrollmentsSourceDegree    EnrollmentsSource = "degree"
	EnrollmentsSourceHackathon EnrollmentsSource = "hackathon"
	EnrollmentsSourcePromotion EnrollmentsSource = "promotion"
	EnrollmentsSourceOrder     EnrollmentsSource = "order"
)

func (e *EnrollmentsSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentsSource(s)
	case string:
		*e = EnrollmentsSource(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentsSource: %T", src)
	}
	return nil
}

type NullEnrollmentsSource struct {
	EnrollmentsSource EnrollmentsSource `json:"enrollments_source"`
	Valid             bool              `json:"valid"` // Valid is true if EnrollmentsSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnrollmentsSource) Scan(value interface{}) error {
	if value == nil {
		ns.EnrollmentsSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnrollmentsSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnrollmentsSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnrollmentsSource), nil
}

func (e EnrollmentsSource) Valid() bool {
	switch e {
	case EnrollmentsSourceDirect,
		EnrollmentsSourceDegree,
		EnrollmentsSourceHackathon,
		EnrollmentsSourcePromotion,
		EnrollmentsSourceOrder:
		return true
	}
	return false
}

type EnterpriseInquiriesStatus string

const (
	EnterpriseInquiriesStatusPending   EnterpriseInquiriesStatus = "pending"
	EnterpriseInquiriesStatusContacted EnterpriseInquiriesStatus = "contacted"
	EnterpriseInquiriesStatusQualified EnterpriseInquiriesStatus = "qualified"
	EnterpriseInquiriesStatusClosed    EnterpriseInquiriesStatus = "closed"
	EnterpriseInquiriesStatusArchived  EnterpriseInquiriesStatus = "archived"
)

func (e *EnterpriseInquiriesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnterpriseInquiriesStatus(s)
	case string:
		*e = EnterpriseInquiriesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnterpriseInquiriesStatus: %T", src)
	}
	return nil
}

type NullEnterpriseInquiriesStatus struct {
	EnterpriseInquiriesStatus EnterpriseInquiriesStatus `json:"enterprise_inquiries_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if EnterpriseInquiriesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnterpriseInquiriesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnterpriseInquiriesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnterpriseInquiriesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnterpriseInquiriesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnterpriseInquiriesStatus), nil
}

func (e EnterpriseInquiriesStatus) Valid() bool {
	switch e {
	case EnterpriseInquiriesStatusPending,
		EnterpriseInquiriesStatusContacted,
		EnterpriseInquiriesStatusQualified,
		EnterpriseInquiriesStatusClosed,
		EnterpriseInquiriesStatusArchived:
		return true
	}
	return false
}

type HackathonRegistrationsStatus string

const (
	HackathonRegistrationsStatusRegistered HackathonRegistrationsStatus = "registered"
	HackathonRegistrationsStatusCancelled  HackathonRegistrationsStatus = "cancelled"
	HackathonRegistrationsStatusCheckedIn  HackathonRegistrationsStatus = "checked_in"
)

func (e *HackathonRegistrationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HackathonRegistrationsStatus(s)
	case string:
		*e = HackathonRegistrationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HackathonRegistrationsStatus: %T", src)
	}
	return nil
}

type NullHackathonRegistrationsStatus struct {
	HackathonRegistrationsStatus HackathonRegistrationsStatus `json:"hackathon_registrations_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if HackathonRegistrationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHackathonRegistrationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HackathonRegistrationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HackathonRegistrationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHackathonRegistrationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HackathonRegistrationsStatus), nil
}

func (e HackathonRegistrationsStatus) Valid() bool {
	switch e {
	case HackathonRegistrationsStatusRegistered,
		HackathonRegistrationsStatusCancelled,
		HackathonRegistrationsStatusCheckedIn:
		return true
	}
	return false
}

type HackathonsStatus string

const (
	HackathonsStatusUpcoming  HackathonsStatus = "upcoming"
	HackathonsStatusActive    HackathonsStatus = "active"
	HackathonsStatusJudging   HackathonsStatus = "judging"
	HackathonsStatusFinished  HackathonsStatus = "finished"
	HackathonsStatusCancelled HackathonsStatus = "cancelled"
)

func (e *HackathonsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HackathonsStatus(s)
	case string:
		*e = HackathonsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HackathonsStatus: %T", src)
	}
	return nil
}

type NullHackathonsStatus struct {
	HackathonsStatus HackathonsStatus `json:"hackathons_status"`
	Valid            bool             `json:"valid"` // Valid is true if HackathonsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHackathonsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HackathonsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HackathonsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHackathonsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HackathonsStatus), nil
}

func (e HackathonsStatus) Valid() bool {
	switch e {
	case HackathonsStatusUpcoming,
		HackathonsStatusActive,
		HackathonsStatusJudging,
		HackathonsStatusFinished,
		HackathonsStatusCancelled:
		return true
	}
	return false
}

type HotKeywordsScope string

const (
	HotKeywordsScopeCourses HotKeywordsScope = "courses"
	HotKeywordsScopeHome    HotKeywordsScope = "home"
	HotKeywordsScopeSearch  HotKeywordsScope = "search"
	HotKeywordsScopeAll     HotKeywordsScope = "all"
)

func (e *HotKeywordsScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HotKeywordsScope(s)
	case string:
		*e = HotKeywordsScope(s)
	default:
		return fmt.Errorf("unsupported scan type for HotKeywordsScope: %T", src)
	}
	return nil
}

type NullHotKeywordsScope struct {
	HotKeywordsScope HotKeywordsScope `json:"hot_keywords_scope"`
	Valid            bool             `json:"valid"` // Valid is true if HotKeywordsScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHotKeywordsScope) Scan(value interface{}) error {
	if value == nil {
		ns.HotKeywordsScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HotKeywordsScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHotKeywordsScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HotKeywordsScope), nil
}

func (e HotKeywordsScope) Valid() bool {
	switch e {
	case HotKeywordsScopeCourses,
		HotKeywordsScopeHome,
		HotKeywordsScopeSearch,
		HotKeywordsScopeAll:
		return true
	}
	return false
}

type I18nMessagesCategory string

const (
	I18nMessagesCategoryCommon     I18nMessagesCategory = "common"
	I18nMessagesCategoryAuth       I18nMessagesCategory = "auth"
	I18nMessagesCategoryCourse     I18nMessagesCategory = "course"
	I18nMessagesCategoryHackathon  I18nMessagesCategory = "hackathon"
	I18nMessagesCategoryDegree     I18nMessagesCategory = "degree"
	I18nMessagesCategoryEnterprise I18nMessagesCategory = "enterprise"
	I18nMessagesCategoryAdmin      I18nMessagesCategory = "admin"
)

func (e *I18nMessagesCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = I18nMessagesCategory(s)
	case string:
		*e = I18nMessagesCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for I18nMessagesCategory: %T", src)
	}
	return nil
}

type NullI18nMessagesCategory struct {
	I18nMessagesCategory I18nMessagesCategory `json:"i18n_messages_category"`
	Valid                bool                 `json:"valid"` // Valid is true if I18nMessagesCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullI18nMessagesCategory) Scan(value interface{}) error {
	if value == nil {
		ns.I18nMessagesCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.I18nMessagesCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullI18nMessagesCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.I18nMessagesCategory), nil
}

func (e I18nMessagesCategory) Valid() bool {
	switch e {
	case I18nMessagesCategoryCommon,
		I18nMessagesCategoryAuth,
		I18nMessagesCategoryCourse,
		I18nMessagesCategoryHackathon,
		I18nMessagesCategoryDegree,
		I18nMessagesCategoryEnterprise,
		I18nMessagesCategoryAdmin:
		return true
	}
	return false
}

type LearningEventsEventType string

const (
	LearningEventsEventTypePlay     LearningEventsEventType = "play"
	LearningEventsEventTypePause    LearningEventsEventType = "pause"
	LearningEventsEventTypeSeek     LearningEventsEventType = "seek"
	LearningEventsEventTypeComplete LearningEventsEventType = "complete"
	LearningEventsEventTypeReplay   LearningEventsEventType = "replay"
	LearningEventsEventTypeSkip     LearningEventsEventType = "skip"
	LearningEventsEventTypeNote     LearningEventsEventType = "note"
)

func (e *LearningEventsEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LearningEventsEventType(s)
	case string:
		*e = LearningEventsEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for LearningEventsEventType: %T", src)
	}
	return nil
}

type NullLearningEventsEventType struct {
	LearningEventsEventType LearningEventsEventType `json:"learning_events_event_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if LearningEventsEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLearningEventsEventType) Scan(value interface{}) error {
	if value == nil {
		ns.LearningEventsEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LearningEventsEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLearningEventsEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LearningEventsEventType), nil
}

func (e LearningEventsEventType) Valid() bool {
	switch e {
	case LearningEventsEventTypePlay,
		LearningEventsEventTypePause,
		LearningEventsEventTypeSeek,
		LearningEventsEventTypeComplete,
		LearningEventsEventTypeReplay,
		LearningEventsEventTypeSkip,
		LearningEventsEventTypeNote:
		return true
	}
	return false
}

type NanoDegreesCostType string

const (
	NanoDegreesCostTypeFree    NanoDegreesCostType = "free"
	NanoDegreesCostTypePaid    NanoDegreesCostType = "paid"
	NanoDegreesCostTypeCharity NanoDegreesCostType = "charity"
)

func (e *NanoDegreesCostType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NanoDegreesCostType(s)
	case string:
		*e = NanoDegreesCostType(s)
	default:
		return fmt.Errorf("unsupported scan type for NanoDegreesCostType: %T", src)
	}
	return nil
}

type NullNanoDegreesCostType struct {
	NanoDegreesCostType NanoDegreesCostType `json:"nano_degrees_cost_type"`
	Valid               bool                `json:"valid"` // Valid is true if NanoDegreesCostType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNanoDegreesCostType) Scan(value interface{}) error {
	if value == nil {
		ns.NanoDegreesCostType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NanoDegreesCostType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNanoDegreesCostType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NanoDegreesCostType), nil
}

func (e NanoDegreesCostType) Valid() bool {
	switch e {
	case NanoDegreesCostTypeFree,
		NanoDegreesCostTypePaid,
		NanoDegreesCostTypeCharity:
		return true
	}
	return false
}

type NanoDegreesStatus string

const (
	NanoDegreesStatusDraft     NanoDegreesStatus = "draft"
	NanoDegreesStatusPublished NanoDegreesStatus = "published"
	NanoDegreesStatusArchived  NanoDegreesStatus = "archived"
)

func (e *NanoDegreesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NanoDegreesStatus(s)
	case string:
		*e = NanoDegreesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NanoDegreesStatus: %T", src)
	}
	return nil
}

type NullNanoDegreesStatus struct {
	NanoDegreesStatus NanoDegreesStatus `json:"nano_degrees_status"`
	Valid             bool              `json:"valid"` // Valid is true if NanoDegreesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNanoDegreesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NanoDegreesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NanoDegreesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNanoDegreesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NanoDegreesStatus), nil
}

func (e NanoDegreesStatus) Valid() bool {
	switch e {
	case NanoDegreesStatusDraft,
		NanoDegreesStatusPublished,
		NanoDegreesStatusArchived:
		return true
	}
	return false
}

type NotificationsType string

const (
	NotificationsTypeAnnouncement NotificationsType = "announcement"
	NotificationsTypeComment      NotificationsType = "comment"
	NotificationsTypeHackathon    NotificationsType = "hackathon"
	NotificationsTypeOrder        NotificationsType = "order"
)

func (e *NotificationsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationsType(s)
	case string:
		*e = NotificationsType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationsType: %T", src)
	}
	return nil
}

type NullNotificationsType struct {
	NotificationsType NotificationsType `json:"notifications_type"`
	Valid             bool              `json:"valid"` // Valid is true if NotificationsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationsType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationsType), nil
}

func (e NotificationsType) Valid() bool {
	switch e {
	case NotificationsTypeAnnouncement,
		NotificationsTypeComment,
		NotificationsTypeHackathon,
		NotificationsTypeOrder:
		return true
	}
	return false
}

type OrdersPaymentMethod string

const (
	OrdersPaymentMethodWechat OrdersPaymentMethod = "wechat"
	OrdersPaymentMethodAlipay OrdersPaymentMethod = "alipay"
	OrdersPaymentMethodStripe OrdersPaymentMethod = "stripe"
)

func (e *OrdersPaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersPaymentMethod(s)
	case string:
		*e = OrdersPaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersPaymentMethod: %T", src)
	}
	return nil
}

type NullOrdersPaymentMethod struct {
	OrdersPaymentMethod OrdersPaymentMethod `json:"orders_payment_method"`
	Valid               bool                `json:"valid"` // Valid is true if OrdersPaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersPaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersPaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersPaymentMethod), nil
}

func (e OrdersPaymentMethod) Valid() bool {
	switch e {
	case OrdersPaymentMethodWechat,
		OrdersPaymentMethodAlipay,
		OrdersPaymentMethodStripe:
		return true
	}
	return false
}

type OrdersStatus string

const (
	OrdersStatusPending  OrdersStatus = "pending"
	OrdersStatusPaid     OrdersStatus = "paid"
	OrdersStatusFailed   OrdersStatus = "failed"
	OrdersStatusExpired  OrdersStatus = "expired"
	OrdersStatusRefunded OrdersStatus = "refunded"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus `json:"orders_status"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

func (e OrdersStatus) Valid() bool {
	switch e {
	case OrdersStatusPending,
		OrdersStatusPaid,
		OrdersStatusFailed,
		OrdersStatusExpired,
		OrdersStatusRefunded:
		return true
	}
	return false
}

type OrdersType string

const (
	OrdersTypeCourse OrdersType = "course"
	OrdersTypeDegree OrdersType = "degree"
)

func (e *OrdersType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersType(s)
	case string:
		*e = OrdersType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersType: %T", src)
	}
	return nil
}

type NullOrdersType struct {
	OrdersType OrdersType `json:"orders_type"`
	Valid      bool       `json:"valid"` // Valid is true if OrdersType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersType) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersType), nil
}

func (e OrdersType) Valid() bool {
	switch e {
	case OrdersTypeCourse,
		OrdersTypeDegree:
		return true
	}
	return false
}

type PointTransactionsRefType string

const (
	PointTransactionsRefTypeLesson     PointTransactionsRefType = "lesson"
	PointTransactionsRefTypePractice   PointTransactionsRefType = "practice"
	PointTransactionsRefTypeBadge      PointTransactionsRefType = "badge"
	PointTransactionsRefTypeEnrollment PointTransactionsRefType = "enrollment"
)

func (e *PointTransactionsRefType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PointTransactionsRefType(s)
	case string:
		*e = PointTransactionsRefType(s)
	default:
		return fmt.Errorf("unsupported scan type for PointTransactionsRefType: %T", src)
	}
	return nil
}

type NullPointTransactionsRefType struct {
	PointTransactionsRefType PointTransactionsRefType `json:"point_transactions_ref_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if PointTransactionsRefType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPointTransactionsRefType) Scan(value interface{}) error {
	if value == nil {
		ns.PointTransactionsRefType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PointTransactionsRefType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPointTransactionsRefType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PointTransactionsRefType), nil
}

func (e PointTransactionsRefType) Valid() bool {
	switch e {
	case PointTransactionsRefTypeLesson,
		PointTransactionsRefTypePractice,
		PointTransactionsRefTypeBadge,
		PointTransactionsRefTypeEnrollment:
		return true
	}
	return false
}

type PracticeCompletionsStatus string

const (
	PracticeCompletionsStatusInProgress PracticeCompletionsStatus = "in_progress"
	PracticeCompletionsStatusCompleted  PracticeCompletionsStatus = "completed"
	PracticeCompletionsStatusSkipped    PracticeCompletionsStatus = "skipped"
)

func (e *PracticeCompletionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PracticeCompletionsStatus(s)
	case string:
		*e = PracticeCompletionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PracticeCompletionsStatus: %T", src)
	}
	return nil
}

type NullPracticeCompletionsStatus struct {
	PracticeCompletionsStatus PracticeCompletionsStatus `json:"practice_completions_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if PracticeCompletionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPracticeCompletionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PracticeCompletionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PracticeCompletionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPracticeCompletionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PracticeCompletionsStatus), nil
}

func (e PracticeCompletionsStatus) Valid() bool {
	switch e {
	case PracticeCompletionsStatusInProgress,
		PracticeCompletionsStatusCompleted,
		PracticeCompletionsStatusSkipped:
		return true
	}
	return false
}

type PracticeProjectsDifficulty string

const (
	PracticeProjectsDifficultyBeginner     PracticeProjectsDifficulty = "beginner"
	PracticeProjectsDifficultyIntermediate PracticeProjectsDifficulty = "intermediate"
	PracticeProjectsDifficultyAdvanced     PracticeProjectsDifficulty = "advanced"
	PracticeProjectsDifficultyExpert       PracticeProjectsDifficulty = "expert"
)

func (e *PracticeProjectsDifficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PracticeProjectsDifficulty(s)
	case string:
		*e = PracticeProjectsDifficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for PracticeProjectsDifficulty: %T", src)
	}
	return nil
}

type NullPracticeProjectsDifficulty struct {
	PracticeProjectsDifficulty PracticeProjectsDifficulty `json:"practice_projects_difficulty"`
	Valid                      bool                       `json:"valid"` // Valid is true if PracticeProjectsDifficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPracticeProjectsDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.PracticeProjectsDifficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PracticeProjectsDifficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPracticeProjectsDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PracticeProjectsDifficulty), nil
}

func (e PracticeProjectsDifficulty) Valid() bool {
	switch e {
	case PracticeProjectsDifficultyBeginner,
		PracticeProjectsDifficultyIntermediate,
		PracticeProjectsDifficultyAdvanced,
		PracticeProjectsDifficultyExpert:
		return true
	}
	return false
}

type PracticeProjectsProjectType string

const (
	PracticeProjectsProjectTypeModelDeployment PracticeProjectsProjectType = "model_deployment"
	PracticeProjectsProjectTypeModelTraining   PracticeProjectsProjectType = "model_training"
	PracticeProjectsProjectTypeModelInference  PracticeProjectsProjectType = "model_inference"
	PracticeProjectsProjectTypeApiIntegration  PracticeProjectsProjectType = "api_integration"
	PracticeProjectsProjectTypeNotebook        PracticeProjectsProjectType = "notebook"
	PracticeProjectsProjectTypeSandbox         PracticeProjectsProjectType = "sandbox"
	PracticeProjectsProjectTypeRepository      PracticeProjectsProjectType = "repository"
	PracticeProjectsProjectTypeCsghubSpace     PracticeProjectsProjectType = "csghub_space"
)

func (e *PracticeProjectsProjectType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PracticeProjectsProjectType(s)
	case string:
		*e = PracticeProjectsProjectType(s)
	default:
		return fmt.Errorf("unsupported scan type for PracticeProjectsProjectType: %T", src)
	}
	return nil
}

type NullPracticeProjectsProjectType struct {
	PracticeProjectsProjectType PracticeProjectsProjectType `json:"practice_projects_project_type"`
	Valid                       bool                        `json:"valid"` // Valid is true if PracticeProjectsProjectType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPracticeProjectsProjectType) Scan(value interface{}) error {
	if value == nil {
		ns.PracticeProjectsProjectType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PracticeProjectsProjectType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPracticeProjectsProjectType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PracticeProjectsProjectType), nil
}

func (e PracticeProjectsProjectType) Valid() bool {
	switch e {
	case PracticeProjectsProjectTypeModelDeployment,
		PracticeProjectsProjectTypeModelTraining,
		PracticeProjectsProjectTypeModelInference,
		PracticeProjectsProjectTypeApiIntegration,
		PracticeProjectsProjectTypeNotebook,
		PracticeProjectsProjectTypeSandbox,
		PracticeProjectsProjectTypeRepository,
		PracticeProjectsProjectTypeCsghubSpace:
		return true
	}
	return false
}

type ProgressRecordsStatus string

const (
	ProgressRecordsStatusNotStarted ProgressRecordsStatus = "not_started"
	ProgressRecordsStatusInProgress ProgressRecordsStatus = "in_progress"
	ProgressRecordsStatusCompleted  ProgressRecordsStatus = "completed"
)

func (e *ProgressRecordsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgressRecordsStatus(s)
	case string:
		*e = ProgressRecordsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgressRecordsStatus: %T", src)
	}
	return nil
}

type NullProgressRecordsStatus struct {
	ProgressRecordsStatus ProgressRecordsStatus `json:"progress_records_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if ProgressRecordsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgressRecordsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProgressRecordsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgressRecordsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgressRecordsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgressRecordsStatus), nil
}

func (e ProgressRecordsStatus) Valid() bool {
	switch e {
	case ProgressRecordsStatusNotStarted,
		ProgressRecordsStatusInProgress,
		ProgressRecordsStatusCompleted:
		return true
	}
	return false
}

type QuickPromptsScope string

const (
	QuickPromptsScopeLesson QuickPromptsScope = "lesson"
	QuickPromptsScopeCourse QuickPromptsScope = "course"
	QuickPromptsScopeDegree QuickPromptsScope = "degree"
	QuickPromptsScopeGlobal QuickPromptsScope = "global"
)

func (e *QuickPromptsScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuickPromptsScope(s)
	case string:
		*e = QuickPromptsScope(s)
	default:
		return fmt.Errorf("unsupported scan type for QuickPromptsScope: %T", src)
	}
	return nil
}

type NullQuickPromptsScope struct {
	QuickPromptsScope QuickPromptsScope `json:"quick_prompts_scope"`
	Valid             bool              `json:"valid"` // Valid is true if QuickPromptsScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuickPromptsScope) Scan(value interface{}) error {
	if value == nil {
		ns.QuickPromptsScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuickPromptsScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuickPromptsScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuickPromptsScope), nil
}

func (e QuickPromptsScope) Valid() bool {
	switch e {
	case QuickPromptsScopeLesson,
		QuickPromptsScopeCourse,
		QuickPromptsScopeDegree,
		QuickPromptsScopeGlobal:
		return true
	}
	return false
}

type ResourcesType string

const (
	ResourcesTypePdf   ResourcesType = "pdf"
	ResourcesTypeCode  ResourcesType = "code"
	ResourcesTypeLink  ResourcesType = "link"
	ResourcesTypeVideo ResourcesType = "video"
	ResourcesTypeAudio ResourcesType = "audio"
)

func (e *ResourcesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourcesType(s)
	case string:
		*e = ResourcesType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourcesType: %T", src)
	}
	return nil
}

type NullResourcesType struct {
	ResourcesType ResourcesType `json:"resources_type"`
	Valid         bool          `json:"valid"` // Valid is true if ResourcesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourcesType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourcesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourcesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourcesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourcesType), nil
}

func (e ResourcesType) Valid() bool {
	switch e {
	case ResourcesTypePdf,
		ResourcesTypeCode,
		ResourcesTypeLink,
		ResourcesTypeVideo,
		ResourcesTypeAudio:
		return true
	}
	return false
}

type SiteSettingsScope string

const (
	SiteSettingsScopeGlobal SiteSettingsScope = "global"
	SiteSettingsScopePage   SiteSettingsScope = "page"
	SiteSettingsScopeUser   SiteSettingsScope = "user"
)

func (e *SiteSettingsScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SiteSettingsScope(s)
	case string:
		*e = SiteSettingsScope(s)
	default:
		return fmt.Errorf("unsupported scan type for SiteSettingsScope: %T", src)
	}
	return nil
}

type NullSiteSettingsScope struct {
	SiteSettingsScope SiteSettingsScope `json:"site_settings_scope"`
	Valid             bool              `json:"valid"` // Valid is true if SiteSettingsScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSiteSettingsScope) Scan(value interface{}) error {
	if value == nil {
		ns.SiteSettingsScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SiteSettingsScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSiteSettingsScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SiteSettingsScope), nil
}

func (e SiteSettingsScope) Valid() bool {
	switch e {
	case SiteSettingsScopeGlobal,
		SiteSettingsScopePage,
		SiteSettingsScopeUser:
		return true
	}
	return false
}

type SubmissionsStatus string

const (
	SubmissionsStatusDraft       SubmissionsStatus = "draft"
	SubmissionsStatusSubmitted   SubmissionsStatus = "submitted"
	SubmissionsStatusUnderReview SubmissionsStatus = "under_review"
	SubmissionsStatusShortlisted SubmissionsStatus = "shortlisted"
	SubmissionsStatusWinner      SubmissionsStatus = "winner"
	SubmissionsStatusRejected    SubmissionsStatus = "rejected"
)

func (e *SubmissionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionsStatus(s)
	case string:
		*e = SubmissionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionsStatus: %T", src)
	}
	return nil
}

type NullSubmissionsStatus struct {
	SubmissionsStatus SubmissionsStatus `json:"submissions_status"`
	Valid             bool              `json:"valid"` // Valid is true if SubmissionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionsStatus), nil
}

func (e SubmissionsStatus) Valid() bool {
	switch e {
	case SubmissionsStatusDraft,
		SubmissionsStatusSubmitted,
		SubmissionsStatusUnderReview,
		SubmissionsStatusShortlisted,
		SubmissionsStatusWinner,
		SubmissionsStatusRejected:
		return true
	}
	return false
}

type TeamMembersRole string

const (
	TeamMembersRoleCaptain TeamMembersRole = "captain"
	TeamMembersRoleMember  TeamMembersRole = "member"
)

func (e *TeamMembersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamMembersRole(s)
	case string:
		*e = TeamMembersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamMembersRole: %T", src)
	}
	return nil
}

type NullTeamMembersRole struct {
	TeamMembersRole TeamMembersRole `json:"team_members_role"`
	Valid           bool            `json:"valid"` // Valid is true if TeamMembersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamMembersRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamMembersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamMembersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamMembersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamMembersRole), nil
}

func (e TeamMembersRole) Valid() bool {
	switch e {
	case TeamMembersRoleCaptain,
		TeamMembersRoleMember:
		return true
	}
	return false
}

type UrlImportsPlatform string

const (
	UrlImportsPlatformYoutube  UrlImportsPlatform = "youtube"
	UrlImportsPlatformBilibili UrlImportsPlatform = "bilibili"
	UrlImportsPlatformUnknown  UrlImportsPlatform = "unknown"
)

func (e *UrlImportsPlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrlImportsPlatform(s)
	case string:
		*e = UrlImportsPlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for UrlImportsPlatform: %T", src)
	}
	return nil
}

type NullUrlImportsPlatform struct {
	UrlImportsPlatform UrlImportsPlatform `json:"url_imports_platform"`
	Valid              bool               `json:"valid"` // Valid is true if UrlImportsPlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrlImportsPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.UrlImportsPlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrlImportsPlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrlImportsPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrlImportsPlatform), nil
}

func (e UrlImportsPlatform) Valid() bool {
	switch e {
	case UrlImportsPlatformYoutube,
		UrlImportsPlatformBilibili,
		UrlImportsPlatformUnknown:
		return true
	}
	return false
}

type UrlImportsStatus string

const (
	UrlImportsStatusPending   UrlImportsStatus = "pending"
	UrlImportsStatusFetched   UrlImportsStatus = "fetched"
	UrlImportsStatusImported  UrlImportsStatus = "imported"
	UrlImportsStatusCompleted UrlImportsStatus = "completed"
	UrlImportsStatusFailed    UrlImportsStatus = "failed"
)

func (e *UrlImportsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrlImportsStatus(s)
	case string:
		*e = UrlImportsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UrlImportsStatus: %T", src)
	}
	return nil
}

type NullUrlImportsStatus struct {
	UrlImportsStatus UrlImportsStatus `json:"url_imports_status"`
	Valid            bool             `json:"valid"` // Valid is true if UrlImportsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrlImportsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UrlImportsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrlImportsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrlImportsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrlImportsStatus), nil
}

func (e UrlImportsStatus) Valid() bool {
	switch e {
	case UrlImportsStatusPending,
		UrlImportsStatusFetched,
		UrlImportsStatusImported,
		UrlImportsStatusCompleted,
		UrlImportsStatusFailed:
		return true
	}
	return false
}

type UsersRole string

const (
	UsersRoleAdmin      UsersRole = "admin"
	UsersRoleStudent    UsersRole = "student"
	UsersRoleInstructor UsersRole = "instructor"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

func (e UsersRole) Valid() bool {
	switch e {
	case UsersRoleAdmin,
		UsersRoleStudent,
		UsersRoleInstructor:
		return true
	}
	return false
}

type AiConfig struct {
	ID        string         `json:"id"`
	Provider  string         `json:"provider"`
	ApiKeyEnc string         `json:"api_key_enc"`
	Model     string         `json:"model"`
	BaseUrl   sql.NullString `json:"base_url"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type AiUsage struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Feature   string       `json:"feature"`
	TokensIn  int32        `json:"tokens_in"`
	TokensOut int32        `json:"tokens_out"`
	Cost      string       `json:"cost"`
	CreatedAt time.Time    `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Announcement struct {
	ID          string    `json:"id"`
	HackathonID string    `json:"hackathon_id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	IsPinned    bool      `json:"is_pinned"`
	CreatedAt   time.Time `json:"created_at"`
}

type AppSetting struct {
	Key         string           `json:"key"`
	ValueJson   json.RawMessage  `json:"value_json"`
	Scope       AppSettingsScope `json:"scope"`
	Description sql.NullString   `json:"description"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type AuditLog struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Action    string         `json:"action"`
	Entity    string         `json:"entity"`
	EntityID  sql.NullString `json:"entity_id"`
	Details   sql.NullString `json:"details"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt time.Time      `json:"created_at"`
}

type AuthProvider struct {
	ID         string          `json:"id"`
	Label      string          `json:"label"`
	Icon       string          `json:"icon"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
	Config     json.RawMessage `json:"config"`
}

type Badge struct {
	ID            string             `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          string             `json:"icon"`
	Category      string             `json:"category"`
	CriteriaType  BadgesCriteriaType `json:"criteria_type"`
	CriteriaValue int32              `json:"criteria_value"`
	CriteriaJson  json.RawMessage    `json:"criteria_json"`
	Points        int32              `json:"points"`
	IsActive      bool               `json:"is_active"`
	OrderIndex    int32              `json:"order_index"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type Certificate struct {
	ID           string           `json:"id"`
	UserID       string           `json:"user_id"`
	Type         CertificatesType `json:"type"`
	RefID        string           `json:"ref_id"`
	Title        string           `json:"title"`
	Description  sql.NullString   `json:"description"`
	SerialNumber string           `json:"serial_number"`
	IssuedAt     time.Time        `json:"issued_at"`
	CompletedAt  time.Time        `json:"completed_at"`
	ImageUrl     sql.NullString   `json:"image_url"`
	VerifyUrl    sql.NullString   `json:"verify_url"`
	Metadata     json.RawMessage  `json:"metadata"`
	RevokedAt    sql.NullTime     `json:"revoked_at"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

type Chapter struct {
	ID          string         `json:"id"`
	CourseID    string         `json:"course_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	OrderIndex  int32          `json:"order_index"`
	CreatedAt   time.Time      `json:"created_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type ChatMessage struct {
	ID        string           `json:"id"`
	SessionID string           `json:"session_id"`
	Role      ChatMessagesRole `json:"role"`
	Content   string           `json:"content"`
	Tokens    int32            `json:"tokens"`
	CreatedAt time.Time        `json:"created_at"`
}

type ChatSession struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	LessonID  sql.NullString `json:"lesson_id"`
	Title     sql.NullString `json:"title"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Course struct {
	ID             string            `json:"id"`
	Title          string            `json:"title"`
	Description    string            `json:"description"`
	LearningPoints string            `json:"learning_points"`
	Instructor     string            `json:"instructor"`
	Level          CoursesLevel      `json:"level"`
	Duration       string            `json:"duration"`
	Thumbnail      string            `json:"thumbnail"`
	Tags           string            `json:"tags"`
	CostType       CoursesCostType   `json:"cost_type"`
	Price          string            `json:"price"`
	Status         CoursesStatus     `json:"status"`
	CourseType     CoursesCourseType `json:"course_type"`
	ExternalUrl    sql.NullString    `json:"external_url"`
	SourceVideoUrl sql.NullString    `json:"source_video_url"`
	SourcePlatform sql.NullString    `json:"source_platform"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	IndustryID     sql.NullString    `json:"industry_id"`
	CategoryID     sql.NullString    `json:"category_id"`
}

type CourseCategory struct {
	ID         string `json:"id"`
	Key        string `json:"key"`
	Label      string `json:"label"`
	IsActive   bool   `json:"is_active"`
	OrderIndex int32  `json:"order_index"`
}

type CourseInstructorLink struct {
	ID           string                    `json:"id"`
	CourseID     string                    `json:"course_id"`
	InstructorID string                    `json:"instructor_id"`
	Role         CourseInstructorLinksRole `json:"role"`
	IsPrimary    bool                      `json:"is_primary"`
	OrderIndex   int32                     `json:"order_index"`
	CreatedAt    time.Time                 `json:"created_at"`
}

type DateFormatTemplate struct {
	Scope    DateFormatTemplatesScope `json:"scope"`
	Locale   string                   `json:"locale"`
	Template string                   `json:"template"`
}

type DegreeCourse struct {
	DegreeID   string `json:"degree_id"`
	CourseID   string `json:"course_id"`
	OrderIndex int32  `json:"order_index"`
}

type Enrollment struct {
	ID         string            `json:"id"`
	UserID     string            `json:"user_id"`
	CourseID   sql.NullString    `json:"course_id"`
	DegreeID   sql.NullString    `json:"degree_id"`
	EnrolledAt time.Time         `json:"enrolled_at"`
	ExpiresAt  sql.NullTime      `json:"expires_at"`
	Source     EnrollmentsSource `json:"source"`
	DeletedAt  sql.NullTime      `json:"deleted_at"`
}

type EnterpriseInquiry struct {
	ID          string                    `json:"id"`
	Name        string                    `json:"name"`
	Email       string                    `json:"email"`
	Company     string                    `json:"company"`
	TeamSize    string                    `json:"team_size"`
	Phone       sql.NullString            `json:"phone"`
	Topic       string                    `json:"topic"`
	Description sql.NullString            `json:"description"`
	Status      EnterpriseInquiriesStatus `json:"status"`
	DeletedAt   sql.NullTime              `json:"deleted_at"`
	CreatedAt   time.Time                 `json:"created_at"`
	UpdatedAt   time.Time                 `json:"updated_at"`
}

type EnterpriseMethod struct {
	ID         string          `json:"id"`
	Num        string          `json:"num"`
	Title      string          `json:"title"`
	Desc       string          `json:"desc"`
	Bullets    json.RawMessage `json:"bullets"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
}

type EnumTranslation struct {
	EnumType   string         `json:"enum_type"`
	EnumValue  string         `json:"enum_value"`
	Locale     string         `json:"locale"`
	Label      string         `json:"label"`
	ColorClass sql.NullString `json:"color_class"`
	Icon       sql.NullString `json:"icon"`
	SortOrder  int32          `json:"sort_order"`
}

type FooterColumn struct {
	ID         string          `json:"id"`
	Title      string          `json:"title"`
	Links      json.RawMessage `json:"links"`
	IsActive   bool            `json:"is_active"`
	OrderIndex int32           `json:"order_index"`
}

type Hackathon struct {
	ID                     string           `json:"id"`
	Title                  string           `json:"title"`
	Description            string           `json:"description"`
	BannerUrl              sql.NullString   `json:"banner_url"`
	Status                 HackathonsStatus `json:"status"`
	StartDate              time.Time        `json:"start_date"`
	EndDate                time.Time        `json:"end_date"`
	RegisterDeadline       sql.NullTime     `json:"register_deadline"`
	SubmissionDeadline     sql.NullTime     `json:"submission_deadline"`
	MaxTeamSize            int32            `json:"max_team_size"`
	MinTeamSize            int32            `json:"min_team_size"`
	Location               sql.NullString   `json:"location"`
	Rules                  sql.NullString   `json:"rules"`
	SubmissionRequirements sql.NullString   `json:"submission_requirements"`
	Prizes                 sql.NullString   `json:"prizes"`
	RegistrationUrl        sql.NullString   `json:"registration_url"`
	RegistrationLabel      sql.NullString   `json:"registration_label"`
	OrganizerID            sql.NullString   `json:"organizer_id"`
	CreatedAt              time.Time        `json:"created_at"`
	UpdatedAt              time.Time        `json:"updated_at"`
}

type HackathonRegistration struct {
	ID           string                       `json:"id"`
	HackathonID  string                       `json:"hackathon_id"`
	UserID       string                       `json:"user_id"`
	Status       HackathonRegistrationsStatus `json:"status"`
	RegisteredAt time.Time                    `json:"registered_at"`
	CheckedInAt  sql.NullTime                 `json:"checked_in_at"`
	DeletedAt    sql.NullTime                 `json:"deleted_at"`
}

type HotKeyword struct {
	ID         string           `json:"id"`
	Keyword    string           `json:"keyword"`
	Scope      HotKeywordsScope `json:"scope"`
	IsActive   bool             `json:"is_active"`
	OrderIndex int32            `json:"order_index"`
}

type I18nMessage struct {
	Key      string               `json:"key"`
	Locale   string               `json:"locale"`
	Value    string               `json:"value"`
	Category I18nMessagesCategory `json:"category"`
}

type Industry struct {
	ID          string          `json:"id"`
	Key         string          `json:"key"`
	Label       string          `json:"label"`
	Description sql.NullString  `json:"description"`
	Icon        sql.NullString  `json:"icon"`
	Methodology json.RawMessage `json:"methodology"`
	IsActive    bool            `json:"is_active"`
	OrderIndex  int32           `json:"order_index"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Instructor struct {
	ID                string         `json:"id"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	NameEn            sql.NullString `json:"name_en"`
	Title             sql.NullString `json:"title"`
	TitleEn           sql.NullString `json:"title_en"`
	Headline          sql.NullString `json:"headline"`
	HeadlineEn        sql.NullString `json:"headline_en"`
	Bio               sql.NullString `json:"bio"`
	BioEn             sql.NullString `json:"bio_en"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Company           sql.NullString `json:"company"`
	YearsOfExperience sql.NullInt32  `json:"years_of_experience"`
	LinkedinUrl       sql.NullString `json:"linkedin_url"`
	GithubUrl         sql.NullString `json:"github_url"`
	TwitterUrl        sql.NullString `json:"twitter_url"`
	WebsiteUrl        sql.NullString `json:"website_url"`
	ContactEmail      sql.NullString `json:"contact_email"`
	Notes             sql.NullString `json:"notes"`
	OrderIndex        int32          `json:"order_index"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type InstructorExpertise struct {
	ID         string         `json:"id"`
	Key        string         `json:"key"`
	Label      string         `json:"label"`
	LabelEn    sql.NullString `json:"label_en"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type InstructorExpertiseLink struct {
	InstructorID string `json:"instructor_id"`
	ExpertiseID  string `json:"expertise_id"`
	OrderIndex   int32  `json:"order_index"`
}

type Judge struct {
	ID          string         `json:"id"`
	HackathonID string         `json:"hackathon_id"`
	UserID      sql.NullString `json:"user_id"`
	Name        string         `json:"name"`
	Title       sql.NullString `json:"title"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
	OrderIndex  int32          `json:"order_index"`
	Role        string         `json:"role"`
}

type LearningEvent struct {
	ID          string                  `json:"id"`
	UserID      string                  `json:"user_id"`
	LessonID    sql.NullString          `json:"lesson_id"`
	EventType   LearningEventsEventType `json:"event_type"`
	PositionSec sql.NullInt32           `json:"position_sec"`
	DurationMs  sql.NullInt32           `json:"duration_ms"`
	Metadata    json.RawMessage         `json:"metadata"`
	CreatedAt   time.Time               `json:"created_at"`
}

type Lesson struct {
	ID            string         `json:"id"`
	ChapterID     string         `json:"chapter_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	VideoUrl      sql.NullString `json:"video_url"`
	VideoDuration sql.NullInt32  `json:"video_duration"`
	OrderIndex    int32          `json:"order_index"`
	IsPreview     bool           `json:"is_preview"`
	CreatedAt     time.Time      `json:"created_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type NanoDegree struct {
	ID             string              `json:"id"`
	Title          string              `json:"title"`
	Description    string              `json:"description"`
	LearningPoints string              `json:"learning_points"`
	Price          string              `json:"price"`
	Icon           string              `json:"icon"`
	CostType       NanoDegreesCostType `json:"cost_type"`
	Thumbnail      sql.NullString      `json:"thumbnail"`
	Status         NanoDegreesStatus   `json:"status"`
	CreatedAt      time.Time           `json:"created_at"`
	UpdatedAt      time.Time           `json:"updated_at"`
}

type Note struct {
	ID          string        `json:"id"`
	UserID      string        `json:"user_id"`
	LessonID    string        `json:"lesson_id"`
	Content     string        `json:"content"`
	PositionSec sql.NullInt32 `json:"position_sec"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type Notification struct {
	ID        string            `json:"id"`
	UserID    string            `json:"user_id"`
	Type      NotificationsType `json:"type"`
	Title     string            `json:"title"`
	Body      string            `json:"body"`
	LinkUrl   sql.NullString    `json:"link_url"`
	IsRead    bool              `json:"is_read"`
	ReadAt    sql.NullTime      `json:"read_at"`
	DeletedAt sql.NullTime      `json:"deleted_at"`
	CreatedAt time.Time         `json:"created_at"`
}

type Order struct {
	ID            string                  `json:"id"`
	UserID        string                  `json:"user_id"`
	Type          OrdersType              `json:"type"`
	CourseID      sql.NullString          `json:"course_id"`
	DegreeID      sql.NullString          `json:"degree_id"`
	Amount        string                  `json:"amount"`
	Currency      string                  `json:"currency"`
	Status        OrdersStatus            `json:"status"`
	PaymentMethod NullOrdersPaymentMethod `json:"payment_method"`
	TransactionID sql.NullString          `json:"transaction_id"`
	PaidAt        sql.NullTime            `json:"paid_at"`
	DeletedAt     sql.NullTime            `json:"deleted_at"`
	CreatedAt     time.Time               `json:"created_at"`
	UpdatedAt     time.Time               `json:"updated_at"`
}

type PageSetting struct {
	Page        string          `json:"page"`
	Key         string          `json:"key"`
	Value       json.RawMessage `json:"value"`
	Description sql.NullString  `json:"description"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type PointTransaction struct {
	ID        string                       `json:"id"`
	UserID    string                       `json:"user_id"`
	Amount    int32                        `json:"amount"`
	Reason    string                       `json:"reason"`
	RefType   NullPointTransactionsRefType `json:"ref_type"`
	RefID     sql.NullString               `json:"ref_id"`
	DeletedAt sql.NullTime                 `json:"deleted_at"`
	CreatedAt time.Time                    `json:"created_at"`
}

type PopularSearch struct {
	ID         string `json:"id"`
	Keyword    string `json:"keyword"`
	ClickCount int32  `json:"click_count"`
	IsActive   bool   `json:"is_active"`
	OrderIndex int32  `json:"order_index"`
}

type PracticeCompletion struct {
	ID            string                    `json:"id"`
	UserID        string                    `json:"user_id"`
	ProjectID     string                    `json:"project_id"`
	Status        PracticeCompletionsStatus `json:"status"`
	StartedAt     time.Time                 `json:"started_at"`
	CompletedAt   sql.NullTime              `json:"completed_at"`
	SubmissionUrl sql.NullString            `json:"submission_url"`
	Notes         sql.NullString            `json:"notes"`
	DeletedAt     sql.NullTime              `json:"deleted_at"`
}

type PracticeProject struct {
	ID            string                      `json:"id"`
	CourseID      string                      `json:"course_id"`
	Title         string                      `json:"title"`
	Description   string                      `json:"description"`
	ProjectUrl    string                      `json:"project_url"`
	ThumbnailUrl  sql.NullString              `json:"thumbnail_url"`
	Difficulty    PracticeProjectsDifficulty  `json:"difficulty"`
	EstimatedTime int32                       `json:"estimated_time"`
	Tags          sql.NullString              `json:"tags"`
	ProjectType   PracticeProjectsProjectType `json:"project_type"`
	OrderIndex    int32                       `json:"order_index"`
	Requirements  sql.NullString              `json:"requirements"`
	Objectives    sql.NullString              `json:"objectives"`
	IsActive      bool                        `json:"is_active"`
	CreatedAt     time.Time                   `json:"created_at"`
	UpdatedAt     time.Time                   `json:"updated_at"`
}

type ProgressRecord struct {
	ID           string                `json:"id"`
	UserID       string                `json:"user_id"`
	CourseID     string                `json:"course_id"`
	LessonID     string                `json:"lesson_id"`
	Status       ProgressRecordsStatus `json:"status"`
	CompletedAt  sql.NullTime          `json:"completed_at"`
	LastPosition sql.NullInt32         `json:"last_position"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type QuickPrompt struct {
	ID         string            `json:"id"`
	Emoji      string            `json:"emoji"`
	Label      string            `json:"label"`
	PromptText string            `json:"prompt_text"`
	Scope      QuickPromptsScope `json:"scope"`
	IsActive   bool              `json:"is_active"`
	OrderIndex int32             `json:"order_index"`
}

type RefreshToken struct {
	ID        string    `json:"id"`
	Token     string    `json:"token"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Resource struct {
	ID        string        `json:"id"`
	LessonID  string        `json:"lesson_id"`
	Title     string        `json:"title"`
	Url       string        `json:"url"`
	Type      ResourcesType `json:"type"`
	IsLocked  bool          `json:"is_locked"`
	CreatedAt time.Time     `json:"created_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

type Review struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	CourseID  string       `json:"course_id"`
	Rating    int32        `json:"rating"`
	Content   string       `json:"content"`
	Helpful   int32        `json:"helpful"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type ReviewHelpfulVote struct {
	ReviewID  string    `json:"review_id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SiteSetting struct {
	Key         string            `json:"key"`
	Value       json.RawMessage   `json:"value"`
	Scope       SiteSettingsScope `json:"scope"`
	Description sql.NullString    `json:"description"`
	UpdatedAt   time.Time         `json:"updated_at"`
}

type Sponsor struct {
	ID          string         `json:"id"`
	HackathonID string         `json:"hackathon_id"`
	Name        string         `json:"name"`
	LogoUrl     sql.NullString `json:"logo_url"`
	WebsiteUrl  sql.NullString `json:"website_url"`
	Tier        string         `json:"tier"`
	OrderIndex  int32          `json:"order_index"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Submission struct {
	ID          string            `json:"id"`
	HackathonID string            `json:"hackathon_id"`
	TeamID      sql.NullString    `json:"team_id"`
	UserID      sql.NullString    `json:"user_id"`
	Title       string            `json:"title"`
	Description string            `json:"description"`
	DemoUrl     sql.NullString    `json:"demo_url"`
	RepoUrl     sql.NullString    `json:"repo_url"`
	VideoUrl    sql.NullString    `json:"video_url"`
	Status      SubmissionsStatus `json:"status"`
	Score       sql.NullString    `json:"score"`
	Feedback    sql.NullString    `json:"feedback"`
	SubmittedAt sql.NullTime      `json:"submitted_at"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
	DeletedAt   sql.NullTime      `json:"deleted_at"`
}

type Team struct {
	ID          string         `json:"id"`
	HackathonID string         `json:"hackathon_id"`
	Name        string         `json:"name"`
	Slogan      sql.NullString `json:"slogan"`
	CaptainID   string         `json:"captain_id"`
	CreatedAt   time.Time      `json:"created_at"`
}

type TeamMember struct {
	ID     string          `json:"id"`
	TeamID string          `json:"team_id"`
	UserID string          `json:"user_id"`
	Role   TeamMembersRole `json:"role"`
}

type Testimonial struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Title      string         `json:"title"`
	Quote      string         `json:"quote"`
	Avatar     sql.NullString `json:"avatar"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
}

type TopNavItem struct {
	ID         string         `json:"id"`
	Label      string         `json:"label"`
	Path       string         `json:"path"`
	Icon       sql.NullString `json:"icon"`
	IsActive   bool           `json:"is_active"`
	OrderIndex int32          `json:"order_index"`
}

type UrlImport struct {
	ID              string             `json:"id"`
	Url             string             `json:"url"`
	Platform        UrlImportsPlatform `json:"platform"`
	Status          UrlImportsStatus   `json:"status"`
	RequestedBy     sql.NullString     `json:"requested_by"`
	ResultCourseID  sql.NullString     `json:"result_course_id"`
	ErrorMessage    sql.NullString     `json:"error_message"`
	Title           sql.NullString     `json:"title"`
	Author          sql.NullString     `json:"author"`
	ThumbnailUrl    sql.NullString     `json:"thumbnail_url"`
	DurationSeconds sql.NullInt32      `json:"duration_seconds"`
	ExtractedJson   sql.NullString     `json:"extracted_json"`
	FetchedAt       sql.NullTime       `json:"fetched_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type User struct {
	ID                    string         `json:"id"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	Name                  string         `json:"name"`
	Role                  UsersRole      `json:"role"`
	AvatarUrl             sql.NullString `json:"avatar_url"`
	PasswordResetRequired bool           `json:"password_reset_required"`
	Points                int32          `json:"points"`
	Level                 int32          `json:"level"`
	DeletedAt             sql.NullTime   `json:"deleted_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	LastLoginAt           sql.NullTime   `json:"last_login_at"`
}

type UserAiProviderConfig struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Provider  string         `json:"provider"`
	ApiKeyEnc string         `json:"api_key_enc"`
	Model     string         `json:"model"`
	BaseUrl   sql.NullString `json:"base_url"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type UserBadge struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	BadgeID    string    `json:"badge_id"`
	UnlockedAt time.Time `json:"unlocked_at"`
}

type UserProviderAccount struct {
	ID             string          `json:"id"`
	UserID         string          `json:"user_id"`
	Provider       string          `json:"provider"`
	ProviderUserID string          `json:"provider_user_id"`
	Email          sql.NullString  `json:"email"`
	DisplayName    sql.NullString  `json:"display_name"`
	IsPrimary      bool            `json:"is_primary"`
	LinkedAt       time.Time       `json:"linked_at"`
	LastUsedAt     time.Time       `json:"last_used_at"`
	DeletedAt      sql.NullTime    `json:"deleted_at"`
	Profile        json.RawMessage `json:"profile"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}
