// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createNote = `-- name: CreateNote :execresult
INSERT INTO notes
  (id, user_id, lesson_id, content, position_sec, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateNoteParams struct {
	ID          string        `json:"id"`
	UserID      string        `json:"user_id"`
	LessonID    string        `json:"lesson_id"`
	Content     string        `json:"content"`
	PositionSec sql.NullInt32 `json:"position_sec"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNote,
		arg.ID,
		arg.UserID,
		arg.LessonID,
		arg.Content,
		arg.PositionSec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, lesson_id, content, position_sec, created_at, updated_at FROM notes WHERE id = ?
`

func (q *Queries) GetNoteByID(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LessonID,
		&i.Content,
		&i.PositionSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesByUserLesson = `-- name: ListNotesByUserLesson :many
SELECT id, user_id, lesson_id, content, position_sec, created_at, updated_at FROM notes
WHERE user_id = ? AND lesson_id = ?
ORDER BY created_at ASC
`

type ListNotesByUserLessonParams struct {
	UserID   string `json:"user_id"`
	LessonID string `json:"lesson_id"`
}

// All notes for a (user, lesson) pair, oldest first (so the user
// can see them in chronological order).
func (q *Queries) ListNotesByUserLesson(ctx context.Context, arg ListNotesByUserLessonParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotesByUserLesson, arg.UserID, arg.LessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.Content,
			&i.PositionSec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes
SET content = ?, position_sec = ?, updated_at = ?
WHERE id = ?
`

type UpdateNoteParams struct {
	Content     string        `json:"content"`
	PositionSec sql.NullInt32 `json:"position_sec"`
	UpdatedAt   time.Time     `json:"updated_at"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateNote,
		arg.Content,
		arg.PositionSec,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
