// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const clearReadNotifications = `-- name: ClearReadNotifications :exec
UPDATE notifications SET deleted_at = ?
WHERE user_id = ? AND is_read = 1 AND deleted_at IS NULL
`

type ClearReadNotificationsParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    string       `json:"user_id"`
}

// Bulk soft-delete: delete all read notifications.
func (q *Queries) ClearReadNotifications(ctx context.Context, arg ClearReadNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, clearReadNotifications, arg.DeletedAt, arg.UserID)
	return err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = ? AND is_read = 0 AND deleted_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :execresult
INSERT INTO notifications
  (id, user_id, type, title, body, link_url, is_read, read_at, deleted_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, 0, NULL, NULL, ?)
`

type CreateNotificationParams struct {
	ID        string            `json:"id"`
	UserID    string            `json:"user_id"`
	Type      NotificationsType `json:"type"`
	Title     string            `json:"title"`
	Body      string            `json:"body"`
	LinkUrl   sql.NullString    `json:"link_url"`
	CreatedAt time.Time         `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.LinkUrl,
		arg.CreatedAt,
	)
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, body, link_url, is_read, read_at, deleted_at, created_at FROM notifications
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ?
`

type ListNotificationsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

// User's notifications, newest first. Excludes soft-deleted.
func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.LinkUrl,
			&i.IsRead,
			&i.ReadAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = 1, read_at = ?
WHERE user_id = ? AND is_read = 0 AND deleted_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	UserID string       `json:"user_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, arg.ReadAt, arg.UserID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = 1, read_at = ? WHERE id = ? AND user_id = ?
`

type MarkNotificationReadParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	ID     string       `json:"id"`
	UserID string       `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ReadAt, arg.ID, arg.UserID)
	return err
}

const softDeleteNotification = `-- name: SoftDeleteNotification :exec
UPDATE notifications SET deleted_at = ? WHERE id = ? AND user_id = ?
`

type SoftDeleteNotificationParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
}

func (q *Queries) SoftDeleteNotification(ctx context.Context, arg SoftDeleteNotificationParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteNotification, arg.DeletedAt, arg.ID, arg.UserID)
	return err
}
