// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET status = 'expired', updated_at = ?
WHERE id = ? AND status = 'pending'
`

type CancelOrderParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) error {
	_, err := q.db.ExecContext(ctx, cancelOrder, arg.UpdatedAt, arg.ID)
	return err
}

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders
  (id, user_id, type, course_id, degree_id, amount, currency, status, payment_method, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	ID            string                  `json:"id"`
	UserID        string                  `json:"user_id"`
	Type          OrdersType              `json:"type"`
	CourseID      sql.NullString          `json:"course_id"`
	DegreeID      sql.NullString          `json:"degree_id"`
	Amount        string                  `json:"amount"`
	Currency      string                  `json:"currency"`
	Status        OrdersStatus            `json:"status"`
	PaymentMethod NullOrdersPaymentMethod `json:"payment_method"`
	CreatedAt     time.Time               `json:"created_at"`
	UpdatedAt     time.Time               `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.CourseID,
		arg.DegreeID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.PaymentMethod,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getActiveEnrollmentByCourse = `-- name: GetActiveEnrollmentByCourse :one
SELECT id, user_id, course_id, degree_id, enrolled_at, expires_at, source, deleted_at
FROM enrollments
WHERE user_id = ? AND course_id = ? AND deleted_at IS NULL
`

type GetActiveEnrollmentByCourseParams struct {
	UserID   string         `json:"user_id"`
	CourseID sql.NullString `json:"course_id"`
}

func (q *Queries) GetActiveEnrollmentByCourse(ctx context.Context, arg GetActiveEnrollmentByCourseParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, getActiveEnrollmentByCourse, arg.UserID, arg.CourseID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.DegreeID,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.Source,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveEnrollmentByDegree = `-- name: GetActiveEnrollmentByDegree :one
SELECT id, user_id, course_id, degree_id, enrolled_at, expires_at, source, deleted_at
FROM enrollments
WHERE user_id = ? AND degree_id = ? AND deleted_at IS NULL
`

type GetActiveEnrollmentByDegreeParams struct {
	UserID   string         `json:"user_id"`
	DegreeID sql.NullString `json:"degree_id"`
}

func (q *Queries) GetActiveEnrollmentByDegree(ctx context.Context, arg GetActiveEnrollmentByDegreeParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, getActiveEnrollmentByDegree, arg.UserID, arg.DegreeID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.DegreeID,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.Source,
		&i.DeletedAt,
	)
	return i, err
}

const getCourseForOrder = `-- name: GetCourseForOrder :one
SELECT id, title, cost_type, price FROM courses WHERE id = ?
`

type GetCourseForOrderRow struct {
	ID       string          `json:"id"`
	Title    string          `json:"title"`
	CostType CoursesCostType `json:"cost_type"`
	Price    string          `json:"price"`
}

func (q *Queries) GetCourseForOrder(ctx context.Context, id string) (GetCourseForOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseForOrder, id)
	var i GetCourseForOrderRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CostType,
		&i.Price,
	)
	return i, err
}

const getDegreeCourses = `-- name: GetDegreeCourses :many
SELECT course_id FROM degree_courses WHERE degree_id = ? ORDER BY order_index ASC
`

func (q *Queries) GetDegreeCourses(ctx context.Context, degreeID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDegreeCourses, degreeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var course_id string
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDegreeForOrder = `-- name: GetDegreeForOrder :one
SELECT id, title, cost_type, price FROM nano_degrees WHERE id = ?
`

type GetDegreeForOrderRow struct {
	ID       string              `json:"id"`
	Title    string              `json:"title"`
	CostType NanoDegreesCostType `json:"cost_type"`
	Price    string              `json:"price"`
}

func (q *Queries) GetDegreeForOrder(ctx context.Context, id string) (GetDegreeForOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getDegreeForOrder, id)
	var i GetDegreeForOrderRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CostType,
		&i.Price,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, type, course_id, degree_id, amount, currency,
       status, payment_method, transaction_id, paid_at, deleted_at, created_at, updated_at
FROM orders
WHERE id = ?
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CourseID,
		&i.DegreeID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentMethod,
		&i.TransactionID,
		&i.PaidAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForRefund = `-- name: GetOrderForRefund :one
SELECT id, user_id, type, course_id, degree_id, amount, paid_at, status
FROM orders WHERE id = ?
`

type GetOrderForRefundRow struct {
	ID       string         `json:"id"`
	UserID   string         `json:"user_id"`
	Type     OrdersType     `json:"type"`
	CourseID sql.NullString `json:"course_id"`
	DegreeID sql.NullString `json:"degree_id"`
	Amount   string         `json:"amount"`
	PaidAt   sql.NullTime   `json:"paid_at"`
	Status   OrdersStatus   `json:"status"`
}

// Fetch the order with paid_at for the refund flow.
func (q *Queries) GetOrderForRefund(ctx context.Context, id string) (GetOrderForRefundRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderForRefund, id)
	var i GetOrderForRefundRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CourseID,
		&i.DegreeID,
		&i.Amount,
		&i.PaidAt,
		&i.Status,
	)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, type, course_id, degree_id, amount, currency,
       status, payment_method, transaction_id, paid_at, deleted_at, created_at, updated_at
FROM orders
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.CourseID,
			&i.DegreeID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentMethod,
			&i.TransactionID,
			&i.PaidAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :exec
UPDATE orders
SET status = 'paid', paid_at = ?, payment_method = ?, transaction_id = ?, updated_at = ?
WHERE id = ? AND status = 'pending'
`

type MarkOrderPaidParams struct {
	PaidAt        sql.NullTime            `json:"paid_at"`
	PaymentMethod NullOrdersPaymentMethod `json:"payment_method"`
	TransactionID sql.NullString          `json:"transaction_id"`
	UpdatedAt     time.Time               `json:"updated_at"`
	ID            string                  `json:"id"`
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) error {
	_, err := q.db.ExecContext(ctx, markOrderPaid,
		arg.PaidAt,
		arg.PaymentMethod,
		arg.TransactionID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const refundCountCompletedLessonsForCourse = `-- name: RefundCountCompletedLessonsForCourse :one

SELECT COUNT(*) FROM progress_records
WHERE user_id = ? AND course_id = ? AND status = 'completed'
`

type RefundCountCompletedLessonsForCourseParams struct {
	UserID   string `json:"user_id"`
	CourseID string `json:"course_id"`
}

// ============================================================================
// Refund flow (T15-final)
// ============================================================================
// Count the user's progress records in a course with status='completed'.
func (q *Queries) RefundCountCompletedLessonsForCourse(ctx context.Context, arg RefundCountCompletedLessonsForCourseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, refundCountCompletedLessonsForCourse, arg.UserID, arg.CourseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const refundCountDegreeCourses = `-- name: RefundCountDegreeCourses :one
SELECT COUNT(*) FROM degree_courses WHERE degree_id = ?
`

func (q *Queries) RefundCountDegreeCourses(ctx context.Context, degreeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, refundCountDegreeCourses, degreeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const refundCountStartedDegreeCourses = `-- name: RefundCountStartedDegreeCourses :one
SELECT COUNT(*) FROM progress_records pr
JOIN degree_courses dc ON dc.course_id = pr.course_id
WHERE pr.user_id = ? AND dc.degree_id = ?
  AND pr.status IN ('in_progress', 'completed')
`

type RefundCountStartedDegreeCoursesParams struct {
	UserID   string `json:"user_id"`
	DegreeID string `json:"degree_id"`
}

// Count the user's started progress records (in_progress + completed)
// across all degree-courses. If 0, degree is refundable.
func (q *Queries) RefundCountStartedDegreeCourses(ctx context.Context, arg RefundCountStartedDegreeCoursesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, refundCountStartedDegreeCourses, arg.UserID, arg.DegreeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const refundCountTotalLessonsForCourse = `-- name: RefundCountTotalLessonsForCourse :one
SELECT COUNT(*) FROM lessons l
JOIN chapters c ON c.id = l.chapter_id
WHERE c.course_id = ? AND l.deleted_at IS NULL AND c.deleted_at IS NULL
`

// Total lessons in a course (via chapters join). Used to compute refund
// progress ratio = completed / total.
func (q *Queries) RefundCountTotalLessonsForCourse(ctx context.Context, courseID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, refundCountTotalLessonsForCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const refundRevokeDegreeCourseEnrollments = `-- name: RefundRevokeDegreeCourseEnrollments :execrows
UPDATE enrollments
SET deleted_at = ?, expires_at = NULL
WHERE user_id = ? AND enrollments.course_id IN (
    SELECT dc.course_id FROM degree_courses dc WHERE dc.degree_id = ?
) AND enrollments.source = 'degree' AND enrollments.deleted_at IS NULL
`

type RefundRevokeDegreeCourseEnrollmentsParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    string       `json:"user_id"`
	DegreeID  string       `json:"degree_id"`
}

func (q *Queries) RefundRevokeDegreeCourseEnrollments(ctx context.Context, arg RefundRevokeDegreeCourseEnrollmentsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refundRevokeDegreeCourseEnrollments, arg.DeletedAt, arg.UserID, arg.DegreeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refundRevokeEnrollmentsForCourse = `-- name: RefundRevokeEnrollmentsForCourse :execrows
UPDATE enrollments
SET deleted_at = ?, expires_at = NULL
WHERE user_id = ? AND course_id = ? AND source = 'order' AND deleted_at IS NULL
`

type RefundRevokeEnrollmentsForCourseParams struct {
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UserID    string         `json:"user_id"`
	CourseID  sql.NullString `json:"course_id"`
}

// Soft-delete the user's order-sourced enrollment for a course.
func (q *Queries) RefundRevokeEnrollmentsForCourse(ctx context.Context, arg RefundRevokeEnrollmentsForCourseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refundRevokeEnrollmentsForCourse, arg.DeletedAt, arg.UserID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refundRevokeEnrollmentsForDegree = `-- name: RefundRevokeEnrollmentsForDegree :execrows
UPDATE enrollments
SET deleted_at = ?, expires_at = NULL
WHERE user_id = ? AND degree_id = ? AND source = 'order' AND deleted_at IS NULL
`

type RefundRevokeEnrollmentsForDegreeParams struct {
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UserID    string         `json:"user_id"`
	DegreeID  sql.NullString `json:"degree_id"`
}

func (q *Queries) RefundRevokeEnrollmentsForDegree(ctx context.Context, arg RefundRevokeEnrollmentsForDegreeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refundRevokeEnrollmentsForDegree, arg.DeletedAt, arg.UserID, arg.DegreeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
