// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: points.sql

package db

import (
	"context"
)

const getUserPoints = `-- name: GetUserPoints :one
SELECT points, level FROM users
WHERE id = ? AND deleted_at IS NULL
`

type GetUserPointsRow struct {
	Points int32 `json:"points"`
	Level  int32 `json:"level"`
}

// Returns the user's points + level. Returns no rows if the user doesn't exist.
func (q *Queries) GetUserPoints(ctx context.Context, id string) (GetUserPointsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPoints, id)
	var i GetUserPointsRow
	err := row.Scan(&i.Points, &i.Level)
	return i, err
}

const listRecentPointTransactions = `-- name: ListRecentPointTransactions :many
SELECT id, user_id, amount, reason, ref_type, ref_id, deleted_at, created_at FROM point_transactions
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ?
`

type ListRecentPointTransactionsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

// The user's most recent non-deleted point transactions, newest first.
func (q *Queries) ListRecentPointTransactions(ctx context.Context, arg ListRecentPointTransactionsParams) ([]PointTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPointTransactions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointTransaction{}
	for rows.Next() {
		var i PointTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Reason,
			&i.RefType,
			&i.RefID,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
