// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: practices.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countActivePracticeProjects = `-- name: CountActivePracticeProjects :one
SELECT COUNT(*) FROM practice_projects WHERE course_id = ? AND is_active = 1
`

func (q *Queries) CountActivePracticeProjects(ctx context.Context, courseID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePracticeProjects, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPracticeCompletion = `-- name: CreatePracticeCompletion :execresult
INSERT INTO practice_completions
  (id, user_id, project_id, status, started_at, submission_url, notes, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NULL)
`

type CreatePracticeCompletionParams struct {
	ID            string                    `json:"id"`
	UserID        string                    `json:"user_id"`
	ProjectID     string                    `json:"project_id"`
	Status        PracticeCompletionsStatus `json:"status"`
	StartedAt     time.Time                 `json:"started_at"`
	SubmissionUrl sql.NullString            `json:"submission_url"`
	Notes         sql.NullString            `json:"notes"`
}

func (q *Queries) CreatePracticeCompletion(ctx context.Context, arg CreatePracticeCompletionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPracticeCompletion,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Status,
		arg.StartedAt,
		arg.SubmissionUrl,
		arg.Notes,
	)
}

const createPracticeProject = `-- name: CreatePracticeProject :execresult
INSERT INTO practice_projects
  (id, course_id, title, description, project_url, thumbnail_url, difficulty, estimated_time, tags, project_type, order_index, requirements, objectives, is_active, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePracticeProjectParams struct {
	ID            string                      `json:"id"`
	CourseID      string                      `json:"course_id"`
	Title         string                      `json:"title"`
	Description   string                      `json:"description"`
	ProjectUrl    string                      `json:"project_url"`
	ThumbnailUrl  sql.NullString              `json:"thumbnail_url"`
	Difficulty    PracticeProjectsDifficulty  `json:"difficulty"`
	EstimatedTime int32                       `json:"estimated_time"`
	Tags          sql.NullString              `json:"tags"`
	ProjectType   PracticeProjectsProjectType `json:"project_type"`
	OrderIndex    int32                       `json:"order_index"`
	Requirements  sql.NullString              `json:"requirements"`
	Objectives    sql.NullString              `json:"objectives"`
	IsActive      bool                        `json:"is_active"`
	UpdatedAt     time.Time                   `json:"updated_at"`
}

func (q *Queries) CreatePracticeProject(ctx context.Context, arg CreatePracticeProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPracticeProject,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.ProjectUrl,
		arg.ThumbnailUrl,
		arg.Difficulty,
		arg.EstimatedTime,
		arg.Tags,
		arg.ProjectType,
		arg.OrderIndex,
		arg.Requirements,
		arg.Objectives,
		arg.IsActive,
		arg.UpdatedAt,
	)
}

const deletePracticeProject = `-- name: DeletePracticeProject :exec
DELETE FROM practice_projects WHERE id = ?
`

func (q *Queries) DeletePracticeProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePracticeProject, id)
	return err
}

const getActiveEnrollmentForUserCourse = `-- name: GetActiveEnrollmentForUserCourse :one
SELECT id FROM enrollments
WHERE user_id = ? AND course_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetActiveEnrollmentForUserCourseParams struct {
	UserID   string         `json:"user_id"`
	CourseID sql.NullString `json:"course_id"`
}

// Used to check if user has an active enrollment for a paid course.
func (q *Queries) GetActiveEnrollmentForUserCourse(ctx context.Context, arg GetActiveEnrollmentForUserCourseParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getActiveEnrollmentForUserCourse, arg.UserID, arg.CourseID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getCourseForPracticeAccess = `-- name: GetCourseForPracticeAccess :one
SELECT cost_type FROM courses WHERE id = ?
`

// Used by assertCourseAccess to check costType before allowing access.
func (q *Queries) GetCourseForPracticeAccess(ctx context.Context, id string) (CoursesCostType, error) {
	row := q.db.QueryRowContext(ctx, getCourseForPracticeAccess, id)
	var cost_type CoursesCostType
	err := row.Scan(&cost_type)
	return cost_type, err
}

const getPracticeCompletion = `-- name: GetPracticeCompletion :one
SELECT id, user_id, project_id, status, started_at, completed_at, submission_url, notes, deleted_at FROM practice_completions WHERE user_id = ? AND project_id = ?
`

type GetPracticeCompletionParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

// Used by start/complete/skip. Unique (user_id, project_id).
func (q *Queries) GetPracticeCompletion(ctx context.Context, arg GetPracticeCompletionParams) (PracticeCompletion, error) {
	row := q.db.QueryRowContext(ctx, getPracticeCompletion, arg.UserID, arg.ProjectID)
	var i PracticeCompletion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.SubmissionUrl,
		&i.Notes,
		&i.DeletedAt,
	)
	return i, err
}

const getPracticeProjectByID = `-- name: GetPracticeProjectByID :one
SELECT id, course_id, title, description, project_url, thumbnail_url, difficulty, estimated_time, tags, project_type, order_index, requirements, objectives, is_active, created_at, updated_at FROM practice_projects WHERE id = ?
`

func (q *Queries) GetPracticeProjectByID(ctx context.Context, id string) (PracticeProject, error) {
	row := q.db.QueryRowContext(ctx, getPracticeProjectByID, id)
	var i PracticeProject
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.ProjectUrl,
		&i.ThumbnailUrl,
		&i.Difficulty,
		&i.EstimatedTime,
		&i.Tags,
		&i.ProjectType,
		&i.OrderIndex,
		&i.Requirements,
		&i.Objectives,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPracticeProjectsByCourse = `-- name: ListAllPracticeProjectsByCourse :many
SELECT id, course_id, title, description, project_url, thumbnail_url, difficulty, estimated_time, tags, project_type, order_index, requirements, objectives, is_active, created_at, updated_at FROM practice_projects
WHERE course_id = ?
ORDER BY order_index ASC, created_at ASC
LIMIT 100
`

// Admin: all projects (active + inactive).
func (q *Queries) ListAllPracticeProjectsByCourse(ctx context.Context, courseID string) ([]PracticeProject, error) {
	rows, err := q.db.QueryContext(ctx, listAllPracticeProjectsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeProject{}
	for rows.Next() {
		var i PracticeProject
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.ProjectUrl,
			&i.ThumbnailUrl,
			&i.Difficulty,
			&i.EstimatedTime,
			&i.Tags,
			&i.ProjectType,
			&i.OrderIndex,
			&i.Requirements,
			&i.Objectives,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPracticeProjectsByCourse = `-- name: ListPracticeProjectsByCourse :many
SELECT id, course_id, title, description, project_url, thumbnail_url, difficulty, estimated_time, tags, project_type, order_index, requirements, objectives, is_active, created_at, updated_at FROM practice_projects
WHERE course_id = ? AND is_active = 1
ORDER BY order_index ASC, created_at ASC
LIMIT 100
`

// Active projects only, ordered. Public list endpoint.
func (q *Queries) ListPracticeProjectsByCourse(ctx context.Context, courseID string) ([]PracticeProject, error) {
	rows, err := q.db.QueryContext(ctx, listPracticeProjectsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeProject{}
	for rows.Next() {
		var i PracticeProject
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.ProjectUrl,
			&i.ThumbnailUrl,
			&i.Difficulty,
			&i.EstimatedTime,
			&i.Tags,
			&i.ProjectType,
			&i.OrderIndex,
			&i.Requirements,
			&i.Objectives,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPracticeCompletions = `-- name: ListUserPracticeCompletions :many
SELECT pc.id, pc.user_id, pc.project_id, pc.status, pc.started_at,
       pc.completed_at, pc.submission_url, pc.notes, pc.deleted_at,
       pp.id, pp.course_id, pp.title, pp.difficulty, pp.estimated_time, pp.project_type
FROM practice_completions pc
JOIN practice_projects pp ON pp.id = pc.project_id
WHERE pc.user_id = ? AND (? = '' OR pp.course_id = ?)
ORDER BY pc.started_at DESC
`

type ListUserPracticeCompletionsParams struct {
	UserID   string      `json:"user_id"`
	Column2  interface{} `json:"column_2"`
	CourseID string      `json:"course_id"`
}

type ListUserPracticeCompletionsRow struct {
	ID            string                      `json:"id"`
	UserID        string                      `json:"user_id"`
	ProjectID     string                      `json:"project_id"`
	Status        PracticeCompletionsStatus   `json:"status"`
	StartedAt     time.Time                   `json:"started_at"`
	CompletedAt   sql.NullTime                `json:"completed_at"`
	SubmissionUrl sql.NullString              `json:"submission_url"`
	Notes         sql.NullString              `json:"notes"`
	DeletedAt     sql.NullTime                `json:"deleted_at"`
	ID_2          string                      `json:"id_2"`
	CourseID      string                      `json:"course_id"`
	Title         string                      `json:"title"`
	Difficulty    PracticeProjectsDifficulty  `json:"difficulty"`
	EstimatedTime int32                       `json:"estimated_time"`
	ProjectType   PracticeProjectsProjectType `json:"project_type"`
}

// Used by getUserProgress. Joins project to filter by courseId.
func (q *Queries) ListUserPracticeCompletions(ctx context.Context, arg ListUserPracticeCompletionsParams) ([]ListUserPracticeCompletionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserPracticeCompletions, arg.UserID, arg.Column2, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPracticeCompletionsRow{}
	for rows.Next() {
		var i ListUserPracticeCompletionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.SubmissionUrl,
			&i.Notes,
			&i.DeletedAt,
			&i.ID_2,
			&i.CourseID,
			&i.Title,
			&i.Difficulty,
			&i.EstimatedTime,
			&i.ProjectType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePracticeCompletion = `-- name: UpdatePracticeCompletion :exec
UPDATE practice_completions
SET status = ?, completed_at = ?, submission_url = ?, notes = ?
WHERE user_id = ? AND project_id = ?
`

type UpdatePracticeCompletionParams struct {
	Status        PracticeCompletionsStatus `json:"status"`
	CompletedAt   sql.NullTime              `json:"completed_at"`
	SubmissionUrl sql.NullString            `json:"submission_url"`
	Notes         sql.NullString            `json:"notes"`
	UserID        string                    `json:"user_id"`
	ProjectID     string                    `json:"project_id"`
}

func (q *Queries) UpdatePracticeCompletion(ctx context.Context, arg UpdatePracticeCompletionParams) error {
	_, err := q.db.ExecContext(ctx, updatePracticeCompletion,
		arg.Status,
		arg.CompletedAt,
		arg.SubmissionUrl,
		arg.Notes,
		arg.UserID,
		arg.ProjectID,
	)
	return err
}

const updatePracticeProject = `-- name: UpdatePracticeProject :exec
UPDATE practice_projects
SET title = ?, description = ?, project_url = ?, thumbnail_url = ?, difficulty = ?,
    estimated_time = ?, tags = ?, project_type = ?, order_index = ?, requirements = ?,
    objectives = ?, is_active = ?, updated_at = ?
WHERE id = ?
`

type UpdatePracticeProjectParams struct {
	Title         string                      `json:"title"`
	Description   string                      `json:"description"`
	ProjectUrl    string                      `json:"project_url"`
	ThumbnailUrl  sql.NullString              `json:"thumbnail_url"`
	Difficulty    PracticeProjectsDifficulty  `json:"difficulty"`
	EstimatedTime int32                       `json:"estimated_time"`
	Tags          sql.NullString              `json:"tags"`
	ProjectType   PracticeProjectsProjectType `json:"project_type"`
	OrderIndex    int32                       `json:"order_index"`
	Requirements  sql.NullString              `json:"requirements"`
	Objectives    sql.NullString              `json:"objectives"`
	IsActive      bool                        `json:"is_active"`
	UpdatedAt     time.Time                   `json:"updated_at"`
	ID            string                      `json:"id"`
}

func (q *Queries) UpdatePracticeProject(ctx context.Context, arg UpdatePracticeProjectParams) error {
	_, err := q.db.ExecContext(ctx, updatePracticeProject,
		arg.Title,
		arg.Description,
		arg.ProjectUrl,
		arg.ThumbnailUrl,
		arg.Difficulty,
		arg.EstimatedTime,
		arg.Tags,
		arg.ProjectType,
		arg.OrderIndex,
		arg.Requirements,
		arg.Objectives,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
