// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCompletedCoursesByUser = `-- name: CountCompletedCoursesByUser :one
SELECT COUNT(DISTINCT course_id) FROM progress_records
WHERE user_id = ? AND status = 'completed'
GROUP BY course_id
HAVING COUNT(DISTINCT lesson_id) = (
  SELECT COUNT(*) FROM lessons l
  WHERE l.course_id = progress_records.course_id
    AND l.deleted_at IS NULL
)
`

// Returns the number of courses the user has fully completed.
// "Fully completed" = all lessons in the course have a progress
// record with status='completed' for this user.
func (q *Queries) CountCompletedCoursesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedCoursesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedLessonsByUser = `-- name: CountCompletedLessonsByUser :one
SELECT COUNT(*) FROM progress_records
WHERE user_id = ? AND status = 'completed'
`

// Used by badges.computeProgress (course_completed, lessons_completed)
// and orders.CheckRefundEligibility.
func (q *Queries) CountCompletedLessonsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedLessonsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProgressByUser = `-- name: GetProgressByUser :many
SELECT id, user_id, course_id, lesson_id, status, completed_at, last_position, updated_at FROM progress_records
WHERE user_id = ?
ORDER BY updated_at DESC
LIMIT 500
`

// All progress records for a user, newest first.
func (q *Queries) GetProgressByUser(ctx context.Context, userID string) ([]ProgressRecord, error) {
	rows, err := q.db.QueryContext(ctx, getProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressRecord{}
	for rows.Next() {
		var i ProgressRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.LessonID,
			&i.Status,
			&i.CompletedAt,
			&i.LastPosition,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgressByUserCourse = `-- name: GetProgressByUserCourse :many
SELECT id, user_id, course_id, lesson_id, status, completed_at, last_position, updated_at FROM progress_records
WHERE user_id = ? AND course_id = ?
ORDER BY updated_at DESC
`

type GetProgressByUserCourseParams struct {
	UserID   string `json:"user_id"`
	CourseID string `json:"course_id"`
}

// All progress records for a user in a specific course.
func (q *Queries) GetProgressByUserCourse(ctx context.Context, arg GetProgressByUserCourseParams) ([]ProgressRecord, error) {
	rows, err := q.db.QueryContext(ctx, getProgressByUserCourse, arg.UserID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressRecord{}
	for rows.Next() {
		var i ProgressRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.LessonID,
			&i.Status,
			&i.CompletedAt,
			&i.LastPosition,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgressByUserLesson = `-- name: GetProgressByUserLesson :one
SELECT id, user_id, course_id, lesson_id, status, completed_at, last_position, updated_at FROM progress_records
WHERE user_id = ? AND lesson_id = ?
`

type GetProgressByUserLessonParams struct {
	UserID   string `json:"user_id"`
	LessonID string `json:"lesson_id"`
}

// Used by completeLesson to detect existing record (unique on user+lesson).
func (q *Queries) GetProgressByUserLesson(ctx context.Context, arg GetProgressByUserLessonParams) (ProgressRecord, error) {
	row := q.db.QueryRowContext(ctx, getProgressByUserLesson, arg.UserID, arg.LessonID)
	var i ProgressRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.LessonID,
		&i.Status,
		&i.CompletedAt,
		&i.LastPosition,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompletedCourseIDs = `-- name: ListCompletedCourseIDs :many
SELECT DISTINCT pr.course_id FROM progress_records pr
WHERE pr.user_id = ? AND pr.status = 'completed'
GROUP BY pr.course_id
HAVING COUNT(DISTINCT pr.lesson_id) = (
  SELECT COUNT(*) FROM lessons l
  JOIN chapters c ON c.id = l.chapter_id
  WHERE c.course_id = pr.course_id
    AND l.deleted_at IS NULL
    AND c.deleted_at IS NULL
)
`

// Returns the list of fully-completed course IDs for a user. Used by
// badges.computeProgress (course_specific leaf) and admin stats.
// Lessons don't have a direct course_id; the join goes lesson →
// chapter → course.
func (q *Queries) ListCompletedCourseIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedCourseIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var course_id string
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedDatesByUser = `-- name: ListCompletedDatesByUser :many
SELECT DISTINCT DATE(completed_at) AS d FROM progress_records
WHERE user_id = ? AND status = 'completed' AND completed_at IS NOT NULL
ORDER BY d DESC
LIMIT 365
`

// Distinct completed_at dates for streak calculation.
// Returned as DATE strings (e.g. "2026-08-11") for easy diff.
func (q *Queries) ListCompletedDatesByUser(ctx context.Context, userID string) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedDatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var d time.Time
		if err := rows.Scan(&d); err != nil {
			return nil, err
		}
		items = append(items, d)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProgress = `-- name: UpsertProgress :execresult
INSERT INTO progress_records
  (id, user_id, course_id, lesson_id, status, completed_at, last_position, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  status = VALUES(status),
  completed_at = VALUES(completed_at),
  last_position = VALUES(last_position),
  updated_at = VALUES(updated_at)
`

type UpsertProgressParams struct {
	ID           string                `json:"id"`
	UserID       string                `json:"user_id"`
	CourseID     string                `json:"course_id"`
	LessonID     string                `json:"lesson_id"`
	Status       ProgressRecordsStatus `json:"status"`
	CompletedAt  sql.NullTime          `json:"completed_at"`
	LastPosition sql.NullInt32         `json:"last_position"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

// Insert or update by user+lesson. ON DUPLICATE updates status +
// completed_at + last_position.
func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertProgress,
		arg.ID,
		arg.UserID,
		arg.CourseID,
		arg.LessonID,
		arg.Status,
		arg.CompletedAt,
		arg.LastPosition,
		arg.UpdatedAt,
	)
}
