// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createResource = `-- name: CreateResource :execresult
INSERT INTO resources (id, lesson_id, title, url, type, is_locked, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateResourceParams struct {
	ID        string        `json:"id"`
	LessonID  string        `json:"lesson_id"`
	Title     string        `json:"title"`
	Url       string        `json:"url"`
	Type      ResourcesType `json:"type"`
	IsLocked  bool          `json:"is_locked"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createResource,
		arg.ID,
		arg.LessonID,
		arg.Title,
		arg.Url,
		arg.Type,
		arg.IsLocked,
		arg.CreatedAt,
	)
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, lesson_id, title, url, type, is_locked, created_at, deleted_at
FROM resources
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetResourceByID(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResourceByID, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Title,
		&i.Url,
		&i.Type,
		&i.IsLocked,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listResourcesByLesson = `-- name: ListResourcesByLesson :many
SELECT id, lesson_id, title, url, type, is_locked, created_at, deleted_at
FROM resources
WHERE lesson_id = ? AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListResourcesByLesson(ctx context.Context, lessonID string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByLesson, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Title,
			&i.Url,
			&i.Type,
			&i.IsLocked,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resourcesByIDs = `-- name: ResourcesByIDs :many
SELECT id, lesson_id FROM resources WHERE id IN (/*SLICE:ids*/?)
`

type ResourcesByIDsRow struct {
	ID       string `json:"id"`
	LessonID string `json:"lesson_id"`
}

// Used by future reorder to verify ownership (lessonId).
func (q *Queries) ResourcesByIDs(ctx context.Context, ids []string) ([]ResourcesByIDsRow, error) {
	query := resourcesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourcesByIDsRow{}
	for rows.Next() {
		var i ResourcesByIDsRow
		if err := rows.Scan(&i.ID, &i.LessonID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteResource = `-- name: SoftDeleteResource :exec
UPDATE resources
SET deleted_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteResourceParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteResource(ctx context.Context, arg SoftDeleteResourceParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteResource, arg.DeletedAt, arg.ID)
	return err
}

const softDeleteResourcesByLesson = `-- name: SoftDeleteResourcesByLesson :execrows
UPDATE resources
SET deleted_at = ?
WHERE lesson_id = ? AND deleted_at IS NULL
`

type SoftDeleteResourcesByLessonParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	LessonID  string       `json:"lesson_id"`
}

// Cascade soft-delete for lesson delete. Returns count.
func (q *Queries) SoftDeleteResourcesByLesson(ctx context.Context, arg SoftDeleteResourcesByLessonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteResourcesByLesson, arg.DeletedAt, arg.LessonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateResource = `-- name: UpdateResource :exec
UPDATE resources
SET title = ?, url = ?, type = ?, is_locked = ?
WHERE id = ?
`

type UpdateResourceParams struct {
	Title    string        `json:"title"`
	Url      string        `json:"url"`
	Type     ResourcesType `json:"type"`
	IsLocked bool          `json:"is_locked"`
	ID       string        `json:"id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) error {
	_, err := q.db.ExecContext(ctx, updateResource,
		arg.Title,
		arg.Url,
		arg.Type,
		arg.IsLocked,
		arg.ID,
	)
	return err
}
