// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createReview = `-- name: CreateReview :execresult
INSERT INTO reviews
  (id, user_id, course_id, rating, content, helpful, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 0, ?, ?)
`

type CreateReviewParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CourseID  string    `json:"course_id"`
	Rating    int32     `json:"rating"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReview,
		arg.ID,
		arg.UserID,
		arg.CourseID,
		arg.Rating,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, user_id, course_id, rating, content, helpful, deleted_at, created_at, updated_at FROM reviews WHERE id = ?
`

func (q *Queries) GetReviewByID(ctx context.Context, id string) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.Rating,
		&i.Content,
		&i.Helpful,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByUserCourse = `-- name: GetReviewByUserCourse :one
SELECT id, user_id, course_id, rating, content, helpful, deleted_at, created_at, updated_at FROM reviews WHERE user_id = ? AND course_id = ?
`

type GetReviewByUserCourseParams struct {
	UserID   string `json:"user_id"`
	CourseID string `json:"course_id"`
}

// Idempotency: one review per (user, course).
func (q *Queries) GetReviewByUserCourse(ctx context.Context, arg GetReviewByUserCourseParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByUserCourse, arg.UserID, arg.CourseID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.Rating,
		&i.Content,
		&i.Helpful,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementReviewHelpful = `-- name: IncrementReviewHelpful :exec
UPDATE reviews SET helpful = helpful + 1, updated_at = ? WHERE id = ?
`

type IncrementReviewHelpfulParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) IncrementReviewHelpful(ctx context.Context, arg IncrementReviewHelpfulParams) error {
	_, err := q.db.ExecContext(ctx, incrementReviewHelpful, arg.UpdatedAt, arg.ID)
	return err
}

const listAllReviews = `-- name: ListAllReviews :many
SELECT id, user_id, course_id, rating, content, helpful, deleted_at, created_at, updated_at FROM reviews
WHERE (? = '' OR course_id = ?)
  AND (? = 0 OR rating = ?)
  AND (? = 0 OR deleted_at IS NOT NULL)
ORDER BY created_at DESC
LIMIT ?
`

type ListAllReviewsParams struct {
	Column1  interface{} `json:"column_1"`
	CourseID string      `json:"course_id"`
	Column3  interface{} `json:"column_3"`
	Rating   int32       `json:"rating"`
	Column5  interface{} `json:"column_5"`
	Limit    int32       `json:"limit"`
}

// Admin: full list with optional filters. Soft-delete aware.
func (q *Queries) ListAllReviews(ctx context.Context, arg ListAllReviewsParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listAllReviews,
		arg.Column1,
		arg.CourseID,
		arg.Column3,
		arg.Rating,
		arg.Column5,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.Rating,
			&i.Content,
			&i.Helpful,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByCourse = `-- name: ListReviewsByCourse :many
SELECT id, user_id, course_id, rating, content, helpful, deleted_at, created_at, updated_at FROM reviews
WHERE course_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ?
`

type ListReviewsByCourseParams struct {
	CourseID string `json:"course_id"`
	Limit    int32  `json:"limit"`
}

// Public list of reviews for a course, newest first. Excludes
// soft-deleted (deleted_at IS NOT NULL).
func (q *Queries) ListReviewsByCourse(ctx context.Context, arg ListReviewsByCourseParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByCourse, arg.CourseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.Rating,
			&i.Content,
			&i.Helpful,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteReview = `-- name: SoftDeleteReview :exec
UPDATE reviews SET deleted_at = ?, updated_at = ? WHERE id = ?
`

type SoftDeleteReviewParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteReview(ctx context.Context, arg SoftDeleteReviewParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteReview, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}
