// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"
	"database/sql"
)

const uploadSetCourseThumbnail = `-- name: UploadSetCourseThumbnail :execrows
UPDATE courses SET thumbnail = ? WHERE id = ?
`

type UploadSetCourseThumbnailParams struct {
	Thumbnail string `json:"thumbnail"`
	ID        string `json:"id"`
}

func (q *Queries) UploadSetCourseThumbnail(ctx context.Context, arg UploadSetCourseThumbnailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetCourseThumbnail, arg.Thumbnail, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetDegreeThumbnail = `-- name: UploadSetDegreeThumbnail :execrows
UPDATE nano_degrees SET thumbnail = ? WHERE id = ?
`

type UploadSetDegreeThumbnailParams struct {
	Thumbnail sql.NullString `json:"thumbnail"`
	ID        string         `json:"id"`
}

func (q *Queries) UploadSetDegreeThumbnail(ctx context.Context, arg UploadSetDegreeThumbnailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetDegreeThumbnail, arg.Thumbnail, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetHackathonBanner = `-- name: UploadSetHackathonBanner :execrows
UPDATE hackathons SET banner_url = ? WHERE id = ?
`

type UploadSetHackathonBannerParams struct {
	BannerUrl sql.NullString `json:"banner_url"`
	ID        string         `json:"id"`
}

func (q *Queries) UploadSetHackathonBanner(ctx context.Context, arg UploadSetHackathonBannerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetHackathonBanner, arg.BannerUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetJudgeAvatar = `-- name: UploadSetJudgeAvatar :execrows
UPDATE judges SET avatar_url = ? WHERE id = ?
`

type UploadSetJudgeAvatarParams struct {
	AvatarUrl sql.NullString `json:"avatar_url"`
	ID        string         `json:"id"`
}

func (q *Queries) UploadSetJudgeAvatar(ctx context.Context, arg UploadSetJudgeAvatarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetJudgeAvatar, arg.AvatarUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetLessonVideo = `-- name: UploadSetLessonVideo :execrows
UPDATE lessons SET video_url = ? WHERE id = ? AND deleted_at IS NULL
`

type UploadSetLessonVideoParams struct {
	VideoUrl sql.NullString `json:"video_url"`
	ID       string         `json:"id"`
}

func (q *Queries) UploadSetLessonVideo(ctx context.Context, arg UploadSetLessonVideoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetLessonVideo, arg.VideoUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetResourceUrl = `-- name: UploadSetResourceUrl :execrows
UPDATE resources SET url = ? WHERE id = ? AND deleted_at IS NULL
`

type UploadSetResourceUrlParams struct {
	Url string `json:"url"`
	ID  string `json:"id"`
}

func (q *Queries) UploadSetResourceUrl(ctx context.Context, arg UploadSetResourceUrlParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetResourceUrl, arg.Url, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetSponsorLogo = `-- name: UploadSetSponsorLogo :execrows
UPDATE sponsors SET logo_url = ? WHERE id = ?
`

type UploadSetSponsorLogoParams struct {
	LogoUrl sql.NullString `json:"logo_url"`
	ID      string         `json:"id"`
}

func (q *Queries) UploadSetSponsorLogo(ctx context.Context, arg UploadSetSponsorLogoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetSponsorLogo, arg.LogoUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetSubmissionVideo = `-- name: UploadSetSubmissionVideo :execrows
UPDATE submissions SET video_url = ? WHERE id = ? AND deleted_at IS NULL
`

type UploadSetSubmissionVideoParams struct {
	VideoUrl sql.NullString `json:"video_url"`
	ID       string         `json:"id"`
}

func (q *Queries) UploadSetSubmissionVideo(ctx context.Context, arg UploadSetSubmissionVideoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetSubmissionVideo, arg.VideoUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadSetUserAvatar = `-- name: UploadSetUserAvatar :execrows
UPDATE users SET avatar_url = ? WHERE id = ? AND deleted_at IS NULL
`

type UploadSetUserAvatarParams struct {
	AvatarUrl sql.NullString `json:"avatar_url"`
	ID        string         `json:"id"`
}

func (q *Queries) UploadSetUserAvatar(ctx context.Context, arg UploadSetUserAvatarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, uploadSetUserAvatar, arg.AvatarUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
