// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urlimport.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUrlImport = `-- name: CreateUrlImport :execresult
INSERT INTO url_imports
  (id, url, platform, status, requested_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUrlImportParams struct {
	ID          string             `json:"id"`
	Url         string             `json:"url"`
	Platform    UrlImportsPlatform `json:"platform"`
	Status      UrlImportsStatus   `json:"status"`
	RequestedBy sql.NullString     `json:"requested_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// Record a new URL-import task. T22 stores every request as a row
// with status='pending'; T22.1 will flip the status when the real
// metadata extraction completes.
func (q *Queries) CreateUrlImport(ctx context.Context, arg CreateUrlImportParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUrlImport,
		arg.ID,
		arg.Url,
		arg.Platform,
		arg.Status,
		arg.RequestedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getUrlImportByID = `-- name: GetUrlImportByID :one
SELECT id, url, platform, status, requested_by, result_course_id, error_message, title, author, thumbnail_url, duration_seconds, extracted_json, fetched_at, created_at, updated_at FROM url_imports WHERE id = ?
`

func (q *Queries) GetUrlImportByID(ctx context.Context, id string) (UrlImport, error) {
	row := q.db.QueryRowContext(ctx, getUrlImportByID, id)
	var i UrlImport
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Platform,
		&i.Status,
		&i.RequestedBy,
		&i.ResultCourseID,
		&i.ErrorMessage,
		&i.Title,
		&i.Author,
		&i.ThumbnailUrl,
		&i.DurationSeconds,
		&i.ExtractedJson,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUrlImports = `-- name: ListUrlImports :many
SELECT id, url, platform, status, requested_by, result_course_id, error_message, title, author, thumbnail_url, duration_seconds, extracted_json, fetched_at, created_at, updated_at FROM url_imports
ORDER BY created_at DESC
LIMIT 100
`

// Recent import tasks, newest first. Used by the admin dashboard
// (T22 ships without a dedicated list endpoint, but the query is
// here for the T22.1 follow-up that exposes /admin/imports).
func (q *Queries) ListUrlImports(ctx context.Context) ([]UrlImport, error) {
	rows, err := q.db.QueryContext(ctx, listUrlImports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UrlImport{}
	for rows.Next() {
		var i UrlImport
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Platform,
			&i.Status,
			&i.RequestedBy,
			&i.ResultCourseID,
			&i.ErrorMessage,
			&i.Title,
			&i.Author,
			&i.ThumbnailUrl,
			&i.DurationSeconds,
			&i.ExtractedJson,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUrlImportsByRequester = `-- name: ListUrlImportsByRequester :many
SELECT id, url, platform, status, requested_by, result_course_id, error_message, title, author, thumbnail_url, duration_seconds, extracted_json, fetched_at, created_at, updated_at FROM url_imports
WHERE requested_by = ?
ORDER BY created_at DESC
LIMIT 100
`

// Per-admin "what did I import" view. T22.1 will mount this.
func (q *Queries) ListUrlImportsByRequester(ctx context.Context, requestedBy sql.NullString) ([]UrlImport, error) {
	rows, err := q.db.QueryContext(ctx, listUrlImportsByRequester, requestedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UrlImport{}
	for rows.Next() {
		var i UrlImport
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Platform,
			&i.Status,
			&i.RequestedBy,
			&i.ResultCourseID,
			&i.ErrorMessage,
			&i.Title,
			&i.Author,
			&i.ThumbnailUrl,
			&i.DurationSeconds,
			&i.ExtractedJson,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUrlImportFetched = `-- name: UpdateUrlImportFetched :exec
UPDATE url_imports
SET status = ?,
    title = ?,
    author = ?,
    thumbnail_url = ?,
    duration_seconds = ?,
    extracted_json = ?,
    fetched_at = ?,
    error_message = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUrlImportFetchedParams struct {
	Status          UrlImportsStatus `json:"status"`
	Title           sql.NullString   `json:"title"`
	Author          sql.NullString   `json:"author"`
	ThumbnailUrl    sql.NullString   `json:"thumbnail_url"`
	DurationSeconds sql.NullInt32    `json:"duration_seconds"`
	ExtractedJson   sql.NullString   `json:"extracted_json"`
	FetchedAt       sql.NullTime     `json:"fetched_at"`
	ErrorMessage    sql.NullString   `json:"error_message"`
	UpdatedAt       time.Time        `json:"updated_at"`
	ID              string           `json:"id"`
}

// T22.1: persist the metadata extracted from YouTube oEmbed or the
// Bilibili view API, and flip the status to 'fetched'. All metadata
// columns are nullable so partial fetches (e.g. Bilibili 404) still
// land a row, and Gemini step failures can later promote to 'imported'
// or roll back to 'failed' from the same row.
func (q *Queries) UpdateUrlImportFetched(ctx context.Context, arg UpdateUrlImportFetchedParams) error {
	_, err := q.db.ExecContext(ctx, updateUrlImportFetched,
		arg.Status,
		arg.Title,
		arg.Author,
		arg.ThumbnailUrl,
		arg.DurationSeconds,
		arg.ExtractedJson,
		arg.FetchedAt,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUrlImportStatus = `-- name: UpdateUrlImportStatus :exec
UPDATE url_imports
SET status = ?,
    result_course_id = ?,
    error_message = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUrlImportStatusParams struct {
	Status         UrlImportsStatus `json:"status"`
	ResultCourseID sql.NullString   `json:"result_course_id"`
	ErrorMessage   sql.NullString   `json:"error_message"`
	UpdatedAt      time.Time        `json:"updated_at"`
	ID             string           `json:"id"`
}

// Flip a task from pending → completed/failed. result_course_id and
// error_message are nullable.
func (q *Queries) UpdateUrlImportStatus(ctx context.Context, arg UpdateUrlImportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUrlImportStatus,
		arg.Status,
		arg.ResultCourseID,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
