// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) AS count
FROM users
WHERE role = 'admin' AND deleted_at IS NULL
`

// Last-admin guard for the disable endpoint. Counts non-deleted admins.
// Phase 2 T11: "不能停用最后一个管理员账号" rule.
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
  id, email, password_hash, name, role, avatar_url, password_reset_required,
  points, level, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID                    string         `json:"id"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	Name                  string         `json:"name"`
	Role                  UsersRole      `json:"role"`
	AvatarUrl             sql.NullString `json:"avatar_url"`
	PasswordResetRequired bool           `json:"password_reset_required"`
	Points                int32          `json:"points"`
	Level                 int32          `json:"level"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

// Inserts a new user. Caller is responsible for generating the UUID.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.AvatarUrl,
		arg.PasswordResetRequired,
		arg.Points,
		arg.Level,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, avatar_url, password_reset_required,
       points, level, deleted_at, created_at, updated_at, last_login_at
FROM users
WHERE email = ? AND deleted_at IS NULL
`

// Used by login flow to look up a user by email.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.PasswordResetRequired,
		&i.Points,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, avatar_url, password_reset_required,
       points, level, deleted_at, created_at, updated_at, last_login_at
FROM users
WHERE id = ?
`

// Retrieves a single user by primary key. Returns ErrNoRows if not found.
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.PasswordResetRequired,
		&i.Points,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, email, password_hash, name, role, avatar_url, password_reset_required,
       points, level, deleted_at, created_at, updated_at, last_login_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListActiveUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Returns active (non-deleted) users, newest first. Paged.
func (q *Queries) ListActiveUsers(ctx context.Context, arg ListActiveUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.AvatarUrl,
			&i.PasswordResetRequired,
			&i.Points,
			&i.Level,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at = NULL, updated_at = ?
WHERE id = ?
`

type RestoreUserParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

// Re-activate a soft-deleted account. Sets deleted_at = NULL. The user
// must already exist (callers verify with GetUserByID first).
func (q *Queries) RestoreUser(ctx context.Context, arg RestoreUserParams) error {
	_, err := q.db.ExecContext(ctx, restoreUser, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = ?, updated_at = ?
WHERE id = ?
`

type SoftDeleteUserParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

// Admin ban / user self-delete goes through deleted_at (see schema.prisma line 21-22).
// Never prisma.user.delete — 17 FK cascades would orphan certificates / points / reviews / progress.
func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = ?, avatar_url = ?, role = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Role      UsersRole      `json:"role"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

// Partial update: name, avatar_url, role. Caller decides which fields to
// change and passes the right sql.Null* values. updated_at always bumps.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.AvatarUrl,
		arg.Role,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserLastLoginParams struct {
	LastLoginAt sql.NullTime `json:"last_login_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          string       `json:"id"`
}

// Bumps last_login_at on successful authentication.
func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, arg.LastLoginAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?, password_reset_required = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash          string    `json:"password_hash"`
	PasswordResetRequired bool      `json:"password_reset_required"`
	UpdatedAt             time.Time `json:"updated_at"`
	ID                    string    `json:"id"`
}

// Change password (current user flow) and reset password (admin flow).
// Both write the same columns; the difference is whether the caller also
// flips password_reset_required. Service layer is responsible for that flag.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword,
		arg.PasswordHash,
		arg.PasswordResetRequired,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
